### PR TITLE
# Kata Containers 1.10.0

### PR DESCRIPTION
**Pull request by katabuilder**
- Backport ch 0.4  for 1.10

df1be10 clh: remove not requried values
b27bdf4 clh: update api calls for latest master
2dc44f7 clh: update client
cf49d81 versions: update clh to v0.4.0

### CODE REVIEW

**Comment by jcvenegas** [comment]
hum the CI passed too quick, looking 
```
10:37:28 INFO: Check patterns: []
10:37:28 INFO: No force CI check patterns
10:37:28 INFO: No force check files found
10:37:28 INFO: No files to check in CI.
10:37:28 INFO: Fastpath short circuit returning from CI.
10:37:28 INFO: Files skipped are:
10:37:28 
10:37:28 VERSION
10:37:28 
10:37:28 INFO: Checking labels for PR kata-containers/runtime/2393
10:37:28 /tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR/go/src/github.com/kata-containers/tests/.ci/ci-fast-return.sh: line 243: jq: command not found
10:37:28 INFO: No forcing label found
10:37:28 Short circuit fast path skipping the rest of the CI.
```

Seems that jq is missing

**Comment by grahamwhaley** [comment]
so, two problems.....
1) why is `jq` not found (@GabyCT I think looked at something similar last week?)
2) why didn't the fastpath script pick up on that and fail, instead of passing! (my code I suspect...)

**Comment by GabyCT** [comment]
@jcvenegas and @grahamwhaley , yes last week I fixed an issue about `jq`
https://github.com/kata-containers/tests/commit/68b4532445eb70a44583829fff9f0c8879ded918

that is when we are using the `get_version` which I saw that it was only used at the `tests` repository , not sure how this can be related with the `ci-fast...sh`

**Comment by chavafg** [comment]
Looking at the `jenkins_job_build.sh` script, the reason that `jq` is not installed is because the `.ci/ci-fast-return.sh` runs before `.ci/setup_env_${ID}.sh`. 

iirc, @GabyCT was looking at `yq`, not `jq`.

**Pull request merged**
