### PR TITLE
version: Update kernel to lts 5.4.32

### LINKED ISSUE #2612: Update kernel to latest LTS 5.4.32

### PR DESCRIPTION
**Pull request by amshinde**
Update kernel from 5.4.15 to 5.4.32

Fixes #2612

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by amshinde** [comment]
@chavafg PTAL. Lets include this in the upcoming release.

**Comment by grahamwhaley** [comment]
ARM CI failed - don't think it is related. I'll give it a rebuild nudge anyway @Pennyzct 

```
01:03:01 ok 1 Setting sysctl
01:03:01 ~/workspace/kata-containers-runtime-ARM-18.04-PR/go/src/github.com/kata-containers/tests
01:03:01 [reset] Reading configuration from the cluster...
01:03:01 [reset] FYI: You can look at this config file with 'kubectl -n kube-system get cm kubeadm-config -oyaml'
01:03:01 [preflight] Running pre-flight checks
01:03:01 [reset] Removing info for node "arm-testing-2" from the ConfigMap "kubeadm-config" in the "kube-system" Namespace
01:03:01 W0415 00:03:01.279094   32325 removeetcdmember.go:61] [reset] failed to remove etcd member: error syncing endpoints with etc: etcdclient: no available endpoints
01:03:01 .Please manually remove this etcd member using etcdctl
01:03:01 [reset] Stopping the kubelet service
01:03:01 [reset] Unmounting mounted directories in "/var/lib/kubelet"
01:03:33 [reset] Deleting contents of config directories: [/etc/kubernetes/manifests /etc/kubernetes/pki]
01:03:33 [reset] Deleting files: [/etc/kubernetes/admin.conf /etc/kubernetes/kubelet.conf /etc/kubernetes/bootstrap-kubelet.conf /etc/kubernetes/controller-manager.conf /etc/kubernetes/scheduler.conf]
01:03:33 [reset] Deleting contents of stateful directories: [/var/lib/etcd /var/lib/kubelet /var/lib/dockershim /var/run/kubernetes /var/lib/cni]
01:03:33 
01:03:33 The reset process does not clean CNI configuration. To do so, you must remove /etc/cni/net.d
01:03:33 
01:03:33 The reset process does not reset or clean up iptables rules or IPVS tables.
01:03:33 If you wish to reset iptables, you must do so manually by using the "iptables" command.
01:03:33 
01:03:33 If your cluster was setup to utilize IPVS, run ipvsadm --clear (or similar)
01:03:33 to reset your system's IPVS tables.
01:03:33 
01:03:33 The reset process does not clean your kubeconfig files and you must remove them manually.
01:03:33 Please, check the contents of the $HOME/.kube/config file.
01:03:33 Bad argument `[unsupported'
01:03:33 Error occurred at line: 54
01:03:33 Try `iptables-restore -h' or 'iptables-restore --help' for more information.
01:03:33 Failed at 19: sudo iptables-restore < "$iptables_cache"
01:03:33 Failed at 39: bash -f "${SCRIPT_PATH}/cleanup_bare_metal_env.sh"
01:03:33 Failed at 1: popd
01:03:33 Makefile:148: recipe for target 'kubernetes' failed
01:03:33 make: *** [kubernetes] Error 2
01:03:33 Failed at 82: sudo -E PATH="$PATH" bash -c "make test"
01:03:34 Build step 'Execute shell' marked build as failure
```

**Comment by amshinde** [comment]
@grahamwhaley That has been failing in other PRs as well.
@Pennyzct @justin-he Can you take a look at the above error.

**Pull request merged**
