### PR TITLE
runtime-v2: Make sure Shutdown() only shuts the server down

### LINKED ISSUE #1150: runtime-v2: Make sure Shutdown() only shuts the server down
We should not stop and delete the sandbox from `Shutdown()` since the caller cannot check the error on this function. It's going to make the server exit, which will close the communication with the RPC server.

### PR DESCRIPTION
**Pull request by sboeuf**
Because the runtime v2 runs as a RPC server, the caller will at some
point use the Shutdown() API to shut down the server. Because this
will cause the server to exit, the caller cannot expect any valid
answer when calling this. That's why we cannot afford stopping and
deleting the sandbox from this function.

Instead, we move sandbox.Stop() and sandbox.Delete() to a more
appropriate API, the Delete() one.

Fixes #1150

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Comment by lifupan** [comment]
LGTM

**Comment by sboeuf** [comment]
@egernst @amshinde @bergwolf PTAL

**Comment by sboeuf** [comment]
`jenkins-ci-fedora-vsocks` fails after 20 seconds, and this is nothing related to this PR. Let's merge.

**Comment by grahamwhaley** [comment]
Yep, seems vsocks build is bust - @chavafg , feels like a new CI issue. Might this be an Azure related thing?
```
PR/go/src/github.com/kata-containers/tests
fatal: Couldn't find remote ref pull/1151/head
Build step 'Execute shell' marked build as failure
```

First candidate for the 'CI status' page/issue maybe?

**Pull request merged**
