### PR TITLE
CI: Enable checkcommits

### LINKED ISSUE #8: Enable checkcommits
Enable [checkcommits](https://github.com/clearcontainers/tests/tree/master/cmd/checkcommits) which will requires that all PRs have:

- a `Signed-off-by:` line.
- a `Fixes #XXX` comment where `XXX` is a github issue number.
- Requires all commits to have a "sub-system" followed by a colon, followed by a brief description.
- Requires a blank line after the subsystem.
- Requires all commits to have a fuller description after the sub-system that will contain the `Fixes ###` and `Signed-off-by:` comments.

### PR DESCRIPTION
**Pull request by jodh-intel**
Run the central static check script to enable `checkcommits`.

Fixes #8.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Blocked on https://github.com/kata-containers/tests/pull/61 (which will cause this to fail under Travis until that PR lands).

**Comment by jodh-intel** [comment]
https://github.com/kata-containers/tests/pull/61 is now merged, so this should now pass the Travis checks...

**Comment by jodh-intel** [comment]
Hi @bergwolf - could you review please?

**Comment by bergwolf** [comment]
lgtm!

**Comment by jodh-intel** [comment]
@grahamwhaley - pullapprove for some reason is ignoring your ack and not treating you as being in the `runtime` group, which you are ;(

**Comment by grahamwhaley** [comment]
odd. it has a tick (approve), but not picked up by pullapprove.  let us try again
lgtm
LTGM
ack
:-)
👍

**Comment by grahamwhaley** [comment]
nope, indeed, it has a mug on. I must have done something in a former life to upset it :-)

**Comment by WeiZhang555** [comment]
LGTM for merge!

**Pull request merged**
