### PR TITLE
Support the memory hotplugged remove

### PR DESCRIPTION
**Pull request by BetaXOi**
Fix: #791

### CODE REVIEW

**Comment by amshinde** [comment]
@BetaXOi Can you fix your commit message to include a subsystem and a description.
Please refer to the Contribution guidelines here:
https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format

cc @jcvenegas Can you take a look, since you have looking at memory hotplug/unplug.

**Comment by bergwolf** [comment]
I think we've decided to look at balloon and virtio-mem first.

**Comment by jcvenegas** [comment]
@BetaXOi as first step we are going to balloon + hotplug , I still would like to evaluate this approach in order to remove memory slots, but first I want to get numbers about the time it takes to remove an slot
under an stressed system. Lets work on that to get a clear about idea about it :).   But also as @bergwolf mentioned, for longer term solution we are evaluating to virtio-mem.

**Comment by raravena80** [comment]
@BetaXOi ping, any updates?

**Pull request closed without merging**
