### PR TITLE
backport: versions: Update firecracker to 0.21.3

### PR DESCRIPTION
**Pull request by amshinde**
Release included important security updates.

References:
https://github.com/firecracker-microvm/firecracker/issues/2057
https://github.com/firecracker-microvm/firecracker/issues/2177

Fixes: #3095

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>
(cherry picked from commit 11c8c19eb95505fff2075f0f3491d17dc83074a4)

### CODE REVIEW

**Review by jcvenegas — APPROVED** [review]

**Comment by amshinde** [comment]
@chavafg @GabyCT  I am seeing errors with docker installation.  Error log looks like :
```
13:13:23 Created symlink /etc/systemd/system/sockets.target.wants/docker.socket → /lib/systemd/system/docker.socket.
13:13:23 Job for docker.service failed because the control process exited with error code.
13:13:23 See "systemctl status docker.service" and "journalctl -xe" for details.
13:13:23 invoke-rc.d: initscript docker, action "start" failed.
13:13:23 ● docker.service - Docker Application Container Engine
13:13:23    Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
13:13:23    Active: activating (auto-restart) (Result: exit-code) since Wed 2020-12-09 21:13:23 UTC; 6ms ago
13:13:23      Docs: https://docs.docker.com
13:13:23   Process: 10770 ExecStart=/usr/bin/dockerd -H fd:// (code=exited, status=1/FAILURE)
13:13:23  Main PID: 10770 (code=exited, status=1/FAILURE)
13:13:23 dpkg: error processing package docker-ce (--configure):
13:13:23  installed docker-ce package post-installation script subprocess returned error exit status 1
13:13:23 Setting up cgroupfs-mount (1.4) ...
13:13:23 Processing triggers for systemd (237-3ubuntu10.43) ...
13:13:24 Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
13:13:33 Processing triggers for ureadahead (0.100.0-21) ...
13:13:33 Processing triggers for libc-bin (2.27-3ubuntu1) ...
13:13:33 Errors were encountered while processing:
13:13:33  docker-ce
13:13:34 E: Sub-process /usr/bin/dpkg returned an error code (1)
13:13:34 Build step 'Execute shell' marked build as failure
13:13:43 Performing Post build task...
13:13:43 Match found for :.* : True
```

**Review by jodh-intel — APPROVED** [review]

**Pull request merged**
