### PR TITLE
cli: Make message of using initrd OR rootfs clearer

### PR DESCRIPTION
**Pull request by nitkon**
Fixes:  #563

Signed-off-by: Nitesh Konkar niteshkonkar@in.ibm.com

### CODE REVIEW

**Comment by nitkon** [comment]
I feel that this commit makes the error message more explicit. I may be wrong. Feel free to NACK it if its not worth it. :-)

**Comment by grahamwhaley** [comment]
I can see the original message is a little confusing. Your new message is fine, but does not read too much like an `Error` to me though.

Combining the two a bit, how about:
`having both an image and an initrd defined in the configuration file is not supported`

/cc @jodh-intel for wordy input...

**Comment by sboeuf** [comment]
I am fine with this either way, but I would prefer @jodh-intel's opinion on how to turn this sentence the best way (as he's a native English speaker).

**Comment by jodh-intel** [comment]
+1 to @grahamwhaley's wording.

@nitkon - please add detail to the commit message though - a "bare fixes" is a bit too terse for my liking ;)

**Comment by nitkon** [comment]
@jodh-intel : Noted your comments. Updated my PR.

**Comment by jodh-intel** [comment]
Thanks @nitkon.

lgtm

**Pull request merged**
