### PR TITLE
doc: update architecture.md link

### PR DESCRIPTION
**Pull request by gabibeyer**
update architecture.md link, since it has moved to within the
design/ directory.

Fixes: #1462

Signed-off-by: Gabi Beyer <Gabrielle.n.beyer@intel.com>

### CODE REVIEW

**Comment by egernst** [comment]
@gabibeyer can you s/contributes to/Fixes/ ?

**Comment by egernst** [comment]
(looks good otherwise)

**Comment by gabibeyer** [comment]
Oh whoops, yes I'll fix that!

**Comment by gabibeyer** [comment]
I'll need to update the packaging repo and documentation repos as well :) someone else snagged the proxy fix already 😄

**Comment by amshinde** [comment]
@gabibeyer Can you change the "contributes to: to "Fixes"?
Our PR check tool expects a "Fixes" line.

**Pull request merged**
