### PR TITLE
vc: Utilize map for newMounts to speed up replaceOCIMountSource

### LINKED ISSUE #2212: Utilize map for newMounts to speed up replaceOCIMountSource
**Which feature do you think can be improved?**

Currently replaceOCIMountSource uses nested loop to match destinations of newMounts and ociMounts.

**How can it be improved?**

mountSharedDirMounts can return map for new mounts keyed by destination.
This way the inner loop of replaceOCIMountSource can become (one single) map lookup.

**Additional Information**

### PR DESCRIPTION
**Pull request by tedyu**
Fixes #2212

Signed-off-by: Ted Yu <yuzhihong@gmail.com>

### CODE REVIEW

**Comment by tedyu** [comment]
@jodh-intel 
Please review

**Comment by jodh-intel** [comment]
Thanks @tedyu. However, Travis is failing in the static analysis checks:

```
virtcontainers/container.go:610:18: nilness: nil dereference in map update (govet)
		sharedDirMounts[sharedDirMount.Destination] = sharedDirMount
		               ^
The command ".ci/static-checks.sh" failed and exited with 1 during .
```

**Comment by tedyu** [comment]
@jodh-intel 
When you were writing the above review, I pushed fix to the branch.

Please take another look.

**Comment by tedyu** [comment]
@jodh-intel
gentle ping for review

**Comment by egernst** [comment]
@tedyu - thanks for the PR. were you able to capture a speed up for the refactor?

**Comment by grahamwhaley** [comment]
@tedyu - just in case it helps, there are some metrics tests and a pdf report generator over [here](https://github.com/kata-containers/tests/tree/master/metrics/report) that could possibly help do some measurements.

**Comment by tedyu** [comment]
@grahamwhaley 
Thanks for the pointer.
I will look at the metrics tests.

**Comment by tedyu** [comment]
@amshinde @egernst 
All tests passed.

**Comment by tedyu** [comment]
@amshinde @egernst
gentle ping

**Pull request merged**
