### PR TITLE
Docs : Add minimal contribution guidelines

### PR DESCRIPTION
**Pull request by ydjainopensource**
Fixes : #25

See : kata-containers/community#5

Signed-off-by: Yash Jain <ydjainopensource@gmail.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hi @ydjainopensource - please could you rebase this PR? That will add the required `.travis.yml` which is now in `master`.

**Comment by ydjainopensource** [comment]
Done!

**Comment by jodh-intel** [comment]
Thanks @ydjainopensource!

lgtm

**Comment by grahamwhaley** [comment]
need an ack from one of @kata-containers/runtime

**Comment by sameo** [comment]
LGTM

**Comment by sameo** [comment]
I guess that one is no longer relevant due to #30 ?

**Comment by jodh-intel** [comment]
Sorry @ydjainopensource, @sameo - I have a script which I used to check which files were missing for #30. But, clearly that script isn't clever enough to also check the PR backlog ;(

**Comment by gnawux** [comment]
Sorry too, didn't notice the two PRs include the same file when I merged #30

**Comment by ydjainopensource** [comment]
No issues I am just closing this PR then

**Pull request closed without merging**
