### PR TITLE
Stable 1.11 backports

### PR DESCRIPTION
**Pull request by jcvenegas**
Changes in this backport

42ec8413 virtiofs: Disable DAX
fd75db90 virtiofsd: Use cache=auto
6239df7f virtcontainers: fix delete sandbox failed problem
ec12ddbb shimv2: handle ctx passed by containerd
7b09e967 sandbox: Disconnect from agent after VM shutdown

### CODE REVIEW

**Comment by jcvenegas** [comment]
@egernst  I have tried to backport #2972 but does not apply directly.

**Comment by jcvenegas** [comment]
removed dax patches, I see merge was having problems, doing as experiment to see if those commits where the problem

**Comment by fidencio** [comment]
@jcvenegas, if possible, I'd like to suggest to have the cgroups fixes Eric worked on backported as well: #2944 and #2988.

**Review by amshinde — APPROVED** [review]

**Review by GabyCT — APPROVED** [review]

**Pull request merged**
