### PR TITLE
# Kata Containers 1.12.0

### PR DESCRIPTION
**Pull request by katabuilder**
- mount fixes for stable-1.12
- 1.12 backports: Bug fixes for 1.12

f03db9f8 static-checks: Correct the copyright format
7df99f30 arm64: correct bridge type for QEMUVIRT machine
a8e9cff3 gitignore: Ignore cli/containerd-shim-kata-v2/config-generated.go
b71211c8 runtime: Ignore ENOENT in kill/delete
ebf5f95e runtime: Add s.newStore.Destroy before defer
44871d29 hypervisor: Remove unused methods
f8e25a4a annotations: Improve asset annotation handling
fb6ca1f9 annotations: Add missing hypervisor control annotation
fa02f1b2 asset: Formatting, grammar and whitespace
77399058 runtime: mount shared mountpoint readonly
509eb6f8 runtime: readonly mounts should be readonly bindmount on the host

### CODE REVIEW

**Comment by fidencio** [comment]
@amshinde, mainly for this one, shouldn't we wait for #3005?

**Comment by fidencio** [comment]
@c3d, can you backport the patches from #3005 to the stable branches?

**Review by jodh-intel — APPROVED** [review]

**Comment by awprice** [comment]
Is https://github.com/kata-containers/runtime/pull/2993 (QEMU 5.1) likely to be included in the 1.12.0 release?

**Pull request merged**
