### PR TITLE
Update cni plugin version

### LINKED ISSUE #2111: Update the version of CNI plugins to make sure CI uses the latest plugins.

### PR DESCRIPTION
**Pull request by amshinde**
Update the version used for testing the cni plugins to the latest
0.8.2 release. This way we make sure CI tests with latest CNI plugins.

Fixes #2111

### CODE REVIEW

**Comment by jodh-intel** [comment]
Builds are still failing due to CNI.

Could you add the git short log to the vendor commit to show what changed too?

**Comment by chavafg** [comment]
@amshinde, you can add a `Depends-on` tag on one of the commits here, so that it can be tested with your change in the tests repo.

**Comment by amshinde** [comment]
Seeing fedora failure:
```
17:19:55 Failed at 171: status=$(get_jaeger_status "$service")
17:19:56 jaeger
17:19:56 jaeger
17:19:57 INFO: Disabling kata tracing on /usr/share/defaults/kata-containers/configuration.toml
17:19:57 make: *** [Makefile:177: tracing] Error 56
17:19:57 Failed at 49: sudo -E PATH="$PATH" bash -c "make test"
17:19:57 Build step 'Execute shell' marked build as failure
17:20:04 Performing Post build task...
```
Rerunning.

**Comment by amshinde** [comment]
@chavafg Can we ack and merge this one and the other PR in the tests repo?

**Comment by chavafg** [comment]
once the CI passes here, will merge them together.
need one more ack here.

**Pull request merged**
