### PR TITLE
vendor: add missing comma to Gopkg.lock

### PR DESCRIPTION
**Pull request by teawater**
$ dep ensure
error while parsing /home/teawater/gopath/src/github.com/kata-containers/runtime/Gopkg.lock: Unable to parse the lock as TOML: (697, 6): missing comma

Fixes: #1241

Signed-off-by: Hui Zhu <teawater@hyper.sh>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Adding a DNM. Looks like something bad happened to the file in the past, and we need to work out what, how and why and ensure we fix it all up correctly.
So, @teawater - thanks for spotting and raising - @sboeuf is looking into the history and trying to unmangle it...

**Comment by sboeuf** [comment]
@teawater thanks for bringing up this issue! I've done a bit of researches and I found @lifupan introduced this bug through the vendoring he did on commit https://github.com/kata-containers/runtime/commit/f1a12ce04c797acfefb7fcba395d96f4034f2d15

@lifupan please be aware that we have some vendoring documentation on how to run a proper vendoring [here](https://github.com/kata-containers/community/blob/master/VENDORING.md). You should never modify the vendoring manually, the only thing you need to do is to modify `Gopkg.toml` to include the new constraints or to update some existing ones.

@teawater please update this PR by actually fixing the vendoring, not simply adding a comma, but running `dep ensure` and pushing all the changes. It should cleanup a few things and generate a new `Gopkg.lock`.

**Comment by teawater** [comment]
@sboeuf done.

**Pull request merged**
