### PR TITLE
CI: add go_import_path

### PR DESCRIPTION
**Pull request by bergwolf**
So that we can test in personal travis setup.

Fixes: #104

Signed-off-by: Peng Tao <bergwolf@gmail.com>

### CODE REVIEW

**Comment by bergwolf** [comment]
Not sure what the pullapprove error actually means...
```
"Signed-off-by" needed on 0 commits
```

**Comment by laijs** [comment]
LGTM

**Comment by jodh-intel** [comment]
Missing a SOB but once that's resolved,

lgtm

**Comment by bergwolf** [comment]
@jodh-intel the commit message actually has SOB line there. Not sure why pullapprove thinks SOB is missing.

**Comment by jodh-intel** [comment]
Oh yes, sorry! Have you maybe changed your primary email address for your github account? If so, that might be a problem if it doesn't match the email address you created the SOB with.

If it isn't that, it sounds like a bug in pullapprove. The Travis log shows that `checkcommits` is happy, and that also checks the SOB.

**Comment by bergwolf** [comment]
@jodh-intel Nop, I am using bergwolf@gmail.com as my primary github email address all the time. Let me try to re-push this PR to see if it retests the SOB line correctly.

**Comment by jodh-intel** [comment]
@bergwolf - ok, if that doesn't help, we can force merge.

**Comment by bergwolf** [comment]
@jodh-intel re-pushed, still failing.

**Comment by jodh-intel** [comment]
@bergwolf - ok. This is a 1-line change to the travis config so cannot possibly affect Jenkins (that's failing due to https://github.com/kata-containers/tests/pull/153 fwics). And travis is failing due to https://github.com/travis-ci/travis-ci/issues/7830, so let's just force-merge...

**Comment by grahamwhaley** [comment]
what I now see on Travis is the 'invalid revision range' I think.
peeked at commit - SOB looks good to me as well.
lgtm

**Pull request merged**
