### PR TITLE
virtcontainers: qemu: Call removeDeviceFromBridge for virtio-blk

### LINKED ISSUE #82: We need to remove a drive from pci bridge in case of virtio-block
See discussion on https://github.com/kata-containers/runtime/pull/72

### PR DESCRIPTION
**Pull request by amshinde**
In case of virtio-block, we hotplug devices to a bridge.
We need to remove device from bridge while stopping a
container.

Fixes #82

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
LGTM

**Comment by jodh-intel** [comment]
lgtm.

You know what I'm going to say though: "tests" :) Can we either have a unit-test or an issue for another type of test to ensure this works as expected?

**Comment by amshinde** [comment]
@jodh-intel See https://github.com/kata-containers/runtime/issues/84

**Comment by amshinde** [comment]
I have created an issue for adding the tests for virtio-block. If we are happy with this, can someone merge this.

**Comment by devimc** [comment]
lgtm

**Pull request merged**
