### PR TITLE
s390x: 2 small test fixes

### PR DESCRIPTION
**Pull request by alicefr**
There are 2 small fixes to make the testsuite running on s390x

### CODE REVIEW

**Comment by alicefr** [comment]
@grahamwhaley you're super fast thx ;)

**Comment by jodh-intel** [comment]
Ubuntu 18.04 CI fell over on:

```
Makefile:91: recipe for target 'kubernetes' failed
```

Restarting all CI's in case this was a transitory issue.

/retest

**Comment by amshinde** [comment]
@jodh-intel There seems to be curl timeout while download packages:

```
Error: Error downloading packages:
03:42:05   Curl error (28): Timeout was reached for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f29&arch=aarch64 [Connection timed out after 30002 milliseconds]
03:42:05 The command '/bin/sh -c dnf -y update && dnf install -y git redhat-release systemd pkgconfig gcc make libseccomp libseccomp-devel' returned a non-zero code: 1
03:42:06 Failed at 116: sudo -E AGENT_INIT="${AGENT_INIT}" AGENT_VERSION="${agent_commit}" GOPATH="$GOPATH" USE_DOCKER=true OS_VERSION=${os_version} ./rootfs-builder/rootfs.sh "${distro}"
```

cc @chavafg

**Comment by jodh-intel** [comment]
@grahamwhaley - here's an aborted build log for you:

- http://jenkins.katacontainers.io/job/kata-containers-runtime-fedora-PR/1679/console

Seems to have aborted due to a network timeout accessing the fedora repos.

**Comment by grahamwhaley** [comment]
Yep, that one definitely looks like a dnf network timeout.

**Comment by jodh-intel** [comment]
Restarted.

**Pull request merged**
