### PR TITLE
DO-NOT-MERGE: Update vendorized govmm for testing

### PR DESCRIPTION
**Pull request by slp**
Update vendorized govmm for testing the refactoring to flexibilize the
use of VirtIO transports:

 - https://github.com/intel/govmm/pull/111

Signed-off-by: Sergio Lopez <slp@redhat.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
@slp - added a `do-not-merge` label, so the CI notices. In the subject line you can have `WIP` or `RFC` for the same effect. See https://github.com/kata-containers/community/wiki/The-WIP-check for some details if interested ;-), but no need - just for future ref.

**Comment by alicefr** [comment]
@slp you're missing the `Fixes` tag in the commit. Have a look to https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format

**Comment by slp** [comment]
@grahamwhaley Thanks and sorry for the inconvenience!

@alicefr I though it wasn't needed, as it was just for testing, but I've just created an issue and referenced it in the commit.

**Comment by alicefr** [comment]
thanks! No the CI is checking it before running the real tests :)

**Comment by grahamwhaley** [comment]
Thanks for adding the Issue @slp . If a PR is just for testing, you can always use a dummy `Fixes`, like `Fixes: #0` etc. :-)  But, yes, the CI does the static checks first. iirc, you can [set a label to force the CI to run](https://github.com/kata-containers/tests/blob/master/.ci/ci-fast-return.sh#L41-L42), but it's easier to just add a `Fixes` most the time ;-)

**Comment by jodh-intel** [comment]
If/when this PR becomes a normal one, please can you add the commits being introduced as documented here:

- https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#re-vendor-prs

**Comment by devimc** [comment]
hotplug block devices test failed 

```
docker: Error response from daemon: OCI runtime create failed: QMP command failed: Property '.devno' not found: unknown.
```

**Comment by slp** [comment]
> hotplug block devices test failed
> 
> ```
> docker: Error response from daemon: OCI runtime create failed: QMP command failed: Property '.devno' not found: unknown.
> ```

@devimc I was confused by this error, but luckily managed to get a s390x test machine to give this a try.

So what's happening is that, in s390x, the default `block_device_driver` is `virtio-scsi`, which means it's using `ExecuteSCSIDeviceAdd` instead of `ExecuteDeviceAdd`. The weird thing is that `ExecuteSCSIDeviceAdd` may add `devno`, `romfile` and `disable-modern`, while what was being added is not a virtio device, but an SCSI device to an already existing virtio-scsi controller.

This was working before because, as `scsi-hd` wasn't present in neither the isVirtioCCW nor the isVirtioPCI map, the check always returned false.

I'm going to update the PR in govmm to fix `ExecuteSCSIDeviceAdd` so it doesn't add those properties in any case.

**Comment by slp** [comment]
I've updated the PR with the commit in govmm that should fix the issues with hotplug.

BTW, I think it'd be nice enabling the CI tests for x86_64 too.

**Comment by devimc** [comment]
thanks @slp 
/test-s390x
/test-ubuntu

**Comment by devimc** [comment]
seems like CI failed again 

```
msg="Request to hypervisor to update vCPUs" 
msg="{\"execute\":\"query-hotpluggable-cpus\"}" 
msg="{\"return\": [{\"props\": {\"core-id\": 0, \"thread-id\": 0, \"node-id\": 0, \"die-id\": 0, \"socket-id\": 3}, \"vcpus-count\": 1, \"type\": \"host-x86_64-cpu\"}, {\"props\": {\"core-id\": 0, \"thread-id\": 0, \"node-id\": 0, \"die-id\": 0, \"socket-id\": 2}, \"vcpus-count\": 1, \"type\": \"host-x86_64-cpu\"}, {\"props\": {\"core-id\": 0, \"thread-id\": 0, \"node-id\": 0, \"die-id\": 0, \"socket-id\": 1}, \"vcpus-count\": 1, \"type\": \"host-x86_64-cpu\"}, {\"props\": {\"core-id\": 0, \"thread-id\": 0, \"node-id\": 0, \"die-id\": 0, \"socket-id\": 0}, \"vcpus-count\": 1, \"qom-path\": \"/machine/unattached/device[0]\", \"type\": \"host-x86_64-cpu\"}]}"
msg="{\"arguments\":{\"core-id\":\"0\",\"die-id\":\"0\",\"driver\":\"host-x86_64-cpu\",\"id\":\"cpu-0\",\"romfile\":\"\",\"socket-id\":\"3\",\"thread-id\":\"0\"},\"execute\":\"device_add\"}"
msg="{\"error\": {\"class\": \"GenericError\", \"desc\": \"Property '.romfile' not found\"}}" 
msg="{\"arguments\":{\"core-id\":\"0\",\"die-id\":\"0\",\"driver\":\"host-x86_64-cpu\",\"id\":\"cpu-0\",\"romfile\":\"\",\"socket-id\":\"2\",\"thread-id\":\"0\"},\"execute\":\"device_add\"}"
msg="{\"error\": {\"class\": \"GenericError\", \"desc\": \"Property '.romfile' not found\"}}"
msg="{\"arguments\":{\"core-id\":\"0\",\"die-id\":\"0\",\"driver\":\"host-x86_64-cpu\",\"id\":\"cpu-0\",\"romfile\":\"\",\"socket-id\":\"1\",\"thread-id\":\"0\"},\"execute\":\"device_add\"}"
msg="{\"error\": {\"class\": \"GenericError\", \"desc\": \"Property '.romfile' not found\"}}"
```

**Comment by slp** [comment]
@devimc Hm... `ExecuteCPUDeviceAdd` may also add a `romfile` property to the request. Weird.

I removed that conditional from it, and I also reviewed the rest of Execute* calls looking for this kind of conditional properties. I think we should be pretty close to passing CI tests.

**Comment by slp** [comment]
Hi, could you please enable the CI tests to give the last update a try? Thanks!

**Comment by slp** [comment]
I see the virtiofs and firecracker CI variants failed. Is that expected?

On the other hand, could you please enable testing on s390x?

**Comment by grahamwhaley** [comment]
I think there is some fc CI instability right now - see #2383 for instance (/cc @WeiZhang555 )
iirc, the s390 CI hardware was going through a re-install/ri-jig over the seasonal period as well - /cc @alicefr for input on that.

**Comment by alicefr** [comment]
@grahamwhaley we're setup the new VM. @jschintag. I'll let run the test when it's up. Thx!

**Comment by slp** [comment]
So it looks like something is broken in the s390x CI:

```
15:04:35 ~/workspace/kata-containers-runtime-s390x-18.04-PR/go/src/github.com/kata-containers/runtime
15:04:35 .ci/static-checks.sh: line 13: make: command not found
15:04:35 Build step 'Execute shell' marked build as failure
```

**Comment by jschintag** [comment]
@slp Ah yeah that, the s390x CI is currently migration to a new VM, so i was just testing if it works. Turned out there was something not quite right with the VM configuration. I'll need to wait until they fix it before we can try this PR again.

**Comment by slp** [comment]
@jschintag Ah, okay, thanks for the info.

**Comment by slp** [comment]
Has there been any progress regarding the s390x CI issues?

**Comment by alicefr** [comment]
@slp there are still issues. I'm going to test your PR locally. Kata runtime is currently broken on s390x without https://github.com/kata-containers/runtime/pull/2385

**Comment by alicefr** [comment]
@slp we've some issues on s390x test right now. They're not due to your PR. So, for me it looks good!

**Comment by slp** [comment]
@alicefr Great! Thanks for testing it out!

**Comment by bergwolf** [comment]
I'm afraid that the PR cannot be merged as is.

The vendored govmm PR(https://github.com/intel/govmm/pull/111) does not preserve API compatibility as expected. To be specific, it dropped the `-pci` suffix of many vhost user devices and it would cause kata runtime to append a wrong device type and govmm unfortunately silently ignores such error and the error only pops out later in container operations.

I've addressed the issue in #2477 and this PR can be dropped when #2477 is merged.

**Comment by slp** [comment]
@bergwolf Sure, no problem, this PR was just to test the govmm changes, is not intended to be merged as is.

**Comment by raravena80** [comment]
@slp nudge. Any updates? Should we close this PR?

**Comment by slp** [comment]
@raravena80 Yeah, I'm closing it.

**Pull request closed without merging**
