### PR TITLE
Fix parallel make

### PR DESCRIPTION
**Pull request by stefanha**

### CODE REVIEW

**Comment by egernst** [comment]
I see a bunch of failures around making the CLI.  Example:

```
INFO: Running 'go test' as current user on package 'github.com/kata-containers/runtime/cli' with flags '-v -race -timeout 30s -outputdir "/tmp/tmp.g6vtVNOdOF"'
# github.com/kata-containers/runtime/cli [github.com/kata-containers/runtime/cli.test]
cli/delete.go:30: undefined: name
cli/delete.go:32: undefined: name
cli/delete.go:34: undefined: name
cli/exec.go:49: undefined: name
cli/kata-check.go:49: const initializer "System is capable of running " + project is not a constant
cli/kata-check.go:49: undefined: project
cli/kata-check.go:50: const initializer "System can currently create " + project is not a constant
cli/kata-check.go:50: undefined: project
cli/kata-check.go:51: const initializer "System is not capable of running " + project is not a constant
cli/kata-check.go:51: undefined: project
cli/exec.go:49: too many errors
FAIL	github.com/kata-containers/runtime/cli [build failed]
Makefile:534: recipe for target 'go-test' failed
```

**Comment by jodh-intel** [comment]
That looks like the tests are being run without first building (to generate `cli/config-generated.go`).

**Comment by stefanha** [comment]
go-test has a dependency on GENERATED_FILES but not GENERATED_CONFIG.  This means generated-config.go is deleted and not regenerated.

I'll have to rethink the solution.

**Comment by stefanha** [comment]
I started from scratch.  Using 'clean' to force a rebuild is a hack.  It's necessary because the makefile uses several values which may change but they are not files, so make has no way of detecting changes.

The new patches that I posted adds file dependencies so changes are detected by make.  It then becomes possible to drop the force rebuild since make will do it's job properly.  And finally, parallel make works correctly.

**Comment by stefanha** [comment]
@grahamwhaley jenkins-ci-ARM-ubuntu-18-04, jenkins-ci-ubuntu-18-04-initrd, and jenkins-ci-ubuntu-nemu failed.  It is not clear to me that these failures were caused by this pull request.  Any ideas?

**Pull request merged**
