### PR TITLE
docs: update debug runtime link

### PR DESCRIPTION
**Pull request by egernst**
It pointed to how to enable logs, which is only a small portion of the
debug options for Kata  Containers.  Let's instead point to the
troubleshooting section, which includes pointers to adding logs and to
debug the guest vm.

Signed-off-by: Eric Ernst <eric.ernst@intel.com>

### CODE REVIEW

**Comment by gnawux** [comment]
LGTM

**Comment by WeiZhang555** [comment]
LGTM.
Waiting for Jenkins. (I believe it can pass :-) )

**Comment by WeiZhang555** [comment]
All green, merging now 😄

**Pull request merged**
