### PR TITLE
Firecracker: update to version v0.15.2

### PR DESCRIPTION
**Pull request by egernst**
Fixes: #1559

Signed-off-by: Eric Ernst <eric.ernst@intel.com>

### CODE REVIEW

**Comment by egernst** [comment]
note: I cancelled all jobs minus required and Firecracker, since they aren't relevant to this change!

**Comment by egernst** [comment]
@mcastelino @amshinde FYI: Here's the failure:

```
command failed error 'exit status 125'
[docker run --cidfile /tmp/cid741702381/8awsv251R7WvWyRl8yE0Ig1GYalLr1 --runtime kata-runtime -td --name 8awsv251R7WvWyRl8yE0Ig1GYalLr1 busybox sh]
Timeout: 120 seconds
Exit Code: 125
Stdout: abe8715e0fefd32007ef229808243b297b526187b71005b728c414d2b435cba0

Stderr: docker: Error response from daemon: OCI runtime create failed: [PATCH /drives/{drive_id}][400] patchGuestDriveByIdBadRequest  &{FaultMessage:API Resource IDs can only contain alphanumeric characters and underscores.}: unknown.
```

**Comment by grahamwhaley** [comment]
@egernst - see https://github.com/kata-containers/runtime/pull/1265 for previous/pending PR of similar, with thread, and @mcastelino noting there may be work to do to make this applicable.

**Comment by teawater** [comment]
Current runtime cannot work OK with fc 0.15.2.
Maybe you can update firecracker-go-sdk to handle the issue.

**Comment by teawater** [comment]
I dnm this PR because fc 1.5.2 cannot work OK with kata runtime now.

**Comment by teawater** [comment]
jenkins-ci-ARM-ubuntu-18-04 fail:
```
09:23:27 INFO: Clone config and patches
09:23:27 lrwxrwxrwx 1 root root 18 May  4 09:23 /usr/share/kata-containers/vmlinux.container -> vmlinux-4.19.28-36
09:23:27 lrwxrwxrwx 1 root root 18 May  4 09:23 /usr/share/kata-containers/vmlinuz.container -> vmlinuz-4.19.28-36
09:23:28 Install Qemu
09:28:36 package github.com/qemu/qemu: no Go files in /home/jenkins/workspace/kata-containers-runtime-ARM-18.04-PR/go/src/github.com/qemu/qemu
09:28:36 can't load package: package github.com/kata-containers/packaging: no Go files in /home/jenkins/workspace/kata-containers-runtime-ARM-18.04-PR/go/src/github.com/kata-containers/packaging
09:28:36 ~/workspace/kata-containers-runtime-ARM-18.04-PR/go/src/github.com/qemu/qemu ~/workspace/kata-containers-runtime-ARM-18.04-PR/go/src/github.com/kata-containers/tests
09:28:41 Already on 'master'
09:28:41 Your branch is up to date with 'origin/master'.
09:28:41 error: The following untracked working tree files would be overwritten by checkout:
09:28:41 	slirp/COPYRIGHT
09:28:41 Please move or remove them before you switch branches.
09:28:41 Aborting
09:28:42 Build step 'Execute shell' marked build as failure
09:28:42 Performing Post build task...
09:28:42 Match found for :.* : True
09:28:42 Logical operation result is TRUE
09:28:42 Running script  : #!/bin/bash
09:28:42 
09:28:42 export GOPATH=$WORKSPACE/go
09:28:42 export GOROOT="/usr/local/go"
```
This PR is around firecracker but this fail doesn't have relation with firecracker.

jenkins-ci-centos-7-4-q-35 fail:
```
--- FAIL: TestHostNetworkingRequested (0.01s)
    assertions.go:239: 
                          
	Error Trace:	network_test.go:98
        
	Error:      	Should be true
```
This is a known issue https://github.com/kata-containers/runtime/issues/1604 .

**Pull request merged**
