### PR TITLE
vc: Restore sandbox state when there is error starting containers

### LINKED ISSUE #2237: Set sandbox state after starting containers
# Description of problem

Currently in Sandbox#Start:
```
	if err := s.setSandboxState(types.StateRunning); err != nil {
		return err
	}

	for _, c := range s.containers {
		if err := c.start(); err != nil {
			return err
```
If some container fails to start (e.g. the first container), sandbox state is set to running but there is no container.

# Expected result

We should set sandbox state to running after starting containers.

# Actual result

### PR DESCRIPTION
**Pull request by tedyu**
Fixes #2237

Signed-off-by: Ted Yu <yuzhihong@gmail.com>

### CODE REVIEW

**Comment by tedyu** [comment]
```
17:46:31 ERROR: Found unexpected /usr/libexec/kata-containers/kata-proxy present
17:46:32 30498
17:46:32 ERROR: Found unexpected /usr/libexec/kata-containers/kata-proxy present
```
Not related to my PR.

@lifupan 
Can you retrigger jenkins-metrics-ubuntu-16-04 test ?

thanks

**Comment by tedyu** [comment]
@grahamwhaley @jodh-intel 
Please review

**Comment by tedyu** [comment]
@lifupan 
Can you retrigger jenkins-ci-opensuse-15 test ?

Thanks

**Comment by grahamwhaley** [comment]
@tedyu - thought I should explain to you what that CI test fail is saying.... from the console logs:

```
bash sanity/check_sanity.sh
9b2373ad817eeb88d69666a02df2cba52ce5229159821b39591d6649fce815f1
ERROR: 1 pods left and found at /var/lib/vc/sbs
make: *** [Makefile:97: docker] Error 1
```

What the `check_sanity.sh` test does is ensure that after we've run tests, that the 'workspace' left by Kata is clean - that we have not left any processes or dirty files laying around on the system. In this case it found a file left in the `sbs` (sandbox?) directory that it did not expect to be there.

Letting you know just in case you need to debug - and your PRs are tinkering around that area of virtcontainers I think :-)

**Comment by tedyu** [comment]
@devimc 
Can you re-trigger opensuse test run ?

thanks

**Comment by tedyu** [comment]
@grahamwhaley 
Can you re-trigger opensuse test run (to see if it was flaky) ?

thanks

**Comment by grahamwhaley** [comment]
ah, thought I had .... done now....

**Comment by tedyu** [comment]
@grahamwhaley @devimc 
All tests passed.

**Pull request merged**
