### PR TITLE
vc: Sandbox#getAndSetSandboxBlockIndex shouldn't alter BlockIndex in case of error

### LINKED ISSUE #2244: Sandbox#getAndSetSandboxBlockIndex shouldn't alter BlockIndex in case of error
# Description of problem

Currently Sandbox#getAndSetSandboxBlockIndex increments BlockIndex up front.
Later on if store.Store() returns error, the index increment is left behind.

# Expected result

BlockIndex should not increment in case of error.

Similar issue applies to decrementSandboxBlockIndex where the symptom may be more severe - in worst case, the block index may become negative.

# Actual result

### PR DESCRIPTION
**Pull request by tedyu**
Fixes #2244

Signed-off-by: Ted Yu <yuzhihong@gmail.com>

### CODE REVIEW

**Comment by egernst** [comment]
Can you make a shorter commit header, and add a message body?

Changes seems fine to me, but I’m going to let @lifupan weigh in.

**Comment by tedyu** [comment]
@egernst 
I have added message body.

Can you trigger ubuntu test ?

Thanks

**Comment by tedyu** [comment]
@lifupan 
Can you take a look ?

**Comment by tedyu** [comment]
@grahamwhaley 
Can you trigger ubuntu test ?

Thanks

**Comment by tedyu** [comment]
@lifupan @jodh-intel @devimc 
Can you approve this ?

Thanks

**Comment by GabyCT** [comment]
lgtm, please @tedyu address @jodh-intel comments

**Comment by jodh-intel** [comment]
@bergwolf - ok, let's do that. I've raised https://github.com/kata-containers/runtime/issues/2263 if anyone wants to have a go? :wink:

**Comment by tedyu** [comment]
@jodh-intel 
can you merge this ?

**Comment by egernst** [comment]
@tedyu can you send same PR to stable-1.9 and stable-1.8 branches?

**Comment by grahamwhaley** [comment]
@tedyu - fyi, there is a 'how to' workflow document on stable backports for kata at https://github.com/kata-containers/community/blob/master/Backport-Guide.md

**Pull request merged**
