### PR TITLE
cli: add no-pivot flag to be compatible with docker in ramdisk

### LINKED ISSUE #409: OCI runtime create failed: flag provided but not defined: -no-pivot: unknown.
# Description of problem

1. set the env variable 'DOCKER_RAMDISK=true' before launching dockerd. (In my environment, docker need to disable ‘pivot_root’)
2. docker run --runtime kata-runtime --rm  busybox echo 'hello'

# Expected result

hello

# Actual result

docker: Error response from daemon: OCI runtime create failed: flag provided but not defined: -no-pivot: unknown.

# P.S.

Can kata-runtime add this flag to made it is compatible with this special environment, so i can choose the runtime by `docker run --runtime xx`.  (kata-runtime can throw a warning, and ignore the flag)

### PR DESCRIPTION
**Pull request by wwq19920405**
This commit add a no-pivot flag (just a warning tip) in kata-runtime create and run cmd.

Fixes: #409 , #134

Signed-off-by:  wenqi wang <wangwenqi01@baidu.com>

### CODE REVIEW

**Comment by WeiZhang555** [comment]
Good PR!  CI is failing because of issue below:
```
ERROR: Commit 10e862c30fe1705dec6ac97d46630bb31227d9d5: Failed to find subsystem in subject: "add no-pivot flag  to be compatible with docker in ramdisk"
```

That means you need to modify the commit message title to:
"cli: add no-pivot flag  to be compatible with docker in ramdisk"

And the message body should contain detailed description, so the full commit message should looks like:
```
cli: add no-pivot flag  to be compatible with docker in ramdisk

Fixes: #409 , #134

This commit add a no-pivot flag (just a warning tip) in kata-runtime create and run cmd.
```

**Comment by jodh-intel** [comment]
Thanks for raising @wwq19920405!

Once this lands and the feature works, we need to do two further things:

- Write a test to ensure the feature continues to work:

  https://github.com/kata-containers/tests/issues/429

- Update the limitations document:

  https://github.com/kata-containers/documentation/issues/170

If you'd like to work on either of those issues, just add a comment on the issue, otherwise the team will look at them when they can...

**Comment by wwq19920405** [comment]
I meet a new problem:
docker run --runtime kata-runtime --rm busybox echo 'hello'
docker: Error response from daemon: OCI runtime create failed: rpc error: code = InvalidArgument desc = Unknown storage driver "ephemeral": unknown.

**Comment by grahamwhaley** [comment]
I think I hit the 'no ephemeral' issue last week - have a look at #394  The problem for me was my agent in my image was too old - I had to add a newly built agent to my osbuilder image.

**Comment by jodh-intel** [comment]
That's right. If you build a rootfs using osbuilder, it will pull in the latest agent to resolve this issue:

- https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#create-a-rootfs-image

**Comment by wwq19920405** [comment]
I didn't build a rootfs using osbuilder, just replace the kata-runtime and  rum `docker run` cmd.
And i update all components, the problem isn't solved.

**Comment by jodh-intel** [comment]
Hi @wwq19920405 - what we mean is that the runtime code recently added support for ephemeral volumes.  Since you have built a newer version of the runtime (which includes that ephemeral support and which requires the agent to understand ephemeral volumes) you **will** need to to create a new rootfs image to overcome that error.

**Comment by jodh-intel** [comment]
By the way, what are 5.31 and 6.19? I'm assuming they are dates? :smile:

If so, it would be much clearer to specify them in ISO 8601 format so it is clear to all (2018-05-31 and 2018-06-19)

**Comment by wwq19920405** [comment]
They are dates, and maybe using commit id to to represent the code versions is clearer.

> Since you have built a newer version of the runtime (which includes that ephemeral support and which requires the agent to understand ephemeral volumes) you will need to to create a new rootfs image to overcome that error.

I will try it, thx.

**Comment by sboeuf** [comment]
@wwq19920405 please sign your commit and include the `Fixes #...` into the commit message.

**Comment by jodh-intel** [comment]
Yep - if you look at the Travis log, you'll see what the problem is and the log will point you to:

- https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format

**Comment by wwq19920405** [comment]
so sorry, i delete my repository. (This my first time to submit PR on GitHub, and  it is not standard enough.)

I raise a new PR #423 .

**Pull request closed without merging**
