### PR TITLE
clh: backport: Move to v0.7.0

### PR DESCRIPTION
**Pull request by jcvenegas**
Changes:
2d251652 clh: vsock: Supply the right VsockConfig to Vmconfig
fcc9e93b versions: Move to cloud-hypervisor v0.7.0
34be9e0c clh: memory: remove pmem size argument
9798e8a5 versions: Move to latest cloud-hypervisor

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hi @jcvenegas - fwics, this is related to https://github.com/kata-containers/runtime/pull/2659. I can see this is a "nice to have" change, but is it actually necessary to backport it?

**Comment by jcvenegas** [comment]
@jodh-intel this is a very few changes and the stable branch gets the bennefit that if there are some fixes in cloud-hypervisor we only need to bump to 0.7.1

**Comment by grahamwhaley** [comment]
> I am always wondering is increasing code coverage required for each PR? I assume No, as we can't guarantee that for every changes, right?

Code Coverage does not have to *increase* for every change - but, ideally, it will not **decrease** for any change :-)  Which implies, if you add code, you may have to add tests to maintain the % coverage...

**Comment by likebreath** [comment]
> > I am always wondering is increasing code coverage required for each PR? I assume No, as we can't guarantee that for every changes, right?
> 
> Code Coverage does not have to _increase_ for every change - but, ideally, it will not **decrease** for any change :-) Which implies, if you add code, you may have to add tests to maintain the % coverage...

Right. That makes sense. Thanks, @grahamwhaley.

**Pull request merged**
