### PR TITLE
runv: modify GOPATH to build

### PR DESCRIPTION
**Pull request by bergwolf**
So that we can use runv repo as git submodule without splitting it.

### CODE REVIEW

**Comment by sameo** [comment]
LGTM

**Comment by sameo** [comment]
@jodh-intel Could you please review?

**Comment by jodh-intel** [comment]
This doesn't work for me:

```
$ make KATA_RUNTIME=runv 
(cd runv/gopath/src/github.com/hyperhq/runv/ && [ -e configure ] || ./autogen.sh && ./configure && GOPATH=/home/james/go/src/github.com/kata-containers/runtimes/runv/gopath make)
/bin/sh: ./autogen.sh: No such file or directory
make: *** [Makefile:50: build] Error 127
```

**Comment by WeiZhang555** [comment]
How about making a temp dir under runtime root dir and using a soft link? a quick example:

```
diff --git a/Makefile b/Makefile
index bcf2dcf..b68a40d 100644
--- a/Makefile
+++ b/Makefile
@@ -37,6 +37,7 @@ endif
 ifeq (runv,$(KATA_RUNTIME))
        RUNTIME_DIR = runv
        RUNTIME_NAME = runv
+       BUILD_ROOT = $(PWD)/build-runv
        DESTTARGET = $(DESTBINDIR)/$(RUNTIME_NAME)
 endif
 
@@ -47,7 +48,8 @@ ifeq (cc,$(KATA_RUNTIME))
        make -C $(RUNTIME_DIR) build-kata-system TARGET=$(TARGET) DESTTARGET=$(DESTTARGET)
 endif
 ifeq (runv,$(KATA_RUNTIME))
-       (cd $(RUNTIME_DIR) && [ -e configure ] || ./autogen.sh && ./configure && make)
+       mkdir -p $(BUILD_ROOT)/src/github.com/hyperhq && ln -sf $(PWD)/$(RUNTIME_DIR) $(BUILD_ROOT)/src/github.com/hyperhq/runv
+       (cd $(BUILD_ROOT)/src/github.com/hyperhq/runv && [ -e configure ] || ./autogen.sh && ./configure && make GOPATH=$(BUILD_ROOT))
 endif

```

It needs a little bit more modifications to make it work, only for showing my ideas.

**Comment by bergwolf** [comment]
@jodh-intel did you sync submodule after pulling the pr locally? What is the output of `ls runv/gopath/src/github.com/hyperhq/runv/`?

**Comment by bergwolf** [comment]
@WeiZhang555 thanks for the suggestion. PR updated.

**Comment by laijs** [comment]
LGTM

**Comment by jodh-intel** [comment]
Hi @bergwolf - sorry, yes, my repo was stale.

lgtm.

**Pull request merged**
