### PR TITLE
# Kata Containers 1.5.1

### PR DESCRIPTION
**Pull request by katacontainersbot**
- versions: Update kernel to 4.14.102

d647fba versions: Update kernel to 4.14.102

### CODE REVIEW

**Comment by egernst** [comment]
change is fine, but can we pull this in first? https://github.com/kata-containers/runtime/pull/1294

**Comment by jodh-intel** [comment]
Travis fell over on the URL checker:

```
INFO: Checking all document URLs
ERROR: Invalid URL 'http://jenkins.katacontainers.io/job/kata-containers-runtime-ubuntu-16-04-master/' found in the following files:
README.md
ERROR: Invalid URL 'http://jenkins.katacontainers.io/job/kata-containers-runtime-ubuntu-16-04-master/badge/icon' found in the following files:
README.md
```

Didn't @grahamwhaley mention this job disappearing yesterday?

**Comment by grahamwhaley** [comment]
I believe, mostly the 16.04 jobs have migrated (been renamed/config'd) into the 18.04 jobs... (the x86 QA CI ones anyway). which CI failed here @jodh-intel - was it travis per chance, which should not be affected, and sounds like a real fail maybe.

**Comment by jodh-intel** [comment]
Yep - travis only.

/cc @chavafg, @GabyCT.

**Comment by grahamwhaley** [comment]
Heh, so, I think it is complaining about the 'jenkins badge URL' at the top of the README file, as we've removed the job it points at... good catch :-)
```
[![Build Status](http://jenkins.katacontainers.io/job/kata-containers-runtime-ubuntu-16-04-master/badge/icon)](http://jenkins.katacontainers.io/job/kata-containers-runtime-ubuntu-16-04-master/)
```

yep, probably need a PR to update that (whoever nuked the job I say ;-) )

**Comment by jodh-intel** [comment]
Our CI rocks! :guitar: :drum: :musical_keyboard: :smile:

**Pull request merged**
