### PR TITLE
docs: Add missing standard docs

### LINKED ISSUE #29: Add missing standard docs
This repo needs:

- a README doc
- a code of conduct doc
- a contributing doc

### PR DESCRIPTION
**Pull request by jodh-intel**
Add a README, along with the standard code of conduct and contributing
docs.

Fixes #29.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by gnawux** [comment]
lgtm

**Comment by gnawux** [comment]
one more approve is required. And the travis failed, looks should not include submodule changes, right? @jodh-intel

**Comment by sameo** [comment]
@jodh-intel Why are we modifying the runtime submodules?

**Comment by jodh-intel** [comment]
@sameo - to pull in the latest changes from our runtime. I thought we had tentatively considered doing this after each release?

**Comment by sameo** [comment]
@jodh-intel Fine with me, but this should be a separate PR.

**Comment by sameo** [comment]
@jodh-intel And we should let the Hyper team decide when to update the runv code, obviously.

**Comment by jodh-intel** [comment]
@sameo - oooh sorry, I must have done a `commit -as` on this PR. Let me re-push in a sec...

**Comment by sameo** [comment]
LGTM

**Pull request merged**
