### PR TITLE
versions: move to go 1.10

### PR DESCRIPTION
**Pull request by jcvenegas**
- move to golang  1.10
- Fix issues needed move to go 1.10

### CODE REVIEW

**Comment by jcvenegas** [comment]
Hit two random issues:
https://github.com/kata-containers/tests/issues/264
and one not documented yet:

not ok 20 ctr execsync std{out,err}
# (in test file ctr.bats, line 759)
#   `[ "$status" -eq 0 ]' failed

**Comment by jcvenegas** [comment]
restating all jobs.

**Comment by jcvenegas** [comment]
@sboeuf @jodh-intel @devimc @bergwolf ready to merge all jobs passing with go 1.10

Tested in agent, proxy and shim CI as well. All looks ok.

**Comment by jodh-intel** [comment]
Thanks @jcvenegas!

lgtm

For reference, the go 1.10 PRs for the other components:

- https://github.com/kata-containers/agent/pull/223
- https://github.com/kata-containers/proxy/pull/68
- https://github.com/kata-containers/shim/pull/77

**Pull request merged**
