### PR TITLE
vc: Persist file handle may leak in FS#ToDisk

### LINKED ISSUE #2241: Persist file handle may leak in FS#ToDisk
# Description of problem

In FS#ToDisk, we have the following code:
```
		cf, err := os.OpenFile(cfile, os.O_RDWR|os.O_CREATE|os.O_TRUNC, fileMode)
...
		if err := json.NewEncoder(cf).Encode(cstate); err != nil {
			return err
		}
		cf.Close()
```
If there is error in encoding, the cf would be left behind unclosed.

# Expected result

cf should be closed regardless of encoding outcome.

# Actual result

### PR DESCRIPTION
**Pull request by tedyu**
Fixes #2241

Signed-off-by: Ted Yu <yuzhihong@gmail.com>

### CODE REVIEW

**Comment by tedyu** [comment]
This was not found via any tool.

**Comment by tedyu** [comment]
@devimc @egernst 
All tests passed.

**Comment by amshinde** [comment]
Needs backport to stable branch.

**Pull request merged**
