### PR TITLE
[DNM][WIP] virtcontainers: fix wrong number of vcpus after killing a container

### LINKED ISSUE #2186: k8s: wrong number of cpus after killing a container
# Description of problem

the number of vpus increases after killing a container with cpus constrains, **if the container is killed 99 times, the same number of vpus are hot plugged !!**

**pod-cpu.yaml**
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: cpu-test
spec:
  runtimeClassName: kata
  containers:
  - name: c1
    image: busybox
    command:
      - sh
    resources:
      limits:
        cpu: "1"
    tty: true
  - name: c2
    image: busybox
    command:
      - sh
    resources:
      limits:
        cpu: "1"
    tty: true
```

```
$ kubectl apply -f pod-cpu.yaml
$ kubectl get pods
NAME       READY   STATUS    RESTARTS   AGE
cpu-test   2/2     Running   0          67s
$ kubectl exec -ti pod/cpu-test -c c1 nproc
3
# the number of vcpus is correct: 1 (c1) + 1 (c2) + 1 (default_vcpus) = 3

# Attach to c2 and kill it
$ kubectl attach -ti pod/cpu-test -c c2
If you don't see a command prompt, try pressing enter.
/ # exit

# wait for c2, it's restarted
$ kubectl get pods
NAME       READY   STATUS    RESTARTS   AGE
cpu-test   2/2     Running   0          67s

# check again the number of vcpus
$ kubectl exec -ti pod/cpu-test -c c1 nproc
4
# Now the number of vcpus is 4, the number of vpus increases after every restart of c2
```

# Expected result

below command should always return 3

```
$ kubectl exec -ti pod/cpu-test -c c1 nproc
3
```

# Actual result

```
$ kubectl exec -ti pod/cpu-test -c c1 nproc
4
# kill c2
$ kubectl exec -ti pod/cpu-test -c c1 nproc
5
# kill c2 again
$ kubectl exec -ti pod/cpu-test -c c1 nproc
6
# kill c2 again
$ kubectl exec -ti pod/cpu-test -c c1 nproc
7
```

might be this issue was introduced here https://github.com/kata-containers/runtime/pull/1998 ?

cc @lifupan @egernst @jcvenegas

### PR DESCRIPTION
**Pull request by devimc**
fixme: split commit

fixes #2186

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by devimc** [comment]
@jodh-intel @chavafg  @grahamwhaley  @egernst @gnawux @WeiZhang555 @kata-containers/architecture-committee this pr can break backward compatibility in kata, this means containers started with kata <= 1.9 may not be stopped with kata > 1.9 (master, 1.10), are we considering backward compatibility?  I think there is no test for that

**Comment by chavafg** [comment]
currently we do not have a test for that, but we should have one if we will actually support backward compatibility.

**Comment by devimc** [comment]
folks, I'm going to split this and raise new PRs, but I still would like to know if we support backward compatibility

**Pull request closed without merging**
