### PR TITLE
cc-runtime: Update to 3.0.20

### LINKED ISSUE #42: Update cc-runtime to 3.0.20
Update `cc-runtime` to release 3.0.20.

### PR DESCRIPTION
**Pull request by jodh-intel**
Update `cc-runtime` to release 3.0.20 to pull in SCSI support and vCPU and
logging fixes.

Shortlog:

    0ea75e1 versions: Update kernel version to latest.
    14439ef release: Clear Containers 3.0.20
    e703f15 fedora-installation-guide: update Fedora versions supported
    b03c4a5 logging: Add name to all log calls
    055c688 logging: Add PID field to logs
    f6da537 config: don't exceed the number of physical cores
    cc84544 versions: Update agent version to pull in SCSI support
    54f87f5 logging: Add CLI command to logs
    befbdb1 config: Add comments for the DisableBlockDeviceUse flag

Fixes #42.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Hi @gnawux, @bergwolf, @WeiZhang555 - could you take a look please?

**Comment by sboeuf** [comment]
LGTM

**Comment by jodh-intel** [comment]
wdyt @sboeuf?

**Comment by sboeuf** [comment]
@grahamwhaley @jodh-intel SCSI is only mentioned for the versions.txt file which refers to the clear containers agent, so nothing to worry about here.

**Comment by grahamwhaley** [comment]
ta, merging then...

**Pull request merged**
