### PR TITLE
shimv2: use the runtime config file passed from containerd/cri

### PR DESCRIPTION
**Pull request by lifupan**
containerd/cri's different runtime handlers can pass different
config files to shimv2 by a generic runtime options, by this kata
can launch the pods using different VMM for different runtime handlers.

Fixes:#1082

Signed-off-by: Fupan Li <lifupan@gmail.com>

### CODE REVIEW

**Comment by gnawux** [comment]
env var and the protobuf field, which should have higher privilege?

**Comment by lifupan** [comment]
> env var and the protobuf field, which should have higher privilege?

protobuf > env var > /etc dir > /usr/share/defualt dif

**Comment by gnawux** [comment]
I have another question with protobuf. if work with old version of containerd, will shimv2 panic due to the lack of a field?

**Comment by lifupan** [comment]
> I have another question with protobuf. if work with old version of containerd, will shimv2 panic due to the lack of a field?

No, it will check the pointer first as below:
		if r.Options != nil {

For the old version containerd, here the r.Options will be nil.

**Comment by lifupan** [comment]
@grahamwhaley Is there any thing wrong with CI, the tests have been launched a day ago, but none of them has been scheduled?

**Comment by gnawux** [comment]
/retest
try again

**Comment by grahamwhaley** [comment]
hi @lifupan - yep, there was a problem yesterday when a disk filled up and things got stalled/backed up in the queu. I think some jobs then got dropped..... looks like the above action has kicked it into action again ...

**Pull request merged**
