### PR TITLE
vc: Drop Sandbox#Pause and Sandbox#Resume

### LINKED ISSUE #2276: Drop Sandbox#Pause and Sandbox#Resume
**Which feature do you think can be improved?**

See https://github.com/kata-containers/runtime/pull/2248#issuecomment-558146963

**How can it be improved?**
Drop Sandbox#Pause and Sandbox#Resume

**Additional Information**

### PR DESCRIPTION
**Pull request by tedyu**
Fixes #2276

Signed-off-by: Ted Yu <yuzhihong@gmail.com>

### CODE REVIEW

**Comment by tedyu** [comment]
@jodh-intel 
I have updated the PR.

**Comment by tedyu** [comment]
@grahamwhaley 
Can you take a look ?

thanks

**Comment by grahamwhaley** [comment]
/test-ubuntu
Not really my area @tedyu :-) - we can wait for @bergwolf to have a look, and try to pull in some others maybe /cc @gnawux . I can trigger the test run though ;-)

**Comment by tedyu** [comment]
@bergwolf 
Can you take a look ?

**Pull request merged**
