### PR TITLE
katautils: Move SetKernelParams from CreateSandbox to updateRuntimeCo…

### PR DESCRIPTION
**Pull request by teawater**
…nfig

Function SetKernelParams is just to update the runtimeConfig according to itself.
It just around the configuration.
So this patch moves it to updateRuntimeConfig.

Fixes: #1106

Signed-off-by: Hui Zhu <teawater@hyper.sh>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Please update the tests:

```
--- FAIL: TestCreateInvalidKernelParams (0.02s)
    <autogenerated>:1: 
                          
	Error Trace:	create_test.go:778
        
	Error:      	Should be false
    <autogenerated>:1: 
                          
	Error Trace:	create_test.go:778
        
	Error:      	Should be false
```

**Comment by lifupan** [comment]
LGTM

**Comment by bergwolf** [comment]
LGTM

**Pull request merged**
