### PR TITLE
virtiofs: stop sandbox when virtiofsd quits

### PR DESCRIPTION
**Pull request by eryugey**
Commit 89e0dfae111e ("qemu: stop qemu process when virtiofsd quits")
stops sandbox when virtiofsd quits so that virtiofs mount inside guest
won't hang. But commit d5a3d0a61c70 ("virtiofs: use virtiofsd
--fd=FDNUM") deleted this monitor logic.

Add the Scanner back to monitor virtiofsd's stderr and stop sandbox if
Scanner returns error.

Note that we don't monitor the virtiofsd process itself is because
virtiofsd may be live-upgraded (when available) and the original
process may quit, but virtiofs service is still running.

Fixes: #2315 
Fixes: d5a3d0a61c70 ("virtiofs: use virtiofsd --fd=FDNUM")
Signed-off-by: Eryu Guan <eguan@linux.alibaba.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
@eryugey - Travis is failing:

```
ound 1 commit between commit 622cec98336c588075a00569fd76a5f926c3222d and branch master
ERROR: No "Fixes" found
ERROR: checkcommits failed. See the document below for help on formatting
commits for the project.
https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format
```

To fix this, please edit the commit message to specify `Fixes: #2315` (rather than specifying a commit) and re-push.

**Comment by eryugey** [comment]
> To fix this, please edit the commit message to specify `Fixes: #2315` (rather than specifying a commit) and re-push.

Force pushed, thanks!

**Comment by jodh-intel** [comment]
Thanks @eryugey.

/test

**Comment by egernst** [comment]
(restarting opensuse-15 test)

**Pull request merged**
