### PR TITLE
kernel: update to 4.19.83

### PR DESCRIPTION
**Pull request by egernst**
Fixes: 1816

Signed-off-by: Eric Ernst <eric.ernst@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Also, #1816 was closed in September, so please can you raise a new issue and provide details of why this change is needed?

**Comment by egernst** [comment]
Pragmatism and laziness.  Do we want a duplicate GitHub issue for bumps each time? The rationale for doing a bump should be very clear. If there are specific CVEs we open them seperately.  WDYT?

**Comment by jodh-intel** [comment]
I personally still vote for discrete issues for each bump as referring to a closed issue is confusing.

The laziness factor can be handled by using [`hub`](https://github.com/github/hub):

```sh
$ echo -e "I am the issue title\n\nThis is the body of the description.\nMore body\nHub is cool" | hub issue create -F -
```

**Comment by egernst** [comment]
Looks like ARM patches aren't applying.

@jongwu @Pennyzct can you PTAL?

**Comment by gnawux** [comment]
@Pennyzct your nightmare unfortunately 😿

**Comment by Pennyzct** [comment]
Hi @egernst plz bump the version to v4.19.84. It's the latest and will decrease the failed chunks.
I've raised the PR to do the update, and you could add the `Depends-on: github.com/kata-containers/packaging#807` to see if ARM CI is working well again. ;)

**Comment by amshinde** [comment]
@egernst CI does not seem to be very happy.

**Comment by egernst** [comment]
@Pennyzct  ^ still unhappy with patches. Sorry.

**Comment by Pennyzct** [comment]
Hi @egernst 
So sorry for the delay. 
I have updated my PR to be also v4.19.86. And ARM CI is happy now. ;)

**Comment by Pennyzct** [comment]
As to the failure on ARM CI:
```
not ok 1 Expose IP Address
```
I've addressed related issue [kata-containers/ci#229](https://github.com/kata-containers/ci/issues/229) to fix, and it should be irrelevant to this patch. ;).

**Comment by egernst** [comment]
rerunning virtio-fs test.  If it passes, we should be good to merge.

**Pull request merged**
