### PR TITLE
vendor: update kata agent

### LINKED ISSUE #576: Failed to check if grpc server is working: context deadline exceeded: unknown when using vsocks
I enabled a new Job that runs the tests using vsock, but I have seen this error frequently on different tests from docker and cri-containerd:

docker test failure:
```
docker kill killing container 
  with '26'(virtual timer expired) signal
  /tmp/jenkins/workspace/kata-containers-tests-vsock-fedora-27-PR/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46
Running command '/usr/bin/docker [docker run --runtime kata-runtime --name NzW80u0qGirlMmcfV4zegNrZLoKxLt -dt busybox sh -c trap "exit 26" 26; echo TRAP_RUNNING; while :; do sleep 1; done]'
command failed error 'exit status 125'
[docker run --runtime kata-runtime --name NzW80u0qGirlMmcfV4zegNrZLoKxLt -dt busybox sh -c trap "exit 26" 26; echo TRAP_RUNNING; while :; do sleep 1; done]
Timeout: 60 seconds
Exit Code: 125
Stdout: 086543aa8dcc805affbc306c04035b10d8745ca8983b6758be08c7c5dd9f4b26

Stderr: docker: Error response from daemon: OCI runtime create failed: Failed to check if grpc server is working: context deadline exceeded: unknown.
```

cri-containerd test failure:
```
• Failure in Spec Setup (BeforeEach) [9.285 seconds]
[k8s.io] Container
/tmp/jenkins/workspace/kata-containers-tests-vsock-fedora-27-PR/go/src/github.com/kubernetes-incubator/cri-tools/pkg/framework/framework.go:72
  runtime should support basic operations on container
  /tmp/jenkins/workspace/kata-containers-tests-vsock-fedora-27-PR/go/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/container.go:68
    runtime should support stopping container [Conformance] [BeforeEach]
    /tmp/jenkins/workspace/kata-containers-tests-vsock-fedora-27-PR/go/src/github.com/kubernetes-incubator/cri-tools/pkg/validate/container.go:100

    failed to create PodSandbox: rpc error: code = Unknown desc = failed to start sandbox container: failed to create containerd task: OCI runtime create failed: Failed to check if grpc server is working: context deadline exceeded: unknown
    Expected error:
        <*status.statusError | 0xc4204a8900>: {
            Code: 2,
            Message: "failed to start sandbox container: failed to create containerd task: OCI runtime create failed: Failed to check if grpc server is working: context deadline exceeded: unknown",
            Details: nil,
        }
        rpc error: code = Unknown desc = failed to start sandbox container: failed to create containerd task: OCI runtime create failed: Failed to check if grpc server is working: context deadline exceeded: unknown
    not to have occurred
```

Failed jobs:
http://jenkins.katacontainers.io/job/kata-containers-tests-vsock-fedora-27-PR/18/consoleFull
http://jenkins.katacontainers.io/job/kata-containers-tests-vsock-fedora-27-PR/16/consoleFull
http://jenkins.katacontainers.io/job/kata-containers-tests-vsock-fedora-27-PR/12/consoleFull
http://jenkins.katacontainers.io/job/kata-containers-tests-vsock-fedora-27-PR/13/consoleFull

### PR DESCRIPTION
**Pull request by devimc**
Increase dial timeout to fix context deadline exceeded when
using vsocks

Shortlog:
93fe84e protocols: increase dial timeout
730b977 client: bypass grpc dialer backoff strategy
41c09c2 agent: enable memory hierarchical account
4f70b1c channel: remove unused functions
f6486e7 channel: support communication channel hotplug
28afabb release: Kata Containers 1.2.0

fixes #576

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by devimc** [comment]
@egernst no, there are not changes in the agent gRPC protocol

**Comment by jodh-intel** [comment]
lgtm

**Comment by chavafg** [comment]
recheck

**Comment by chavafg** [comment]
recheck

**Comment by jodh-intel** [comment]
lgtm

**Pull request merged**
