### PR TITLE
vendor: update govmm and agent to support memory update

### LINKED ISSUE #671: Update vendor to support memory update
Related to #624 , which need govmm qmp and agent pb update. We should update govmm and agent pkg in vendor.

Create a new PR #669 .

### PR DESCRIPTION
**Pull request by linzichang**
vendor: update govmm and agent to support memory update
    Fixes #671 

    To support kata-runtime update memory, need separate CPU/memory in agent grpc handler
    and handler query-memory-devices QMP commands in govmm.

    1.Implement query-memory-devices QMP commands(govmm).
    2.Add "CpuOnly" field to onlineCPUMem grpc request(agent).

    govmm Shortlog:
    b16291c qemu/qmp: support query-memory-devices qmp command.

    agent Shortlog:
    74a5364 build: fix make proto error
    b1c2ad8 agent: add support for online memory and cpu separately.

    Signed-off-by: Zichang Lin <linzichang@huawei.com>
    Signed-off-by: Clare Chen <clare.chenhui@huawei.com>

### CODE REVIEW

**Comment by linzichang** [comment]
Related to #624

**Comment by jodh-intel** [comment]
lgtm but build failing. From Travis:

```
../virtcontainers/qemu.go:862:53: not enough arguments in call to q.qmpMonitorCh.qmp.ExecuteNetPCIDeviceAdd
	have ("context".Context, string, string, string, string, string)
	want ("context".Context, string, string, string, string, string, int)
```

**Comment by linzichang** [comment]
CI is failed. I think there are some problems in CI environment, unrelated to my change.

**Comment by caoruidong** [comment]
We have a issue track this failure. https://github.com/kata-containers/tests/issues/680

**Comment by WeiZhang555** [comment]
This is duplicate of https://github.com/kata-containers/runtime/pull/649

**Comment by linzichang** [comment]
@WeiZhang555 This PR need govmm and agent update. And the govmm update is newly that #649 . Two choose:
1. Merge #649 first, then I make a rebase on this PR.
2. Close #649 , just merge this PR.

**Comment by jshachm** [comment]
PLZ rebase this. #649 is just going to be merged~

**Comment by jodh-intel** [comment]
yep - #649 is now merged so this needs a rebase.

**Comment by linzichang** [comment]
Don't merge,  #624 need more agent.pb update.

**Comment by caoruidong** [comment]
If so, I think this can be a commit of PR #624

**Comment by jodh-intel** [comment]
I agree with @caoruidong.

**Comment by linzichang** [comment]
Combine this into #624 . Close.

**Pull request closed without merging**
