### PR TITLE
versions: kernel: update to 4.19.28

### PR DESCRIPTION
**Pull request by grahamwhaley**
Update kernel to latest version.

Fixes: #1288

Signed-off-by: Graham Whaley <graham.whaley@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
/test
minor version update, let's see if it flies
/cc @jcvenegas @sboeuf

**Comment by grahamwhaley** [comment]
ARM CI fail looks on the surface like a network download error - I'll nudge it - it is in the kernel version area though...

```
12:44:48 INFO: Current Kernel version 4.19.26.25
12:44:48 INFO: Get packaged kernel version
12:44:48 INFO: Packaged Kernel version 
12:44:48 INFO: Install kernel from sources
12:44:48 INFO: Clone config and patches
12:44:48 INFO: Config version: 25
12:44:48 INFO: Kernel version: 4.19.26
12:44:48 INFO: kernel path does not exist, will download kernel
12:44:48   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
12:44:48                                  Dload  Upload   Total   Spent    Left  Speed
12:44:48 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  290k  100  290k    0     0  3267k      0 --:--:-- --:--:-- --:--:-- 3267k
12:44:49 Build step 'Execute shell' marked build as failure
```

**Comment by grahamwhaley** [comment]
ARM CI is now failing on what look like some CPU/arch type items. Here is a quick summary from the log:

```
16:42:21 --- FAIL: TestEnvGetEnvInfoSetsCPUType (0.02s)
16:42:21 --- FAIL: TestEnvGetHostInfo (0.00s)
16:42:21 --- FAIL: TestEnvGetEnvInfo (0.04s)
16:42:21 --- FAIL: TestEnvGetEnvInfoNoHypervisorVersion (0.02s)
```
@Pennyzct - something you can look into?

The 16.04-initrd fail I can't chase now, as that has moved to 18.04 in the CI. The only way to re-trigger that is to do a full test retrigger.... we'll have to decide if we need to (I suspect we do...)
Let's give @Pennyzct a chance to look at the ARM CI first..

**Comment by Pennyzct** [comment]
Hi~ @grahamwhaley sorry for the delay. got sidetracked. I'm already working on this, related PR online asap. ;)

**Comment by grahamwhaley** [comment]
/test
as the two failing CIs links are now stale.
The only CI I think might currently fail (not due to this PR) is the vsocks ...

**Comment by grahamwhaley** [comment]
Hmm, CI errors still... 3 fails for what look like 3 different reasons:

### 18.04-initrd

```
Summarizing 1 Failure:

[Fail] Update CPU constraints Update number of CPUs to check period and quota [It] quota/period should be equal to 3.0 
/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR-initrd/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:364

Ran 229 of 237 Specs in 1793.968 seconds
FAIL! -- 228 Passed | 1 Failed | 0 Pending | 8 Skipped --- FAIL: TestIntegration (1815.42s)
```

### fedora-vsocks

```
72002e1944d775736cee99f64ea42e26e3b06829bef87ab32e415bf10e88411e
docker: Error response from daemon: OCI runtime create failed: Failed to check if grpc server is working: context deadline exceeded: unknown.
Checking 17 containers have all relevant components
Wrong number of shims running (17 != 16) - stopping
Wrong number of netmons running (17 != 16) - stopping
Wrong number of 'runtime list' containers running (17 != 16) - stopping
Wrong number of pods in /var/lib/vc/sbs (17 != 16) - stopping)
```

### 7.4-fc

```
Starting stability test: bind_mount_linux.sh
d0cfa96c1495eaa8db0dfbf3769b746f810ea806606f5d43fa4de35281a987f3
docker: Error response from daemon: OCI runtime create failed: Failed to check if grpc server is working: context deadline exceeded: unknown.
make: *** [docker-stability] Error 125
Build step 'Execute shell' marked build as failure
```

So, either the new kernel/minor update is causing instabilities, or we have some CI instabilities - but, this feels worse than 'the average' for CI right now.
/cc @chavafg for any thoughts.

**Comment by chavafg** [comment]
1. We know that the fedora vsocks job is unstable right now. 
2. About the firecracker failure, I hadn't seen it before. /cc @GabyCT may know more about this.
3. The hotplug cpu test failure on the initrd job seems like a real failure:
```
Stderr: 
Running command '/usr/bin/docker [docker exec OpaPO8gnU3T5kYEu9WE9lWVFX0ij7D bash -c perl -e "printf ('%.1f', $(cat /sys/fs/cgroup/cpu/cpu.cfs_quota_us)/$(cat /sys/fs/cgroup/cpu/cpu.cfs_period_us))"]'
command failed error 'exit status 126'
[docker exec OpaPO8gnU3T5kYEu9WE9lWVFX0ij7D bash -c perl -e "printf ('%.1f', $(cat /sys/fs/cgroup/cpu/cpu.cfs_quota_us)/$(cat /sys/fs/cgroup/cpu/cpu.cfs_period_us))"]
Timeout: 60 seconds
Exit Code: 126
Stdout: OCI runtime exec failed: rpc error: code = Internal desc = Could not run process: container_linux.go:348: starting container process caused "process_linux.go:90: adding pid 105 to cgroups caused \"failed to write 105 to cgroup.procs: write /sys/fs/cgroup/cpu/docker/554b982daa0451b5edfafce6c6c74fd97b4bd49a89443f4ca41a9b45a978ff23/cgroup.procs: invalid argument\"": unknown
```
/cc @devimc

**Comment by GabyCT** [comment]
@grahamwhaley and @chavafg , I have not seen that failure before on firecracker

**Comment by grahamwhaley** [comment]
I'm going to re-spin some CIs here to see if we really do have breakage...

**Comment by grahamwhaley** [comment]
/test
had a few 404's on the CIs, so let's run them all...

**Comment by jodh-intel** [comment]
I was about to retest all CIs as 3 of the failing jobs have expired anyway. However, @grahamwhaley maybe you could update the branch to remove the conflict and re-push to save me the effort? :)

**Comment by jodh-intel** [comment]
boo for timing clash ;)

**Comment by grahamwhaley** [comment]
afaict, the only CI we should be ignoring here is that 16.04initrd - as that job no longer exists (that is a stale fail we cannot clear from the list easily....)

**Comment by grahamwhaley** [comment]
And we are now up to 4.19.28, so updated that whilst rebasing....

**Comment by jodh-intel** [comment]
Hmm, no CI's pending. Let's try...

/retest

**Comment by jodh-intel** [comment]
:boom:

**Comment by sboeuf** [comment]
@grahamwhaley @jodh-intel what's the blocker here? We should be able to merge right?

**Comment by grahamwhaley** [comment]
@sboeuf - only if CIs are happy, and we still have a vsock failure:

```
Summarizing 1 Failure:

[Fail] [k8s.io] Container runtime should support basic operations on container [BeforeEach] runtime should support removing container [Conformance] 
/tmp/jenkins/workspace/kata-containers-runtime-fedora-vsocks-PR/go/src/github.com/kubernetes-sigs/cri-tools/pkg/framework/util.go:152

Ran 5 of 73 Specs in 22.155 seconds
FAIL! -- 4 Passed | 1 Failed | 0 Pending | 68 Skipped
```

metrics I could believe, as we merged a fix earlier today... but, we probably want to wait until I have tweaked the metrics CI and tried again - so we don't miss any regressions.
Sure, a relatively minor version bump 'should' be safe... but, that's what the CIs are here for...

**Comment by grahamwhaley** [comment]
Here is the fuller error from the vsocks CI log:

```
• Failure in Spec Setup (BeforeEach) [18.132 seconds]
[k8s.io] Container
/tmp/jenkins/workspace/kata-containers-runtime-fedora-vsocks-PR/go/src/github.com/kubernetes-sigs/cri-tools/pkg/framework/framework.go:72
  runtime should support basic operations on container
  /tmp/jenkins/workspace/kata-containers-runtime-fedora-vsocks-PR/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container.go:68
    runtime should support removing container [Conformance] [BeforeEach]
    /tmp/jenkins/workspace/kata-containers-runtime-fedora-vsocks-PR/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container.go:111

    failed to create PodSandbox: rpc error: code = Unknown desc = failed to start sandbox container: failed to create containerd task: Failed to check if grpc server is working: context deadline exceeded: unknown
    Expected error:
        <*status.statusError | 0xc0003abe30>: {
            Code: 2,
            Message: "failed to start sandbox container: failed to create containerd task: Failed to check if grpc server is working: context deadline exceeded: unknown",
            Details: nil,
        }
        rpc error: code = Unknown desc = failed to start sandbox container: failed to create containerd task: Failed to check if grpc server is working: context deadline exceeded: unknown
    not to have occurred
```

**Comment by sboeuf** [comment]
@grahamwhaley oh of course, I just thought those CI tests were flaky. But if this is a true bug introduced by this bump, then yes I agree it needs to be solved before we move :)

**Comment by amshinde** [comment]
CIs have passed. Merging this..

**Pull request merged**
