### PR TITLE
Fix ARM CI

### LINKED ISSUE #1217: ARM CI is broken
# Description of problem

Static checks fail with:

```
02:29:38 cli/kata-check_arm64.go:129:9:warning: if block ends with a return statement, so drop this else and outdent its block (move short variable declaration to its own line if necessary) (golint)
02:29:40 cli/kata-check_test.go:141:113:warning: unused variable or constant undeclared name: TestDataa (varcheck)
02:29:40 virtcontainers/qemu_arm64_test.go:43:23:warning: unused variable or constant undeclared name: virt (varcheck)
02:29:40 virtcontainers/qemu_arm64_test.go:50:11:warning: unused variable or constant undeclared name: defaultMemSlots (varcheck)
02:29:40 virtcontainers/qemu_arm64_test.go:54:40:warning: unused variable or constant too few arguments in call to arm64.memoryTopology (varcheck)
02:29:40 virtcontainers/qemu_arm64_test.go:29:23:warning: unused variable or constant undeclared name: virt (varcheck)
02:29:41 cli/kata-check_test.go:141:113:warning: unused struct field undeclared name: TestDataa (structcheck)
02:29:41 virtcontainers/qemu_arm64_test.go:43:23:warning: unused struct field undeclared name: virt (structcheck)
02:29:41 virtcontainers/qemu_arm64_test.go:50:11:warning: unused struct field undeclared name: defaultMemSlots (structcheck)
02:29:41 virtcontainers/qemu_arm64_test.go:54:40:warning: unused struct field too few arguments in call to arm64.memoryTopology (structcheck)
02:29:41 virtcontainers/qemu_arm64_test.go:29:23:warning: unused struct field undeclared name: virt (structcheck)
02:29:41 cli/kata-check_test.go:141:113:warning: undeclared name: TestDataa (staticcheck)
02:29:42 virtcontainers/qemu_arm64_test.go:43:23:warning: undeclared name: virt (unused)

```

### PR DESCRIPTION
**Pull request by sameo**
Fixes #1217

### CODE REVIEW

**Comment by sameo** [comment]
> @sameo I predict the checkcommits will complain about 'lack of commit body text' on your 3rd commit btw.
>

Thanks for the heads-up. Fixed now.

**Comment by Pennyzct** [comment]
Hi~ @sameo @grahamwhaley thanks for the proposal. I have also pulled similar request #1202 to fix the same problem a few days ago. ptal. ;}

**Comment by jcvenegas** [comment]
@sameo @Pennyzct  so both PRs are needed ? any update on this ?

**Comment by sameo** [comment]
> @sameo @Pennyzct so both PRs are needed ? any update on this ?

No, only #1202 is needed, I will close that one once the ARM CI will be fixed.

**Comment by sameo** [comment]
ARM CI is fixed now with #1202, closing.

**Pull request closed without merging**
