### PR TITLE
virtcontainers: Return the appropriate container status

### LINKED ISSUE #926: Moving to Docker 18.09 does not delete the VM and proxy when the container terminates
We usually expect `docker` to monitor the shim process representing the container process inside the VM. And by doing so, it sends a `kata-runtime delete <container-id>` when it sees the shim going away. But unfortunately, something changed between `18.06` and `18.09` that prevents this logic from working as expected here.

Reference on docker repo: https://github.com/moby/moby/issues/38233

/cc @amshinde @egernst @grahamwhaley @jodh-intel

### PR DESCRIPTION
**Pull request by sboeuf**
When our runtime is asked for the container status, we also handle
the scenario where the container is stopped if the shim process for
that container on the host has terminated.

In the current implementation, we retrieve the container status
before stopping the container, causing a wrong status to be returned.
The wait for the original go-routine's completion was done in a defer
within the caller of statusContainers(), resulting in the
statusContainer()'s values to return the pre-stopped value.

This bug is first observed when updating to docker v18.09/containerd
v1.2.0. With the current implementation, containerd-shim receives the
TaskExit when it detects kata-shim is terminating. When checking the
container state, however, it does not get the expected "stopped" value.

The following commit resolves the described issue by simplifying the
locking used around the status container calls. Originally
StatusContainer would request a read lock. If we needed to update the
container status in statusContainer, we'd start a go-routine which
would request a read-write lock, waiting for the original read lock to
be released.  Can't imagine a bug could linger in this logic. We now
just request a read-write lock in the caller (StatusContainer),
skipping the need for a separate go-routine and defer. This greatly
simplifies the logic, and removes the original bug.

Fixes #926

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
@jodh-intel @devimc @amshinde @chavafg PTAL, this PR fixes the issue seen with Docker 18.09. Other than that, we don't need to modify anything else, the fact that containerd removed the call to `kill --all` is not a big deal, but we were returning the wrong container status, which was not appreciated by containerd, and eventually `delete` was never called.

**Comment by egernst** [comment]
Suggested commit message edit:
```
When our runtime is asked for the container status, we also handle the scenario where the container is stopped if the shim process for that container on the host has terminated.

In the current implementation, we retrieve the container status before stopping the container, causing a wrong status to be returned.  The wait for the original go-routine's completion was done in a defer within the caller of statusContainers(), resulting in the statusContainer()'s values to return the pre-stopped value. 
 
This bug is first observed when updating to docker v18.09/containerd v1.2.0. With the current implementation, containerd-shim receives the TaskExit when it detects kata-shim is terminating. When checking the container state, however, it does not get the expected "stopped" value.

The following commit resolves the described issue by simplifying the locking used around the status container calls. Originally StatusContainer would request a read lock.  If we needed to update the container status in statusContainer, we'd start a go-routine which would request a read-write lock, waiting for the original read lock to be released.  Can't imagine a bug could linger in this logic.  We now just request a read-write lock in the caller (StatusContainer), skipping the need for a separate go-routine and defer.  This greatly simplifies the logic, and removes the original bug.
```

**Comment by sboeuf** [comment]
@egernst commit message updated! Thanks!

**Comment by jodh-intel** [comment]
@sboeuf - nice!!

Can you find a way to add a unit test for this change though? Given the importance of this fix, it would be good to know we have a test to assert the correct behaviour.

**Comment by jodh-intel** [comment]
@sboeuf - my bad - s/unit test/any type of test/ ;)

**Comment by jodh-intel** [comment]
ftr, I can confirm this PR fixes the issue with Docker 18.09 (tested on ubuntu bionic). The CI will be testing using docker 18.06.1 (from https://github.com/kata-containers/runtime/blob/master/versions.yaml#L154) so we can say that it works with both versions.

**Comment by sboeuf** [comment]
@jodh-intel yes that's a good idea, I think we can write a simple integration test using `kata-runtime state` after we run a simple workload that naturally exits after a few seconds. The result should be `stopped` directly, where before it would have returned `running`.
Reference: https://github.com/kata-containers/tests/issues/956

**Comment by jodh-intel** [comment]
Thanks @sboeuf - let's land this to allow you to write that test... ;)

**Comment by sboeuf** [comment]
Thanks @jodh-intel! I'll write this today!

**Pull request merged**
