### PR TITLE
Fix the issue of update resources wrong

### PR DESCRIPTION
**Pull request by lifupan**
When create container failed, it should delete the container
config from sandbox, otherwise, the following new creating container
 would get a wrong resources caculating which would contain the previous
 failed container resources such as memory and cpu.

Fixes: #1997

### CODE REVIEW

**Comment by lifupan** [comment]
> lgtm, but ideally would have a unit test to assert this behaviour - is that possible do you think?

Hi @jodh-intel , Had added some unit tests.

**Comment by jodh-intel** [comment]
Thanks @lifupan !

**Comment by devimc** [comment]
restarting nemu and initrd

**Pull request merged**
