### PR TITLE
clh: virtiofs: Add no_posix_lock option

### PR DESCRIPTION
**Pull request by jcvenegas**
Add option in qemu driver , this will allow lock operations.

Fixes: #2594

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by c3d** [comment]
This is a bit similar to #2580, although the virtiofs option is different. I believe that my comment over there, https://github.com/kata-containers/runtime/issues/2580#issuecomment-610487663, applies here as well, although the security risk associated to locking is lower.

In short, it would be better to have a "semantic" option associated to specific volumes and indicating that we _want_ to install things there. Changing options globally for all volumes seems risky, since ultimately this impacts the host.

**Comment by jcvenegas** [comment]
@c3d thanks for the pointer to the issue. 
@c3d @amshinde @grahamwhaley 
For now this PR was to match what virtiofsd qemu implementation has see:
https://github.com/kata-containers/runtime/blob/master/virtcontainers/qemu.go#L625

We have two options here, 
 - just hang in this change and remove `no_posix_lock` from qemu implementation. In addition skip test  affected by this.
- Merge this and keep working in a side solution for a "sematic" option to allow users decide to enable extra options like this. 

Both options work for me, specially because I would like to unblock cloud-hypervisor CI.
\cc @kata-containers/architecture-committee

**Comment by dagrh** [comment]
I believe one problem is that I don't think we have a setlkw (i.e. blocking) lock implementation - so if you declare that you support posix locks you get most but not a full implementation.   The difficulty is that a blocking lock is ... blocking; so you hang up one of the threads of the daemon waiting for the lock and there's no good kernel interface for it.  We could spawn threads just to hold the blocking locks but they could get eaten up quickly.
Really the world needs an asynchronous lock kernel interface, so you can say you'd like a lock but neither need to block nor poll for it.

**Comment by amshinde** [comment]
@jcvenegas @dagrh @c3d
I am curious how this change fixes the package update issue. We discussed in another thread about a running virtiofsd with the capability to change extended attributes.

**Comment by jcvenegas** [comment]
@amshinde to be honest I dont know, I figured out by checking the difference with qemu driver an clh.

Probably @dagrh could extend bit more if on the option, the effects is has, functionally and from security perspective. And finally if we should go with this change or remove the flag from qemu until a semantic option is implemented.

**Comment by amshinde** [comment]
@jcvenegas Ok Lets wait for some input here.
Following git blame, similar change to qemu was done by @chavafg. Maybe he has some input here.

@jcvenegas To be clear, this fixes the apt install issue and not dnf/yum. I believe for the latter, we still need virtiofsd to be called with support for changing extended attributes. Please confirm.

**Comment by jcvenegas** [comment]
@amshinde  I confirm this only fix apt, for dnf I still see the container hangs.

**Comment by jcvenegas** [comment]
@kata-containers/architecture-committee  ping, please feel free to merge this PR as agreed this morning in arch meeting.

**Comment by fidencio** [comment]
As discussed during the meeting Today, this option is already present for QEMU backend, let's have it merged.

**Pull request merged**
