### PR TITLE
backport: 1.6.3 rel

### PR DESCRIPTION
**Pull request by ganeshmaharaj**
Backporting the below patches for 1.6.3 release.

https://github.com/kata-containers/runtime/pull/1409
https://github.com/kata-containers/runtime/pull/1439
https://github.com/kata-containers/runtime/pull/1528
https://github.com/kata-containers/runtime/pull/1541
https://github.com/kata-containers/runtime/pull/1547
https://github.com/kata-containers/runtime/pull/1554
https://github.com/kata-containers/runtime/pull/1599
https://github.com/kata-containers/runtime/pull/1530

### CODE REVIEW

**Comment by ganeshmaharaj** [comment]
centos-7-4-q-35
```
=== RUN   TestHostNetworkingRequested
--- FAIL: TestHostNetworkingRequested (0.01s)
    assertions.go:239: 
                          
	Error Trace:	network_test.go:98
        
	Error:      	Should be true
=== RUN   TestSetupNetworkNamespace
```

sles-12
```
=== RUN   TestNsEnterSuccessful
--- FAIL: TestNsEnterSuccessful (0.00s)
    assertions.go:239: 
                          
	Error Trace:	nsenter_test.go:210
        
	Error:      	Expected nil, but got: &errors.errorString{s:"failed to open target ns: failed to Statfs \"/proc/109136/ns/cgroup\": no such file or directory"}
        
	Messages:   	failed to open target ns: failed to Statfs "/proc/109136/ns/cgroup": no such file or directory
    assertions.go:239: 
                          
	Error Trace:	nsenter_test.go:240
        
	Error:      	Not equal: 
        
	            	expected: "cgroup"
        
	            	actual: "0"
    assertions.go:239: 
                          
	Error Trace:	nsenter_test.go:240
        
	Error:      	Not equal: 
        
	            	expected: "ipc:[4026533094]"
        
	            	actual: "0"
    assertions.go:239: 
                          
	Error Trace:	nsenter_test.go:240
        
	Error:      	Not equal: 
        
	            	expected: "net:[4026533097]"
        
	            	actual: "0"
    assertions.go:239: 
                          
	Error Trace:	nsenter_test.go:240
        
	Error:      	Not equal: 
        
	            	expected: "pid:[4026533095]"
        
	            	actual: "0"
    assertions.go:239: 
                          
	Error Trace:	nsenter_test.go:240
        
	Error:      	Not equal: 
        
	            	expected: "uts:[4026533093]"
        
	            	actual: "0"
FAIL
```

**Comment by jcvenegas** [comment]
@GabyCT is a known issue ? 
```
--- FAIL: TestHostNetworkingRequested (0.01s)
    assertions.go:239: 
                          
	Error Trace:	network_test.go:98
        
	Error:      	Should be true
```
for centos ?

**Comment by jodh-intel** [comment]
@jcvenegas - yep, it's known - see https://github.com/kata-containers/runtime/issues/1604.

**Comment by jcvenegas** [comment]
@jodh-intel thanks! So I will merge it in a few minutes, please let me know you are not agree to merge it for that faling CI job.

@jodh-intel @egernst @grahamwhaley

**Comment by jodh-intel** [comment]
@jcvenegas - the centos failure can be ignored imho as we won't get it fixed today and it's not specific to this PR anyway.

**Pull request merged**
