### PR TITLE
[backport]: virtiofs: Change to cache auto and no DAX

### PR DESCRIPTION
**Pull request by jcvenegas**
Backport from master

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
yes, please! :-)

lgtm, thanks @jcvenegas.

**Comment by fidencio** [comment]
```
22:54:10 Patch failed at 0090 ci: don't disable vmx-rdseed-exit on experimental QEMU
22:54:10 Resolve all conflicts manually, mark them as resolved with
22:54:10 "git add/rm <conflicted_files>", then run "git rebase --continue".
22:54:10 You can instead skip this commit: run "git rebase --skip".
22:54:10 To abort and get back to the state before "git rebase", run "git rebase --abort".
22:54:11 Build step 'Execute shell' marked build as failure
```

**Comment by fidencio** [comment]
ubuntu:
```
[2] • Failure [11.808 seconds]
[2] capabilities
[2] /tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR-initrd/go/src/github.com/kata-containers/tests/integration/docker/cap_test.go:19
[2]   drop and add capabilities
[2]   /tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR-initrd/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table.go:92
[2]     cap_sys_pacct [It]
[2]     /tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR-initrd/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43
[2] 
[2]     Expected
[2]         <int>: 125
[2]     to equal
[2]         <int>: 0
[2] 
[2]     /tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR-initrd/go/src/github.com/kata-containers/tests/integration/docker/cap_test.go:47
[2] ------------------------------
[2] SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
[2] 
[2] Summarizing 1 Failure:
[2] 
[2] [Fail] capabilities drop and add capabilities [It] cap_sys_pacct 
[2] /tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR-initrd/go/src/github.com/kata-containers/tests/integration/docker/cap_test.go:47
[2] 
[2] Ran 33 of 140 Specs in 352.068 seconds
[2] FAIL! -- 32 Passed | 1 Failed | 0 Pending | 107 Skipped
[2] --- FAIL: TestIntegration (352.07s)
[2] FAIL
```

**Review by jodh-intel — APPROVED** [review]

**Pull request merged**
