### PR TITLE
vendor: Update github.com/kata-containers/agent

### PR DESCRIPTION
**Pull request by teawater**
Update github.com/kata-containers/agent to
introduce fix of hybrid vsock.

Fixes: #2284

Signed-off-by: Hui Zhu <teawater@antfin.com>

### CODE REVIEW

**Comment by lifupan** [comment]
Hi @teawater ,
I think need to add a summary of  range of commits being added for these third-party packages in commit message. 
Please refer  https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#re-vendor-prs .

**Comment by teawater** [comment]
I found that there is another issue should be fix about fc.  I will update curent PR later.

**Comment by teawater** [comment]
@lifupan @jodh-intel Thanks for your remind.  I pushed a new commit according to your comments.

**Comment by egernst** [comment]
Wondering about this failure:
```
not ok 31 ctr with default list of capabilities from crio.conf
# (in test file ctr.bats, line 1064)
#   `[ "$status" -eq 0 ]' failed
# time="2019-12-04T15:04:57Z" level=error msg="File descriptor 3 (pipe:[3799975]) leaked on pvdisplay invocation. Parent PID 30107: /tmp/jenkins/workspace/kata-con\nFile descriptor 6 (/dev/mapper/control) leaked on pvdisplay invocation. Parent PID 30107: /tmp/jenkins/workspace/kata-con\n  Failed to find physical volume \"/dev/sdb\".\n" error="exit status 5"
# 0
```

**Comment by teawater** [comment]
jenkins-ci-ubuntu-1804-firecracker failed:
```
#   `[ "$status" -eq 0 ]' failed
# time="2019-12-05T04:31:54Z" level=error msg="File descriptor 3 (pipe:[2961050]) leaked on pvdisplay invocation. Parent PID 27856: /tmp/jenkins/workspace/kata-con\nFile descriptor 6 (/dev/mapper/control) leaked on pvdisplay invocation. Parent PID 27856: /tmp/jenkins/workspace/kata-con\n  Failed to find physical volume \"/dev/sdb\".\n" error="exit status 5"
# 0
# time="2019-12-05 04:32:08.868841497Z" level=debug msg="found valid runtime \"runc\" for runtime_path \"/usr/local/bin/kata-runtime\"" file="config/config.go:803"
# time="2019-12-05 04:32:08.868962200Z" level
```

I think it doesn't have relation with this PR.

**Comment by teawater** [comment]
jenkins-ci-ubuntu-1804-firecracker failed a lot of times with different fails.
And http://jenkins.katacontainers.io/job/kata-containers-runtime-ubuntu-1804-PR-firecracker/1305/ got success after these fails.  So I think maybe there are something not right in this PR.

I worried that it has relation with the big update of golang.org/x/sys that is need by github.com/kata-containers/agent.

**Pull request merged**
