### PR TITLE
shim-v2: support shim v2 options

### PR DESCRIPTION
**Pull request by Ace-Tang**
register shim v2 option in create
Fixes: #1583

Signed-off-by: Ace-Tang <aceapril@126.com>

### CODE REVIEW

**Comment by Ace-Tang** [comment]
Do I need to update `Gopkg.lock` file, @lifupan

**Comment by devimc** [comment]
@Ace-Tang yes, you need to re-vendor containerd, see https://github.com/kata-containers/community/blob/master/VENDORING.md#update-a-vendored-package

**Comment by Ace-Tang** [comment]
@devimc  Oh, thanks for the link

**Comment by Ace-Tang** [comment]
When I execute `dep ensure`, it update many packages, any suggest ?
```
diff --git a/Gopkg.lock b/Gopkg.lock
index fd7ea6b..f857f3e 100644
--- a/Gopkg.lock
+++ b/Gopkg.lock
@@ -2,7 +2,7 @@
 
 
 [[projects]]
-  digest = "1:79896046d0807ae89b74ae106b6cb0b346c201c02fc57b7c56017edad7493a61"
+  digest = "1:5d72bbcc9c8667b11c3dc3cbe681c5a6f71e5096744c0bf7726ab5c6425d5dc4"
   name = "github.com/BurntSushi/toml"
   packages = ["."]
   pruneopts = "NUT"
@@ -10,7 +10,7 @@
   version = "v0.3.1"
 
 [[projects]]
-  digest = "1:26b14a6dc72ace253599e969997d5ecf2143c63833c015179786bc756c76eaa4"
+  digest = "1:2be791e7b333ff7c06f8fb3dc18a7d70580e9399dbdffd352621d067ff260b6e"
   name = "github.com/Microsoft/go-winio"
   packages = ["."]
   pruneopts = "NUT"
@@ -18,7 +18,7 @@
   version = "v0.4.12"
 
 [[projects]]
-  digest = "1:e4eec8e05fe8611837a9b34a787cf9c714a2fd9228a0a1f41dd2ccccbaa21b7e"
+  digest = "1:a8e16b4caf3575365c9aa3380d9418f31dd0b810596faebfe3a15c37fabeee4a"
   name = "github.com/Microsoft/hcsshim"
   packages = [
     ".",
@@ -65,16 +65,6 @@
   revision = "ccb8e960c48f04d6935e72476ae4a51028f9e22f"
   version = "v9"
 
-[[projects]]
-  digest = "1:f1bb062def4356e0ffacbf80952a122489df3d26887249a6d351f5b3c98d4c16"
-  name = "github.com/clearcontainers/proxy"
-  packages = [
-    "api",
-    "client",
-  ]
-  pruneopts = "NUT"
-  revision = "1d2a6a3ea132a86abd0731408b7dc34f2fc17d55"
-
```

**Comment by Ace-Tang** [comment]
I execute `/home/ace/go/bin/dep ensure -no-vendor` , and found many changed in `Gopkg.lock`

**Comment by grahamwhaley** [comment]
@jodh-intel - is this the same dep file you are hitting your head on?
@sboeuf for your deppyness input and diagnostic skills...

**Comment by sboeuf** [comment]
@Ace-Tang since you're adding this new dependency `github.com/containerd/containerd/runtime/v2/runc/options`, you simply need to run `dep ensure -update github.com/containerd/containerd`.

**Comment by Ace-Tang** [comment]
@sboeuf , updated, thanks

**Comment by Ace-Tang** [comment]
Disscussed with @lifupan , not MUST add shim option now, so close it

**Pull request closed without merging**
