### PR TITLE
unit test: Fix local test

### PR DESCRIPTION
**Pull request by jcvenegas**
- Simply empty string proxy type handling and cast string  ProxyType
- Allow run make check-go-test from virtcontainers directory 
Fixes: #1312

### CODE REVIEW

**Comment by grahamwhaley** [comment]
/test
as I suspect you would not have pushed it if you didn't want to see what the CIs thought...

**Comment by jcvenegas** [comment]
@kata-containers/runtime ready to review

**Comment by grahamwhaley** [comment]
The opensuse CI fail looks unrelated. @GabyCT - is this one you know of/have fixed already:

```
Problem: conflicting requests
 Solution 1: Following actions will be done:
  do not ask to delete all solvables providing docker.x86_64 = 18.06.1_ce-lp150.5.6.1
  keep docker-libnetwork-0.7.0.1+gitr2664_3ac297bc7fd0-lp150.3.3.1.x86_64
  keep docker-runc-1.0.0rc5+gitr3562_69663f0bd4b6-lp150.5.7.1.x86_64
 Solution 2: remove lock to allow removal of docker-18.06.1_ce-lp150.5.6.1.x86_64
```

**Comment by grahamwhaley** [comment]
Other CIs are happy ... merging

**Pull request merged**
