### PR TITLE
kernel: Update kernel to latest stable 5.4.15

### PR DESCRIPTION
**Pull request by amshinde**
Fixes: #2421

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
/test-ubuntu
I'm half expecting we might hit some kernel fragment CONFIG deprecation issues, which might need some items adding to the fragment whitelist etc. let's see....

**Comment by amshinde** [comment]
@grahamwhaley Yup, CI is tripping, was expecting that :) Time to have a good look.

**Comment by amshinde** [comment]
Rerunning ARM and virtio-fs PRs as these seems to be failing k8s test. 
But the powerpc  CI is failing while building kernel.

```
ERROR: failed to find default config /home/jenkins/workspace/kata-containers-runtime-Power8-ubuntu-18-04-PR-initrd/go/src/github.com/kata-containers/packaging/kernel/configs/powerpc_kata_kvm_5.4.x```

@nitkon Looks like a 5.4 config is missing for powerpc:
https://github.com/kata-containers/packaging/tree/master/kernel/configs

Due you see any issues in moving to 5.4 for powerpc. If not, can you add a 5.4 config for powerpc?
It can be added as a commit to my existing PR in the packaging repo if you want:
https://github.com/kata-containers/packaging/pull/925

**Comment by amshinde** [comment]
I am seeing ARM CI failing with 
```
configmap/kube-flannel-cfg created
22:16:27 error: error validating "/home/jenkins/workspace/kata-containers-runtime-ARM-18.04-PR/go/src/github.com/kata-containers/tests/integration/kubernetes/../../.ci/aarch64/kubernetes/kube-flannel.yml": error validating data: ValidationError(DaemonSet.spec.template.spec.containers): invalid type for io.k8s.api.core.v1.PodSpec.containers: got "map", expected "array"; if you choose to ignore these errors, turn validation off with --validate=false
22:16:27 Failed at 130: kubectl apply -f "$network_plugin_config"
22:16:27 Failed at 79: ./init.sh
```

@chavafg @Pennyzct Is this something that we have seen before?

**Comment by jcvenegas** [comment]
virtiofs job will keep using kernel https://gitlab.com/virtio-fs/linux/-/tree/virtio-fs-v0.3 that is based in 
Linux 5.3-rc3

In the web page of virtiofs I see that say `Linux v5.4 and later includes virtio-fs` @dagrh is it fine if we just move to a vanilla 5.4? or is there any limitations that were not merged yet into upstream
@sboeuf same question for you doe clh require aditional patches of what 5.4 has? and what are those?

**Comment by dagrh** [comment]
> virtiofs job will keep using kernel https://gitlab.com/virtio-fs/linux/-/tree/virtio-fs-v0.3 that is based in
> Linux 5.3-rc3
> 
> In the web page of virtiofs I see that say `Linux v5.4 and later includes virtio-fs` @dagrh is it fine if we just move to a vanilla 5.4? or is there any limitations that were not merged yet into upstream
> @sboeuf same question for you doe clh require aditional patches of what 5.4 has? and what are those?

Upstream doesn't have virtiofs-DAX support yet; non-DAX works out of the box with upstream kernel/qemu

**Comment by sboeuf** [comment]
@jcvenegas `cloud-hypervisor` kernel branch [here](https://github.com/cloud-hypervisor/linux/tree/virtio-fs-virtio-iommu-topo-5.5-rc1) includes the extra patches needed to have the DAX support with 5.5 kernel.

**Comment by amshinde** [comment]
@nitkon Any progress here?

**Comment by amshinde** [comment]
Rerunning powerpc CI

**Pull request merged**
