### PR TITLE
virtcontainers: Remove unnecessary kernel parameters for ppc64le

### PR DESCRIPTION
**Pull request by nitkon**
Fixes: #360

Signed-off-by: Nitesh Konkar <niteshkonkar@in.ibm.com>

### CODE REVIEW

**Comment by nitkon** [comment]
@sboeuf @jodh-intel

**Comment by katabuilder** [comment]
PSS Measurement:
Qemu: 159746 KB
Proxy: 4653 KB
Shim: 8906 KB

Memory inside container:
Total Memory: 2045972 KB
Free Memory:  1997004 KB

**Comment by jodh-intel** [comment]
Thanks @nitkon. Nice.

lgtm

**Comment by nitkon** [comment]
@jodh-intel : I see one failure from jenkins-ci-ubuntu-16-04 which has a ``` Required``` tag. 
```
Summarizing 1 Failure:

[Fail] Update number of CPUs Update CPU period and quota [It] should have 3 CPUs 
/home/jenkins/jenkins_slave/workspace/kata-containers-runtime-ubuntu-16-04-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:278
```
How do we treat this? I don't think its related to my patch.

**Comment by jodh-intel** [comment]
Hi @devimc - any thoughts on that failure?

**Comment by devimc** [comment]
lgtm

**Comment by devimc** [comment]
@jodh-intel the error is 

```
Stderr: 
Running command '/usr/bin/docker [docker exec xtZlrXwGDH3mDcFRwE8sXY5bFBaDlD bash -c for c in $(seq 1 5); do [ -d /sys/devices/system/cpu/cpu3 ] && nproc && exit 0; sleep 5; done; exit 1]'
command failed error 'exit status 126'
[docker exec xtZlrXwGDH3mDcFRwE8sXY5bFBaDlD bash -c for c in $(seq 1 5); do [ -d /sys/devices/system/cpu/cpu3 ] && nproc && exit 0; sleep 5; done; exit 1]
Timeout: 60 seconds
Exit Code: 126
Stdout: OCI runtime exec failed: rpc error: code = Internal desc = Could not run process: container_linux.go:348: starting container process caused "process_linux.go:90: adding pid 173 to cgroups caused \"failed to write 173 to cgroup.procs: write /sys/fs/cgroup/cpu,cpuacct/docker/07c01f0fe8808f4083249dba2fe4ad5be451021998a692fdaf3214cdd4b3e16a/cgroup.procs: invalid argument\"": unknown
```

**Comment by katabuilder** [comment]
PSS Measurement:
Qemu: 161951 KB
Proxy: 6668 KB
Shim: 10918 KB

Memory inside container:
Total Memory: 2045972 KB
Free Memory:  1997128 KB

**Comment by jodh-intel** [comment]
lgtm

**Pull request merged**
