### PR TITLE
versions: Update cri-o to fix race condition test.

### PR DESCRIPTION
**Pull request by jcvenegas**
Some test were CI test were failing due to a race condition.

Update cri-o repository to have a stable CI.

Fixes: #435

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by jcvenegas** [comment]
do not merge  - still see some fails - update to branch 1.11 to verify if is the branch 1.10

**Comment by sboeuf** [comment]
@jcvenegas we need the commit `e0dd8a3d4c9e5ebc8b25299950bd5b222e3783d3`, was it the one you were using ?

**Comment by jodh-intel** [comment]
lgtm

**Comment by WeiZhang555** [comment]
Is this ready for merging? @jcvenegas 
LGTM

**Comment by chavafg** [comment]
I think it is, but needs to be merged along https://github.com/kata-containers/tests/pull/462

**Comment by chavafg** [comment]
merging this one as https://github.com/kata-containers/tests/pull/462 is already merged.

**Pull request merged**
