### PR TITLE
vc: Remove unnecessary call to kill

### LINKED ISSUE #2207: Clh: fix potentially racy kill sequence
# Description of problem

See https://github.com/kata-containers/runtime/pull/2164/files#r346776205

### PR DESCRIPTION
**Pull request by tedyu**
Fixes #2207

    Addresses https://github.com/kata-containers/runtime/pull/2204#issuecomment-555409722

    Signed-off-by: Ted Yu <yuzhihong@gmail.com>

### CODE REVIEW

**Comment by tedyu** [comment]
@jodh-intel 
Please take a look.

**Comment by grahamwhaley** [comment]
Hmm, Travis complaining about no SoB - can you see anything obvious @jodh-intel ?

```
ERROR: Commit 2950d87b6ab18f4ca1dfaac4a7bd628bd0bb761b: no Signed-off-by specified
```

**Comment by tedyu** [comment]
@grahamwhaley 
I removed the leading indentation for the sign off.

**Comment by tedyu** [comment]
Test failure in kata-containers-runtime-ubuntu-18-04-PR-initrd doesn't seem to be related.

**Comment by tedyu** [comment]
@grahamwhaley
Can this be merged ?

thanks

**Comment by grahamwhaley** [comment]
@tedyu - heh, helps if you post the logs from the failed CI so we can see...:

```
Summarizing 5 Failures:

[Fail] [k8s.io] Container runtime should support basic operations on container [BeforeEach] runtime should support removing container [Conformance] 
/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR-initrd/go/src/github.com/kubernetes-sigs/cri-tools/pkg/framework/util.go:214

[Fail] [k8s.io] Container runtime should support basic operations on container [BeforeEach] runtime should support starting container [Conformance] 
/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR-initrd/go/src/github.com/kubernetes-sigs/cri-tools/pkg/framework/util.go:214

[Fail] [k8s.io] Container runtime should support basic operations on container [BeforeEach] runtime should support execSync [Conformance] 
/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR-initrd/go/src/github.com/kubernetes-sigs/cri-tools/pkg/framework/util.go:214

[Fail] [k8s.io] Container runtime should support basic operations on container [BeforeEach] runtime should support stopping container [Conformance] 
/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR-initrd/go/src/github.com/kubernetes-sigs/cri-tools/pkg/framework/util.go:214

[Fail] [k8s.io] Container runtime should support basic operations on container [BeforeEach] runtime should support creating container [Conformance] 
/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR-initrd/go/src/github.com/kubernetes-sigs/cri-tools/pkg/framework/util.go:214

Ran 5 of 80 Specs in 28.791 seconds
FAIL! -- 0 Passed | 5 Failed | 0 Pending | 75 Skipped
```

and then, we normally re-fire the failed CI to check if it was sporadic or reproducible. Let me re-trigger that build on Jenkins...

**Comment by tedyu** [comment]
@grahamwhaley 
All tests passed.

**Comment by grahamwhaley** [comment]
yay, so let's say sporadic fail... merging.

**Pull request merged**
