### PR TITLE
versions: kernel: update to 4.19.65

### PR DESCRIPTION
**Pull request by egernst**
52 is long in the tooth.  On to x.y.65!

Fixes: #1947

Signed-off-by: Eric Ernst <eric.ernst@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
A couple of CI fails.
@GabyCT, Jaeger trace test seems to have failed on Debian10 - known issue?
```
21:55:20 6b5697b90c38: Pull complete
21:55:20 acfcd6cf6e2a: Pull complete
21:55:20 Digest: sha256:9557b64b16cdd41af36b0deaead0cc5f7ef9a2aad262a4dc327fbe503318363a
21:55:20 Status: Downloaded newer image for jaegertracing/all-in-one:latest
21:55:24 6e0326702111b9933b9329ac63040c929ade01af043fcb93aa30557b3ae6ff4c
21:55:24 INFO: Enabling kata tracing on /usr/share/defaults/kata-containers/configuration.toml
21:55:25 INFO: Checking runtime spans
21:55:28 INFO: Checking Jaeger status (and logging traces to /var/log/kata-tests/logs/traces/kata-runtime-traces.json)
21:55:28 Failed at 171: status=$(get_jaeger_status "$service")
21:55:30 jaeger
21:55:31 jaeger
21:55:31 INFO: Disabling kata tracing on /usr/share/defaults/kata-containers/configuration.toml
21:55:31 make: *** [Makefile:177: tracing] Error 56
```

@nitkon - Power8 looks to have some package clash issue :-(

```
moreutils is already the newest version (0.63-1).
You might want to run 'apt --fix-broken install' to correct these.
The following packages have unmet dependencies:
 console-setup : Depends: keyboard-configuration (= 1.108ubuntu15.4) but 1.193 is to be installed
 console-setup-linux : Depends: keyboard-configuration (= 1.108ubuntu15.4) but 1.193 is to be installed
 e2fsprogs : PreDepends: e2fslibs (= 1.42.13-1ubuntu1)
 libdpkg-perl : Depends: dpkg (>= 1.18.11) but 1.18.4ubuntu1.5 is to be installed
E: Unmet dependencies. Try 'apt --fix-broken install' with no packages (or specify a solution).
Failed at 16: sudo -E apt -y install moreutils
Build step 'Execute shell' marked build as failure
```

**Comment by jcvenegas** [comment]
rebuild per Gaby suggestion, waiting for the CI ready.

**Comment by chavafg** [comment]
@egernst debian job passed and we know that Power8 job is currently broken, so I think we are fine merging this.

**Pull request merged**
