### PR TITLE
[test] crio: Run the integration tests also for shimv2

### PR DESCRIPTION
**Pull request by fidencio**
Depends-on: https://github.com/kata-containers/ci/pull/324
Fixes: #0

Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>

### CODE REVIEW

**Comment by fidencio** [comment]
Hmm. The tests were run only with `kata-runtime`. It seems like the change on https://github.com/kata-containers/ci/pull/324 was completely ignored.

@chavafg, @GabyCT, @jodh-intel, am I doing something completely wrong or is there some trick to check whether the ci changes are valid before merging them?

**Comment by GabyCT** [comment]
@fidencio did you modify directly the jenkins job? if not that is possible why is still failing

**Comment by fidencio** [comment]
> @fidencio did you modify directly the jenkins job? if not that is possible why is still failing

@GabyCT, I've modified the jenkins job as part of https://github.com/kata-containers/ci/pull/324
Theoretically this PR depends on that one, is this enough?

**Comment by GabyCT** [comment]
@fidencio no, you need to do it directly here http://jenkins.katacontainers.io/

**Comment by fidencio** [comment]
As this PR is marked as `do-not-merge`, we're assuming it won't make for the final 1.13.0 release, thus we're closing it.
In case you feel this has been wrongly closed, please, feel free to re-open it.

**Pull request closed without merging**
