### PR TITLE
DNM: clh: debug ci

### PR DESCRIPTION
**Pull request by jcvenegas**
debug ci by printing agent logs in stdout

Fixes: #666

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
@jcvenegas - can we zap this PR now?

**Comment by likebreath** [comment]
@jodh-Intel we are locating the issue and should wrap up this week. So let’s keep this debug PR for another few days.

**Pull request closed without merging**
