### PR TITLE
Backports for 1.8

### PR DESCRIPTION
**Pull request by egernst**
The following fixes landed on master since RC0 and should be included:

c192343c virtiofs: Allow memory hotplug with virtiofs
0a18fba3 runtime: Disable disable-modern for virtio QMP add
0d7b9819 vendor: update govmm and match code
c980da47 test: Fix fd leak causing test error
5628825a shimv2: Add missing page size to Hugetlb Stat

qemu: use x-ignore-shared to implement vm template

### CODE REVIEW

**Comment by jcvenegas** [comment]
```
+ echo 'init vm template'
init vm template
+ sudo -E PATH=/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR-initrd/go/bin:/usr/local/go/bin:/usr/sbin:/sbin:/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR-initrd/go/bin:/usr/local/go/bin:/usr/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games /usr/local/bin/kata-runtime factory init
QMP command failed: Invalid parameter 'bypass-shared-memory'
Makefile:150: recipe for target 'vm-factory' failed
make: *** [vm-factory] Error 1
Failed at 40: sudo -E PATH="$PATH" bash -c "make test"
Build step 'Execute shell' marked build as failure
Performing Post build task...
Match found for :.* : True
Logical operation result is TRUE
Running script  : #!/bin/bash
```

**Comment by egernst** [comment]
@ganeshmaharaj PTAL @ https://github.com/kata-containers/runtime/pull/1882#issuecomment-512353678

**Comment by egernst** [comment]
@chavafg @GabyCT are either of these familiar?

From fedora:
```
13:50:19 • Failure [22.480 seconds]
13:50:19 state
13:50:19 /tmp/jenkins/workspace/kata-containers-runtime-fedora-PR/go/src/github.com/kata-containers/tests/functional/state_test.go:26
13:50:19   container
13:50:19   /tmp/jenkins/workspace/kata-containers-runtime-fedora-PR/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table.go:92
13:50:19     with workload [true], timeWait 5 [It]
13:50:19     /tmp/jenkins/workspace/kata-containers-runtime-fedora-PR/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46
13:50:19 
13:50:19     Expected
13:50:19         <int>: 1
13:50:19     to equal
13:50:19         <int>: 0
13:50:19 
13:50:19     /tmp/jenkins/workspace/kata-containers-runtime-fedora-PR/go/src/github.com/kata-containers/tests/functional/state_test.go:45
13:50:19 ------------------------------
13:50:19 SSSSSSS
13:50:19 
13:50:19 Summarizing 1 Failure:
13:50:19 
13:50:19 [Fail] state container [It] with workload [true], timeWait 5 
13:50:19 /tmp/jenkins/workspace/kata-containers-runtime-fedora-PR/go/src/github.com/kata-containers/tests/functional/state_test.go:45
13:50:19 
13:50:19 Ran 1 of 8 Specs in 22.480 seconds
13:50:19 FAIL! -- 0 Passed | 1 Failed | 0 Pending | 7 Skipped --- FAIL: TestFunctional (22.48s)
13:50:19 FAIL
```

From vsock:
```
curl: (7) Failed to connect to 10.107.205.234 port 8080: Connection timed out
# service "my-service" deleted
# deployment.extensions "hello-world" deleted
Failed at 60: bats k8s-expose-ip.bats
Makefile:118: recipe for target 'kubernetes' failed
```
```

**Pull request merged**
