### PR TITLE
agent: Revert client protocol patch to fix CH and FC

### LINKED ISSUE #666: Add support for s390x
This issue will track Z support for Kata.

### PR DESCRIPTION
**Pull request by sboeuf**
DEBUG

Fixes #666

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
ouch, this is not running CI at all:
```
11:46:02 INFO: Checking for any changed files that will prevent CI fastpath return
11:46:02 INFO: No files found
11:46:02 INFO: Checking labels for PR kata-containers/runtime/2403
11:46:02 /tmp/jenkins/workspace/kata-containers-runtime-ubuntu-1804-PR-cloud-hypervisor/go/src/github.com/kata-containers/tests/.ci/ci-fast-return.sh: line 243: jq: command not found
11:46:02 INFO: No forcing label found
11:46:02 Short circuit fast path skipping the rest of the CI.
```

are we skipping CI when only vendoring is changed?
/cc @grahamwhaley

**Comment by sboeuf** [comment]
@chavafg yeah I noticed... I thought it was skipping CI because the travis check didn't pass.

**Comment by grahamwhaley** [comment]
hmm, I don't think so. The YAML file that defines what to skip and what to hard-check is over at:

https://github.com/kata-containers/tests/blob/master/.ci/ci-fast-return.yaml

it doesn't mention vendor... let me have a brief stare at the CI logs..

**Comment by grahamwhaley** [comment]
ah, but, we use a lib func to get the list of PR changed files - and I think it strips vendor out...
https://github.com/kata-containers/tests/blob/master/.ci/lib.sh#L429

maybe we want to re-consider that...

**Comment by chavafg** [comment]
thanks for the answer @grahamwhaley, yeah, I think we need to reconsider that. Will open an issue/

**Pull request closed without merging**
