### PR TITLE
versions: Update cloud-hypervisor to release v0.12.0

### PR DESCRIPTION
**Pull request by likebreath**
Highlights for cloud-hypervisor version v0.12.0 include: removal of
`vhost-user-net` and `vhost-user-block` self spawning, migration of
`vhost-user-fs` backend, ARM64 enhancements with full support of
`--watchdog` for rebooting, and enhanced `info` HTTP API to include the
details of devices used by the VM including VFIO devices.

Fixes: #3123

Signed-off-by: Bo Chen <chen.bo@intel.com>

### CODE REVIEW

**Review by devimc — APPROVED** [review]
thanks @likebreath

**Review by egernst — APPROVED** [review]
Looks good -- thanks.

**Pull request merged**
