### PR TITLE
DNM: Revert "drivers: Correct isPCIeDevice logic"

### PR DESCRIPTION
**Pull request by GabyCT**
This reverts commit 6bf93b23159e3f8eab62e9c2fc26ed9946a818e9.

### CODE REVIEW

**Comment by dgibson** [comment]
Um.. why?

**Comment by jodh-intel** [comment]
Yes, @GabyCT - please add some details for this PR.

**Comment by devimc** [comment]
@dgibson @jodh-intel  she is trying to identify which PR introduced the metrics regression

**Comment by GabyCT** [comment]
sorry for the confusion @dgibson and @jodh-intel but as @devimc I am trying to see which PR caused that metrics started to failed...I will be opening a number of reverts to see if I can find it

**Comment by dgibson** [comment]
Understood, thanks.  I didn't realize until after I posted that "DNM" probably meant "Do Not Merge", which didn't help my reaction :).

**Pull request closed without merging**
