### PR TITLE
Revert shimv2, vendor commits

### PR DESCRIPTION
**Pull request by egernst**
This reverts:
 - 590ed09 vendor: update gogo/protobuf, containerd and agent vendors
 - eabfd99 shimv2: Improve shim shutdown logic

These introduce a regression for starting pods with k8s 1.14 + containerd
1.2.6

Fixes: #1781

Signed-off-by: Eric Ernst <eric.ernst@intel.com>

### CODE REVIEW

**Comment by gnawux** [comment]
ask @lifupan for confirming it

**Comment by lifupan** [comment]
@gnawux @egernst ,  the root cause was that the latest containerd used ttrpc to publish event from shimv2 to containerd, and it depended on the pull https://github.com/containerd/containerd/pull/3195  to support this feature.

**Comment by egernst** [comment]
What’s your recommendation @lifupan ?

**Comment by lifupan** [comment]
> What’s your recommendation @lifupan ?

Hi @egernst ,  since the latest containerd stable release(v1.2.6) hasn't integrated that PR https://github.com/containerd/containerd/pull/3195, for Kata's stable release, I think we can revert those two corresponding patches for shimv2 to compatible with the stable released containerd; 
Since the breaks of compatibility was bring by shim's framework, was it better for us to complain to containerd community to make the change compatible backward, otherwise, there would be issue for cri-o to communicate with kata shimv2 as show in https://github.com/kata-containers/tests/issues/1624 .

**Pull request merged**
