### PR TITLE
qemu: add disable_image_nvdimm option

### PR DESCRIPTION
**Pull request by bergwolf**
To control whether an image rootfs is used as nvdimm device or just plain virtio-block device.

### CODE REVIEW

**Comment by Pennyzct** [comment]
Hi~ @bergwolf 
If we're using `virtio-blk` as backend with qemu, then we may not support launching more than one containers simultaneously. It will incur `write lock` error. 
We have addressed this scenario in issue [#843](https://github.com/kata-containers/runtime/issues/843).

**Comment by bergwolf** [comment]
@Pennyzct The `virtio-block` drive has `ShareRW` bit set so that the image can be shared among multiple qemu instances. Also it is mounted readonly so no write will incur on the guest rootfs image.

**Comment by Pennyzct** [comment]
@bergwolf thanks for the explanation. ;)

**Pull request merged**
