### PR TITLE
Stable 1.1.1 candidate

### PR DESCRIPTION
**Pull request by egernst**
Walked through patches between 1.1.0 to HEAD, 8bbd9b5 , searching for changes which are candidates for a 1.1.x stable release. 

All changes applied were non-conflicting cherry-picks.  

Bugs from new features as well as new features or vendoring changes were rejected for stable.

Summary of changes/decisions made given below (for each commit between 1.1.0 and HEAD):

NO -  * |   e35caa6 Merge pull request #553 from chavafg/topic/update-openshift-version
>>| * | 4fc3041 versions: update openshift to 3.10.0

_^ don't want to update versions after making a stable unless there's an explicit fix we need_

NO * |   dec385a Merge pull request #548 from bergwolf/cleanup
>> | * | bd50761 qemu: create vm directory before launching qemu
>> | * | 568b65c qemu: remove redundant code

_^ Feature not relevant for 1.1.1_

NO * |   244917c Merge pull request #546 from bergwolf/status-factory
Feature not relevant for 1.1.1
>> | * | 024a38b cli: print to defaultOutputFile in factory.go
>> | * | 03f2459 cli: support factory status command

_^VM factory changes not part of 1.1.1_

NO * |   16600ef Merge pull request #531 from WeiZhang555/bugfix
>> | * | 44b9214 devices: fix typo
>> | * | f474af1 devices: add some test cases
>> | * | b746489 devices: address some comments
>> | * | 44c37bf devices: rename VFIODrive to VFIODev
>> | * | 7d9d66d devices: remove unused functions
>> | * | a93e2d0 unit-tests: fix unit tests
>> | * | f905c16 device-manager: refactor device manger
>> | * | eec7fa3 devices: don't use drivers package directly.
>> | * | 5db5f42 devices: remove interface VhostUserDevice
>> | * | 1194154 devices: use device manager to manage all devices

_^ refactoring which introduces risk - not a bug fix/security issue_

NO * | |   04fa125 Merge pull request #544 from lifupan/master
>> | * | | 1586018 virtcontainers: fix the issue of cleanup the vm's path

_^ factory not part of 1.1_

NO * | | |   c871a90 Merge pull request #539 from bergwolf/crng
>> | * | | 6156341 factory: reseed guest RNG device after resuming
>> | * | | d43a435 vendor: update agent dependency

_^ Factory not part of 1.1_

1.1.1 | * | | a8f5e2b (jodh/remove-initcall-debug-kernel-option) kernel: Remove initcall_debug boot option

1.1.1 | * | | | 476f21f codecov: remove codecov.yml

NO * | | | |   487f9ef Merge pull request #536 from bergwolf/qmp_clear
>> | * | | | 44a3a44 qemu: wait on disconnected channel in qmp shutdown
>> | * | | | c8b4fab qemu: clear qmp state before wait for qemu process

_^ Not a bug fix/security issue_

NO * | | |   1dae056 Merge pull request #524 from bergwolf/agent_log
>> | * | | b200163 kata_agent: send sandbox id in CreateSandbox request
>> | * | | e69ebe5 vendor: update agent grpc
>> | * | | 0541a5f cli: fix factory assignment

_^ Factory not a part of 1.1_

NO * | |   fc45d2e Merge pull request #497 from jcvenegas/vsock-runtime5
>> | * | | 3364379 virtcontainers: Use vsock if host support it
>> | * | | 3c15bc5 virtcontainers: remove parseVSOCKAddr function
>> | * | | 0527691 virtcontainers: implement function to cold plug vsocks
>> | * | | 1515bd0 virtcontainers: update KataAgentConfig to support vsocks
>> | * | | 3adc862 virtcontainers: log type of proxy started
>> | * | | 4680e58 cli: add configuration option to enable/disable vsocks
>> | * | | f389b94 kata-agent: Remove GRPCSock unused variable.
>> | * | | 9b28325 virtcontainers: Implement function to get a free context ID
>> | * | | 2339ac3 virtcontainers/utils: Implement function to check vsocks support
>> | * | | 8ae2888 vendor: update govmm

_^New feature, not part of 1.1_

NO * | |   17a2fb8 Merge pull request #528 from jodh-intel/fix-log-fields
>> | * | 763a1b6 (jodh/fix-log-fields) logging: Remove unnecessary fields and use standard names
>> | * | 3323c08 logging: Add cid logging to update command
>> | * | 3d5ed66 logging: Improve cid+sid logging
>> | * | 58448bb logging: Allow SetLogger to be called multiple times
>> | * | 029e7ca api: Change logger functions to accept a log entry
>> | * | dfb758a logging: Remove duplicate arch field in vc
>> | * | acdd0b8 logging: Split logging source into two fields
>> | * | c59394d network: Make better use of log fields
>> | * | a0be57f network: Always call network logger function

_^While "nice to have", this is changing an API, and modifies network code which was refactored since 1.1_

NO * |   f4a7712 Merge pull request #530 from kata-containers/revert-301-pre-addstorage-based-devmanager
>> | * | 927487c revert: "virtcontainers: support pre-add storage for frakti"

_^preadd storage Not part of 1.1_

NO * |   cfbc974 Merge pull request #521 from bergwolf/log
>> | * | 9a497fe factory: add SetLogger API

_^factory not part of 1.1_

NO * | |   2c3215c Merge pull request #301 from WeiZhang555/pre-addstorage-based-devmanager
>> | * | | b3015dd devices: fix typo
>> | * | | 198a069 devices: add some test cases
>> | * | | 8391b20 devices: address some comments
>> | * | | 04f4f52 devices: rename VFIODrive to VFIODev
>> | * | | daf5abc devices: remove unused functions
>> | * | | 1b062b3 unit-tests: fix unit tests
>> | * | | 7f5989f device-manager: refactor device manger
>> | * | | c08a263 devices: don't use drivers package directly.
>> | * | | b54df7e devices: remove interface VhostUserDevice
>> | * | | 2885eb0 devices: use device manager to manage all devices

_^refactoring which isn't a bug fix nor security issue_

NO * | | |   2a670ce Merge pull request #522 from chavafg/topic/update-docker-version
>> | * | | | da77124 versions: Update docker-ce to 18.06

_^ don't want to update versions after making a stable unless there's an explicit fix we need_

1.1.1 | * | | | 5fc7219 agent: check: Increase timeout check request.
1.1.1 | * | | | 12e1911 kata-agent: Improve error message.

1.1.1 | * | | 4326ea8 cli: add AMD support to kata-check

1.1.1 | * | | 0e5f6b2 codecov: Explicitly disable codecov/patch coverage

1.1.1  | * | | c6fda44 virtconainers: rollback the NetNs when createNetwork failed

1.1.1 | * | | f9d5072 sandbox: change container slice to a map

1.1.1  | * | | 2993cb3 virtcontainers: fix kata-agent fail to start
1.1.1 | * | | 7103c4f virtcontainers: add qemu process rollback
1.1.1 | * | | c2651a8 virtcontainers: add kata-proxy rollback
1.1.1 | * | | daebbd1 virtcontainers: add rollback to remove sandbox network

NO * | |   99954d5 Merge pull request #501 from bergwolf/qemu
>> | * | d69fbcf sandbox: add stateful sandbox config
>> | * | 7a6f205 virtcontainers: keep qmp connection when possible
>> | * | c9bd12a qemu: cleanup qmp channel setup and teardown

_^ wasn't completely clear, but think this is just enabling for vm factory, not a bug fix/security issue_

NO * |   b244410 Merge pull request #505 from bergwolf/create_factory
>>| * | 4656a72 cli: create vm factory if failed to load existing one

1.1.1 | * 50b445c cli: tests: Clarify who cleans up tmpdir
1.1.1 | * 73c8286 cli: tests: remove the tmpdir to the config.json
1.1.1 | * d6d38da cli: update_test: defer remove tmpfile

NO *   14d25b8 Merge pull request #303 from bergwolf/vmfactory
>> | * 0a11230 factory: add UTs
>> | * 7cdc0fe cli: do not set ip based kernel parameter
>> | * 0309e59 cli: add vm factory management subcommand
>> | * a7d888f virtconainers: add SetFactory API
>> | * bdd5c66 virtcontainers: add vm factory support
>> | * 8dda2dd virtcontainers: add a vm abstraction layer
>> | * 28b6104 qemu: prepare for vm templating support
>> | * 057214f agent: prepare for vm factory
>> | * 7f20dd8 hypervisor: cleanup valid method
>> | * 18e6a6e hypervisor: decouple hypervisor from sandbox
>> | * 4ac6754 qemu: remove append9PVolumes

_^factory not part of 1.1_

1.1.1 | * 5d6da35 kata_agent: print request details

NO * |   81c073f Merge pull request #458 from harche/without_devices
>> | * | b821a5d virtcontainers: Add support for ephemeral volumes

_^new feature - not part of 1.1_

1.1.1 | * c72a720 makefile: update PREFIX to remove redundant slash

1.1.1 | * bd6db30 kata-env: tests: add JSON out/in verify test
1.1.1 | * e45f591 kata-env: Do not leave temp files on test
1.1.1 | * 1f8f762 kata-env: Fix test cases for kata-env JSON
1.1.1 | * 63c06be kata-env: Add ability to output as JSON

NO * |   02056b6 Merge pull request #482 from chavafg/topic/update-cri-o
>> | * | bb0bab2 versions: Update CRI-O supported version

_^ don't want to update versions after making a stable unless there's an explicit fix we need_

1.1.1 031632d ci: no-exit: Do not run no-exit check on test files
1.1.1 62495d4 ci: no-exit: Allow path override for os.Exit check
1.1.1 6268ba4 ci: no-exit: Skip check if no files to check
1.1.1 1c453a3 ci: no-exit: Document and echo what the check is

1.1.1 | * | 114482e api: To stop its monitor after a sandbox paused

1.1.1 | * | d0bccab virtcontainers: Set ppc64le maxmem depending on qemu version

1.1.1 | * | a38b251 (jodh/pass-sandbox-to-proxy) tests: Refactor CC proxy test for Kata
NO:
>> 1.1.1 | * | 23eb13f proxy: Pass sandbox to proxy

_^ changing compat_

NO: * |   a8952fb Merge pull request #470 from bergwolf/memory-hotplug
>> | * | 66a3e81 hypervisor/qemu: add memory hotplug support
>> | * | 0646a39 vendor: fix dep warning and update yamux dependency
>> | * | 0f20b6b vendor: update govmm changes

_^ New feature_

1.1.1 | * | 67de5d4 ci: reconstructure image-type and initrd for architecture-independant

1.1.1    830d50e (jodh/add-runtime-cli-cmd-to-vc-log) main: Pass runtime CLI command to vc logger

NO:
>>  - follow up       793a220 (jodh/pass-sandbox-id-to-agent) qemu: Pass sandboxID to agent for logging purposes

_^ changing compat_

1.1.1  64e2ca3 (jodh/improve-cid+sid-logging) logging: Reset external loggers when cid+sid available
1.1.1 03d4d49 logging: Add function to handle external loggers
1.1.1 79e8da0 create: Remove redundant logging code

1.1.1 9155412 api: To watch the vm console in FetchSandbox api

### CODE REVIEW

**Comment by egernst** [comment]
@jcvenegas PTAL

All - going forward we shouldn't need a PR via cherry-picks, this is just to start the bootstrap of the stable branches.  Not sure if our CI will have issues with pre-existing Fixes?

**Comment by egernst** [comment]
@nitkon @Pennyzct @lifupan @sboeuf @jcvenegas @jodh-intel @bergwolf @grahamwhaley @amshinde  PTAL and ACK, as I am taking your prior commits/PRs to create this stable branch.

**Comment by grahamwhaley** [comment]
Nice job @egernst - this looks like a real brainache, so yes, glad we only have to do this once.
Given this is a one-shot thing, I believe we are/can/have relaxed the strict `bug fix and security fix only` rules - which, is fine by me this time, as long as none of the small feature items that sneak in break anything (but we are going to run the testsuites, so we should spot any major breakage).

Given that, I think it might be prudent for folks to scan the `NO` entries with priority, and see if there is anything excluded that we think should be included. With that in mind, can I query these:

```
NO * | |   cd133dc Merge pull request #509 from lifupan/kata-integration
 | * | | c6fda44 virtconainers: rollback the NetNs when createNetwork failed
```
From that summary line that feels like a bugfix.

```
NO * | |   8939fd8 Merge pull request #351 from woshijpf/fix-no-kata-agent
 | * | | 2993cb3 virtcontainers: fix kata-agent fail to start
 | * | | 7103c4f virtcontainers: add qemu process rollback
 | * | | c2651a8 virtcontainers: add kata-proxy rollback
 | * | | daebbd1 virtcontainers: add rollback to remove sandbox network
```
Similarly, those look on the surface like bug fixes.

Eric, do you still have details of those in your head? If not, we can go read up on them to check.

-------------
> SIDENOTE

/me wonders if we ever have to do this in the future (and I hope not ;-) ), if we can format the list with github tickbox stylies... with a little bit of sedding I reckon we could get to something like:

- [ ] | |   8939fd8 Merge pull request #351 from woshijpf/fix-no-kata-agent
    - [ ] | 2993cb3 virtcontainers: fix kata-agent fail to start
    - [ ] | 7103c4f virtcontainers: add qemu process rollback
    - [ ] | c2651a8 virtcontainers: add kata-proxy rollback
    - [ ] | daebbd1 virtcontainers: add rollback to remove sandbox network
- [x] | a8f5e2b (jodh/remove-initcall-debug-kernel-option) kernel: Remove initcall_debug boot option

which might be easier to eyball-parse. Oh, and an added bonus, it appears to hot-link the SHA's!

---------------

**Comment by egernst** [comment]
@grahamwhaley @jodh-intel 

re: formatting: good idea -- I wasn't think of mark down - I was editing a snipped of git log --oneline --decorate --graph as I stepped through.  I'll update the original paste for my rationale...

**Comment by egernst** [comment]
- [] 1.1.1 | * c72a720 makefile: update PREFIX to remove redundant slash
- [ ] 1.1.1 9155412 api: To watch the vm console in FetchSandbox api

**Comment by egernst** [comment]
I added some notes above.  @grahamwhaley I ended up pulling in the roll back.  I was hesitant at first as there were a couple of conflicts introduced, but these were easily resolvable.  Agreed.

@jodh-intel, regarding ```NO * |   dec385a Merge pull request #548 from bergwolf/cleanup```
This is setup for cleaning up some handling which was introduced in a prior PR, 99954d5.  I honestly wasn't 100% on this one, as its adding a new statesful flag for sandboxes.  While we are just offering this new functionality and not a consumer of it, I am uncertain if that original change was a good candidate.

@bergwolf  - can you please weigh in?

**Comment by bergwolf** [comment]
@egernst I don't think https://github.com/kata-containers/runtime/commit/99954d50257760929b6d72bfa628dadb6ea96394 is a good candidate for stable. It was added as an optimization. So please exclude it along with #548

**Comment by bergwolf** [comment]
@egernst According to the guideline we have agreed upon
> 1. Only bug and security fixes which do not introduce inter-component dependencies are candidates for the stable branch

I don't think we should include tests/logging related commits in stable. Code cleanups and New features should be excluded as well. If we follow this rule, it will cut down your current list quite a lot.

**Comment by WeiZhang555** [comment]
Why not "tests/logging" ? I think it doesn't hurt anything. @bergwolf

**Comment by bergwolf** [comment]
@WeiZhang555 I was echoing the guideline in the [gdoc](https://docs.google.com/document/d/18R8Ckl20PIP5FeC81faNEhbcX7ydgsCTHPlwogrhPAs/edit?ts=5b7d1b51#heading=h.7am6s5s7xwqa). I agree it's good to have tests and logging there. But it needs to be mentioned in the gdoc as well so that everyone is on the same page. The current statement there says that we only want minimal changes to the stable.

Also by logging, I would restrict it as adding a few lines of new logs. For larger changes like the opentracing support @jodh-intel is currently working on, and any logging changes that require cross-component upgrades in order to work, should be excluded IMO.

Looking closer, this one `1.1.1 | * | 23eb13f proxy: Pass sandbox to proxy` is actually breaking command line compatibility between kata-runtime and kata-proxy. So even if it improves logging, it should not be considered in stable.

Similar is `1.1.1 - follow up 793a220 (jodh/pass-sandbox-id-to-agent) qemu: Pass sandboxID to agent for logging purposes`, -- it cannot work unless we include the counter part of the change in kata-agent.

Also there are several code cleanups listed in the PR and we should decide if they are suitable for stable as well.

**Comment by bergwolf** [comment]
Speaking of the guidelines, @egernst would you please add the branching and stable maintenance guidelines in your gdoc to the kata documentation repo? Since we are starting to practicing it, it's better to make it a formal document :)

**Comment by jodh-intel** [comment]
@bergwolf - good point!

@egernst - could you add the doc as a `.md` file please?

**Comment by egernst** [comment]
@bergwolf agreed - I'll remove the ones you cited.

@bergwolf @jodh-intel  - opened https://github.com/kata-containers/documentation/issues/231

**Comment by egernst** [comment]
Repushed with problematic commits removed - thanks @bergwolf.  Since we now have a stable release (which is just 1.1.0), I was able to verify with the initial stable packages as well.

I'll work on clarifying the backport candidates as we move from gdoc to .md.  I think that we should allow for low-risk changes which enhance debug / usability, especially at this point.  Definitely not higher risk / larger changes though, which creep towards really being features (like opentracing).  WDYT?  We can continue the discussion on the document PR...

**Comment by bergwolf** [comment]
@egernst Thanks for the update.
LGTM!

**Comment by jodh-intel** [comment]
Thanks for adding the explanations @egernst!

lgtm

**Comment by chavafg** [comment]
I still see some license headers issues:

```
INFO: Checking for SPDX license headers
ERROR: Required license identifier ('SPDX-License-Identifier: Apache-2.0') missing from following files:

virtcontainers/pkg/cni/OWNERS

```

**Comment by jcvenegas** [comment]
@chavafg the file header is correct, I think is an issue with the CI script.

**Comment by chavafg** [comment]
https://github.com/kata-containers/tests/pull/652 should fix the issue.

**Comment by jcvenegas** [comment]
CI was not stable with CRI-O tests on 1.1 lets merge this PR.

**Pull request merged**
