### PR TITLE
[stable-1.12] Backport #3005

### PR DESCRIPTION
**Pull request by fidencio**
Would be good to get this one merged for the 1.12.0 release.

It's been merged Yesterday, and as Today is a Holiday in ~~Cambodia~~ France I'm doing the backport of @c3d series.

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @fidencio.

**Comment by fidencio** [comment]
@jodh-intel, the patches in the series makes a reference to #3005, which was not found by the "Move issues to "In progress" in backlog ..."
```
Run pr=3060
{}Moved issue 2943 to column In progress in project org 'Issue backlog'
{}Moved issue 3004 to column In progress in project org 'Issue backlog'
cannot determine project fields for issue 3005 in project Issue backlog
issue 3005 not in project (add it first)
Error: Process completed with exit code 1.
```

Does it mean that I'll have to create a new issue (I did already), and force push the mention to the new issues in the last commit of the series?

**Comment by fidencio** [comment]
- **jenkins-ci-podman-clh-fedora-31**:
```
10:41:30 HEAD is now at 6d30fe05 vmm: openapi: Add the 'iommu' and 'id' option to 'VmAddDevice'
10:41:30 ./scripts/dev_cli.sh: line 122: docker: command not found
``` 

It's a known failure, already tracked at: https://github.com/kata-containers/ci/issues/340

**Review by amshinde — APPROVED** [review]

**Pull request merged**
