### PR TITLE
test: [DNM] kernel fragments support

### PR DESCRIPTION
**Pull request by devimc**
Depends-on: github.com/kata-containers/packaging#646

Fixes: #1234567

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by devimc** [comment]
@grahamwhaley @ganeshmaharaj @egernst  FC CI is happy :smile:  . Next step is to check SRIOV / VFIO

**Comment by grahamwhaley** [comment]
nice @devimc - thanks!
metrics unhappiness is understood - suspect I need to update a PR for that:
```
21:52:08 .ci/jenkins_job_build.sh: line 167: .ci/run_metrics_PR_ci.sh: No such file or directory
```

**Pull request closed without merging**
