### PR TITLE
vc: Sandbox#getAndSetSandboxBlockIndex shouldn't alter BlockIndex in case of error

### LINKED ISSUE #2244: Sandbox#getAndSetSandboxBlockIndex shouldn't alter BlockIndex in case of error
# Description of problem

Currently Sandbox#getAndSetSandboxBlockIndex increments BlockIndex up front.
Later on if store.Store() returns error, the index increment is left behind.

# Expected result

BlockIndex should not increment in case of error.

Similar issue applies to decrementSandboxBlockIndex where the symptom may be more severe - in worst case, the block index may become negative.

# Actual result

### PR DESCRIPTION
**Pull request by tedyu**
Fixes #2244

Signed-off-by: Ted Yu yuzhihong@gmail.com

### CODE REVIEW

**Comment by egernst** [comment]
thanks @tedyu

**Comment by tedyu** [comment]
@jodh-intel 
Can you re-trigger jenkins-ci-ARM-ubuntu-18-04 test ?

Thanks

**Comment by tedyu** [comment]
@jodh-intel @egernst 
Can you re-trigger jenkins-ci-ARM-ubuntu-18-04 test ?

Thanks

**Comment by tedyu** [comment]
@grahamwhaley 
Can you re-trigger jenkins-ci-ARM-ubuntu-18-04 test ?

Thanks

**Comment by grahamwhaley** [comment]
@tedyu - did you read the CI failure log? I see:

```
20:17:38 Found 1 commit between commit 3044cd45bedc7e8bde68d85bbe070573a6213714 and branch stable-1.9
20:17:38 ERROR: Commit 3044cd45bedc7e8bde68d85bbe070573a6213714: subject too long (max 75, got 82): "vc: Sandbox#getAndSetSandboxBlockIndex shouldn't alter BlockIndex in case of error"
20:17:38 ERROR: checkcommits failed. See the document below for help on formatting
20:17:38 commits for the project.
```

So, let's check with @Pennyzct if this is a known, or fixed, ARM related error.... before we re-spin the CI.

**Comment by tedyu** [comment]
@grahamwhaley 
The error message you referred to was about length of commit subject.

The same fix has been applied to master branch.

In my opinion, the commit subject can stay as it is. I will pay attention to future commit subjects.

Thanks

**Comment by jodh-intel** [comment]
@tedyu - I hadn't noticed this issue in `master` but I agree with @grahamwhaley: we want every commit to be "well formed" which for this project means a simple and brief summary line (with subsystem tag at the start) and an actual body to the commit. This can be as long as is necessary to explain what the commit is doing and why.

I'd write the commit something like this:

```
virtcontainers: Don't adjust block index on error

Fixed `Sandbox::getAndSetSandboxBlockIndex() so that
it does not update `BlockIndex` if an error occurs.

...
```

**Comment by tedyu** [comment]
Thanks for the reminder, @jodh-intel 

I have created #2293 to comply with your suggestion (I lost the original repo a few days ago).

**Pull request closed without merging**
