### PR TITLE
spell check

### LINKED ISSUE #2144: There's a spelling mistake
# Description of problem
In the README.md there's a spelling mistake in the 'Note' in 'Configuration Section'
'special' is spelled as 'specialist'

### PR DESCRIPTION
**Pull request by csor-dev**
readme: fix spell check
Corrects the spelling mistake in the Note in Configuration Section of main README.md file
fixes #2144

Signed-off-by: Yeshwanth Reddy <gophernani@gmail.com>

### CODE REVIEW

**Comment by devimc** [comment]
@csor-dev thanks for raising this, 
* please add a body in your commit message
* file an issue and add `fixes #XXX` in your commit message

**Comment by csor-dev** [comment]
Just followed your steps
Thanks @devimc

**Comment by devimc** [comment]
@csor-dev CI still failing , please a subsystem in the subject, i.e `readme: fix spell check`

```
ERROR: Commit e61dffacd48f57bb5b3a0a89970a4b4d0d2279a0: Failed to find subsystem in subject: "spell check"
```

**Comment by chavafg** [comment]
@csor-dev please amend your commit locally and re-push with the changes. It is not enough to edit the PR description.
The following should work: 

1. use `git commit --amend`
2. Fix your commit message
3. use `git push -f` to re-push your changes

**Comment by raravena80** [comment]
@csor-dev any update on this PR? Thx!

**Comment by raravena80** [comment]
@csor-dev any updates?

Your weekly Kata herder.

**Comment by grahamwhaley** [comment]
Replaced with #2414 - hence, on the next round of gateherding, we'll likely close this PR. Thanks for your contribution @csor-dev

**Comment by amshinde** [comment]
Closing this in favor of #2414

**Pull request closed without merging**
