### PR TITLE
improve robustness w.r.t. dead hypervisor

### PR DESCRIPTION
**Pull request by bergwolf**
When hypervisor crashes or gets killed, we get into a very bad situation that we cannot recover properly even by stopping and deleting the container.

The PR handles the situation by:
1. allow to stop and delete a container even if hypervisor process is dead
2. use the sandbox monitor to monitor agent and hypervisor liveness

### CODE REVIEW

**Comment by devimc** [comment]
/test

@bergwolf  thanks

**Comment by bergwolf** [comment]
/test

PS, SoB and WIP checks seem broken?

**Comment by grahamwhaley** [comment]
Looks like there has been a glitch on the (Zuul based) SoB and WIP checks, but may have since cleared:
https://zuul.opendev.org/t/kata-containers/builds?pipeline=SoB-check
I'll wiggle a label and see if the WIP one works now...

**Comment by bergwolf** [comment]
@grahamwhaley How do we restart SOB check?

**Comment by grahamwhaley** [comment]
@bergwolf - is detailed on the wiki page linked to from the status: https://github.com/kata-containers/community/wiki/The-SoB-check#this-looks-like-a-transient-failure-how-can-i-ask-the-tests-to-run-again-
;-)
/zuul-recheck
(thx, as I'd half forgotten and was going to look it up anyway...)

**Comment by bergwolf** [comment]
Working like a charm~ Thanks @grahamwhaley !

**Comment by devimc** [comment]
@bergwolf please rebase it

**Pull request merged**
