### PR TITLE
hypervisor cleanup

### PR DESCRIPTION
**Pull request by egernst**

### CODE REVIEW

**Comment by egernst** [comment]
@sboeuf @mcastelino @amshinde  - PTAL

**Comment by jodh-intel** [comment]
Hi @egernst - our static analysis scripts are saying what I was about to:

```
virtcontainers/capabilities.go:11:2:warning: const hotplugUnsupported is unused (U1000) (unused)
virtcontainers/capabilities.go:12:2:warning: const plan9FSUnsupported is unused (U1000) (unused)
virtcontainers/capabilities.go:41:27:warning: func (*capabilities).isHotplugSupported is unused (U1000) (unused)
virtcontainers/capabilities.go:48:27:warning: func (*capabilities).setHotplugUnsupported is unused (U1000) (unused)
virtcontainers/capabilities.go:52:27:warning: func (*capabilities).is9pSupported is unused (U1000) (unused)
virtcontainers/capabilities.go:59:27:warning: func (*capabilities).set9pUnsupported is unused (U1000) (unused)
```

Either we wait until these functions are actually needed, or how about reworking `virtcontainers/mock_hypervisor.go` as it seems reasonable for that  hypervisor to support neither hotplug nor 9p? That might merit a bit of light unit-test reworking possibly.

**Comment by devimc** [comment]
@egernst any update?, I need this change to copy file from host to guest

**Comment by devimc** [comment]
@egernst @jodh-intel  I'm including these patches here https://github.com/kata-containers/runtime/pull/1041

**Pull request closed without merging**
