### PR TITLE
re-add: refactor device manager

### LINKED ISSUE #50: virtcontainers: Implement Storage hotplug API
To help optimize the container boot process, virtcontainers needs to support hotplugging of storage and network devices.  We need to define and implement an API for attaching NICs and storage endpoints to a Pod/Sandbox, such as:
```go
func AddStorage(podID string) error {
        ...
}


AND/OR

func (p VCPod) AddStorage() error {
        ...
}
```

let's use this issue to define the API for storage  hotplug.  This should be closed once we have the design documented and implementation merged.

### LINKED ISSUE #529: After running K8s tests processes are left behind
After running K8s tests processes like shim are left behind

```
$ pgrep -a -f /usr/libexec/kata-containers/kata-shim
1848 /usr/libexec/kata-containers/kata-shim -agent unix:///run/vc/sbs/98264dde03f2f9b9a1cec51adc5a80b47a23b819b9dece9f61fe624d2b66149a/proxy.sock -container 98264dde03f2f9b9a1cec51adc5a80b47a23b819b9dece9f61fe624d2b66149a -exec-id 98264dde03f2f9b9a1cec51adc5a80b47a23b819b9dece9f61fe624d2b66149a -log debug
27893 /usr/libexec/kata-containers/kata-shim -agent unix:///run/vc/sbs/b8873ddaef5b0072f2632be77749a2f6306bdc322ec89a35112b3d14ca72bb15/proxy.sock -container b8873ddaef5b0072f2632be77749a2f6306bdc322ec89a35112b3d14ca72bb15 -exec-id b8873ddaef5b0072f2632be77749a2f6306bdc322ec89a35112b3d14ca72bb15 -log debug
27966 /usr/libexec/kata-containers/kata-shim -agent unix:///run/vc/sbs/b8873ddaef5b0072f2632be77749a2f6306bdc322ec89a35112b3d14ca72bb15/proxy.sock -container 06ae4e2e246ccc4a82fe842c287a33bb8f98c7d0e7aa97054d8194e8afa0c82c -exec-id 06ae4e2e246ccc4a82fe842c287a33bb8f98c7d0e7aa97054d8194e8afa0c82c -log debug
28050 /usr/libexec/kata-containers/kata-shim -agent unix:///run/vc/sbs/b8873ddaef5b0072f2632be77749a2f6306bdc322ec89a35112b3d14ca72bb15/proxy.sock -container b362b6b83d66e179978591ed035868cab43ed9f64f57b5c37890463575d14532 -exec-id b362b6b83d66e179978591ed035868cab43ed9f64f57b5c37890463575d14532 -log debug
28132 /usr/libexec/kata-containers/kata-shim -agent unix:///run/vc/sbs/b8873ddaef5b0072f2632be77749a2f6306bdc322ec89a35112b3d14ca72bb15/proxy.sock -container 884e0a2db39f255494da117d7d8eb3c40923f49aa25f1265845f3e9243bfdeda -exec-id 884e0a2db39f255494da117d7d8eb3c40923f49aa25f1265845f3e9243bfdeda -log debug
```
Here it is the configuration that I am using
kata-runtime  : 1.1.0
commit   : cfbc974fec1d04ec7d799eac11f3bee99ab8e477
OCI specs: 1.0.1
kata-proxy version 1.1.0-c416c9fc2ff8389c201075f0f26bfabd08a3b140
kata-shim version 1.1.0-6ddca0334d0e8dee6e1e00f0c120fde4b8c1c176
kata-agent version 1.1.0-c6ac153f0c4c03b475d2b65bb73427cd33459bf7

That is causing that the `swarm` tests are failing as they are detecting that processes were left behind (https://github.com/kata-containers/agent/pull/309)

### PR DESCRIPTION
**Pull request by WeiZhang555**
Fixes #50
Fixes #529
    
Test case:
```
Terminal 1:
$ docker run -ti -v /tmp/a/hello:/hello --runtime kata busybox sh
/

Terminal 2:
$ rm -fv /tmp/a/hello

Terminal 1: exit the container
/ exit
```

We can observe that there's proxy and shim left.

To fix this bug, we need to ignore "path not exist" error for volume
source, and go on to next step.

Signed-off-by: Wei Zhang <zhangwei555@huawei.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
@WeiZhang555 thanks for working on a fix regarding the issue that have been introduced through your initial PR about storage. Please let us know when this is ready to be reviewed ;)

**Comment by sboeuf** [comment]
@WeiZhang555 just one thing on the top of my head. It'd be great if you could reintroduce the whole PR with the commits, instead of just having two commits. Or even better, if the fix is part of the code you've introduced, I don't think we should introduce a special commit for it, it should be part of the modified PR.
I don't know other ppl opinions on that though? @egernst @bergwolf @amshinde @grahamwhaley @jodh-intel ?

**Comment by WeiZhang555** [comment]
@sboeuf Either way is good to me, commit 1 is exactly the same with initial PR, so I'm not sure if it's worth another split.

CI is on vacation, waiting its return...

**Comment by jodh-intel** [comment]
+1 to re-add the original commits, with the bug-fix changes added of course ;) This PR only has 2 commits whereas the original #301 had 10 so in terms of understanding the code, it would be much better to have those 10 back.

@WeiZhang555 - can we add a new test in the tests repo to ensure we don't leave processes around? As I type this, I've just remembered https://github.com/kata-containers/tests/issues/195 which I'm assuming would have caught this issue.

**Comment by WeiZhang555** [comment]
I will do that, need CI to verify my guess

**Comment by WeiZhang555** [comment]
Ubuntu-16.04 CI passed, so my guess is right.

This problem is caused by the K8S cleanup script: https://github.com/kata-containers/tests/blob/master/integration/kubernetes/cleanup_env.sh#L11-L21

This script will first call `sudo -E kubeadm reset --cri-socket=/var/run/crio/crio.sock` which will remove all "/var/lib/kubelet", and then call `ctictl` to stop and remove pod, at this time, the volume source under `/var/lib/kubelet` such as `/var/lib/kubelet/pods/d903eaa9-9184-11e8-9908-fa163e279126/etc-hosts` is already removed, which caused the problem.

So this test case demonstrate this situation exactly:
```
Terminal 1:
$ docker run -ti -v /tmp/a/hello:/hello --runtime kata busybox sh
/

Terminal 2:
$ rm -fv /tmp/a/hello

Terminal 1: exit the container
/ exit
```

According to my test, master branch could also leak kata-proxy process with this test case, not sure why it passed. Never mind, I'll add a new test case to test repo to address this.

**Comment by WeiZhang555** [comment]
@bergwolf Not sure whether the workaround can be deleted or not, let me check with our CI team.

also ping @sboeuf @egernst @amshinde

**Comment by jodh-intel** [comment]
lgtm

re-ping @sboeuf @egernst @amshinde.

**Comment by sboeuf** [comment]
@jodh-intel I'll take a look today!

**Pull request merged**
