### PR TITLE
Stable 1.5 backports

### PR DESCRIPTION
**Pull request by egernst**
Backport fixes from master

## Patches pulled:
edc77a02 Merge pull request #1502 from amshinde/make-tc-default
38526822 network: Change the package level network default
33bae705 network: Make tcfilter model as default

da08b3af Merge pull request #1509 from bergwolf/kata-check
9ac68310 cli: fix kata-check test

### Questionable:

This set has conflicts:
d5a759e1 Merge pull request #1526 from bergwolf/ut-non-root
9040f6a8 ut: fix UT failure due to incorrect cleanup
a0f49a91 ut: fix UT failure due to non-root

 c08976e1 Merge pull request #1494 from lifupan/fixstop
 f7223c6f shimv2: fix the issue of stop container failed

### Confidently Rejected

Not an issue with 1.5, as we don't provide host cgroups:
d99693a5 Merge pull request #1518 from lifupan/fixtop
1a1f93bc virtcontainers: add a kata specific prefix to host cgroups path

 5d875be2 (origin/master, origin/HEAD) Merge pull request #1409 from teawater/vmcache_templating
 343a0d35 factory: Make VMCache and VM templating can work together

168665b9 Merge pull request #1439 from YongjiXie/pass-correct-mount-type-for-ephemeral-volumes
2d422a84 agent: pass correct mount type to agent for ephemeral volumes

2b45f0b2 Merge pull request #1528 from bergwolf/grpc
f5125421 sandbox: return ErrNoSuchContainer when failing to find a container
8215a3ce shimv2: convert vc errors to grpc errors
cf907516 vc: export vc error types

ae022dc Merge pull request #1428 from gabibeyer/slashNburn
b08ab6ae vc: modify ioctl function to handle shim test
c4250790 vc: Deprecate CC proxy and shim
c6587708 vc: remove virtc api cli
d4ef9c05 vc: deprecate hyperstart agent

6e595783 Merge pull request #1530 from devimc/topic/virtcontainers/inheritParentCpuCgroup
59e39563 virtcontainers: inherit parent's CPU constraint

9b622b7e Merge pull request #1485 from awprice/k8s-empty-dir-local
76c4639a storage: create k8s emptyDir inside VM
228d1512 mount: Add check for k8s host empty directory
70c19313 mounts: Add check for system volumes

e15f3e49 Merge pull request #1337 from jongwu/bypass
98687a34 Template: enable template for arm64

dd5c6aa7 Merge pull request #1507 from bergwolf/state
c4145996 types: remove pid from sandbox state
03ee25d4 agent: treat container as shared pidns whenever it has pidns path
616f26cf types: split sandbox and container state

6d81e446 Merge pull request #1437 from teawater/vmcache_grpc
ace81155 factory: Make factory status can show status of VMCache server
f639787e factory: Make factory destroy can stop VMCache server

### CODE REVIEW

**Comment by jcvenegas** [comment]
http://jenkins.katacontainers.io/job/kata-containers-runtime-sles-12-PR/44/console
```
--- FAIL: TestNsEnterSuccessful (0.00s)
    <autogenerated>:1: 
                          
	Error Trace:	nsenter_test.go:210
        
	Error:      	Expected nil, but got: &errors.errorString{s:"failed to open target ns: failed to Statfs \"/proc/106472/ns/cgroup\": no such file or directory"}
        
	Messages:   	failed to open target ns: failed to Statfs "/proc/106472/ns/cgroup": no such file or directory
    <autogenerated>:1: 
                          
	Error Trace:	nsenter_test.go:240
        
	Error:      	Not equal: 
        
	            	expected: "cgroup"
        
	            	actual: "0"
    <autogenerated>:1: 
                          
	Error Trace:	nsenter_test.go:240
        
	Error:      	Not equal: 
        
	            	expected: "ipc:[4026533094]"
        
	            	actual: "0"
    <autogenerated>:1: 
                          
	Error Trace:	nsenter_test.go:240
        
	Error:      	Not equal: 
        
	            	expected: "net:[4026533097]"
        
	            	actual: "0"
    <autogenerated>:1: 
                          
	Error Trace:	nsenter_test.go:240
        
	Error:      	Not equal: 
        
	            	expected: "pid:[4026533095]"
        
	            	actual: "0"
    <autogenerated>:1: 
                          
	Error Trace:	nsenter_test.go:240
        
	Error:      	Not equal: 
        
	            	expected: "uts:[4026533093]"
        
	            	actual: "0"
FAIL
```
http://jenkins.katacontainers.io/job/kata-containers-runtime-ubuntu-18-04-PR-initrd/1812/console
```
• Failure in Spec Teardown (AfterEach) [73.495 seconds]
[k8s.io] Container
/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR-initrd/go/src/github.com/kubernetes-sigs/cri-tools/pkg/framework/framework.go:72
  runtime should support basic operations on container
  /tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR-initrd/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container.go:68
    runtime should support stopping container [Conformance] [AfterEach]
    /tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR-initrd/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container.go:100

    Apr 16 21:50:05.405: stop container "b789671d2c8bcd2b9a16f49bb9cf8f024c533d2223fb3e29394d0d2af65b9b98" timeout.
    

    /tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR-initrd/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container.go:332
------------------------------


Summarizing 1 Failure:

[Fail] [k8s.io] Container runtime should support basic operations on container [AfterEach] runtime should support stopping container [Conformance] 
/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR-initrd/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container.go:332

Ran 5 of 71 Specs in 73.540 seconds
FAIL! -- 4 Passed | 1 Failed | 0 Pending | 66 Skipped
```

http://jenkins.katacontainers.io/job/kata-containers-runtime-ubuntu-nemu/235/console
```
16:15:07 Summarizing 2 Failures:
16:15:07 
16:15:07 [Fail] docker exec [AfterEach] modifying a container with exec should have the changes 
16:15:07 /tmp/jenkins/workspace/kata-containers-runtime-ubuntu-nemu/go/src/github.com/kata-containers/tests/integration/docker/exec_test.go:35
16:15:07 
16:15:07 [Fail] docker exec [BeforeEach] check exit code using exec should have the value assigned 
16:15:07 /tmp/jenkins/workspace/kata-containers-runtime-ubuntu-nemu/go/src/github.com/kata-containers/tests/integration/docker/exec_test.go:31
16:15:07 
16:15:07 Ran 225 of 234 Specs in 2288.334 seconds
16:15:07 FAIL! -- 223 Passed | 2 Failed | 0 Pending | 9 Skipped --- FAIL: TestIntegration (2311.67s)
16:15:07 FAIL
16:15:07 
```

http://jenkins.katacontainers.io/job/kata-containers-runtime-fedora-vsocks-PR/632/console
```
• Failure in Spec Teardown (AfterEach) [73.934 seconds]
[k8s.io] Container
/tmp/jenkins/workspace/kata-containers-runtime-fedora-vsocks-PR/go/src/github.com/kubernetes-sigs/cri-tools/pkg/framework/framework.go:72
  runtime should support basic operations on container
  /tmp/jenkins/workspace/kata-containers-runtime-fedora-vsocks-PR/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container.go:68
    runtime should support stopping container [Conformance] [AfterEach]
    /tmp/jenkins/workspace/kata-containers-runtime-fedora-vsocks-PR/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container.go:100

    Apr 16 21:43:49.915: stop container "e16f2cebf6d0d1c9b9ef6985ad3bdefa79d388c47d9c4ac6cc2984dcfc9e5ccc" timeout.
    

    /tmp/jenkins/workspace/kata-containers-runtime-fedora-vsocks-PR/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container.go:332
------------------------------


Summarizing 1 Failure:

[Fail] [k8s.io] Container runtime should support basic operations on container [AfterEach] runtime should support stopping container [Conformance] 
/tmp/jenkins/workspace/kata-containers-runtime-fedora-vsocks-PR/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container.go:332

Ran 5 of 68 Specs in 73.977 seconds
FAIL! -- 4 Passed | 1 Failed | 0 Pending | 63 Skipped
```
http://jenkins.katacontainers.io/job/kata-containers-runtime-fedora-PR/1920/console
```
• Failure in Spec Teardown (AfterEach) [74.163 seconds]
[k8s.io] Container
/tmp/jenkins/workspace/kata-containers-runtime-fedora-PR/go/src/github.com/kubernetes-sigs/cri-tools/pkg/framework/framework.go:72
  runtime should support basic operations on container
  /tmp/jenkins/workspace/kata-containers-runtime-fedora-PR/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container.go:68
    runtime should support stopping container [Conformance] [AfterEach]
    /tmp/jenkins/workspace/kata-containers-runtime-fedora-PR/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container.go:100

    Apr 16 21:23:10.514: stop container "18c9bb241ead41c8da5816f21d3b62c3ef3bfb2e6d279698a2a338638550d8b7" timeout.
    

    /tmp/jenkins/workspace/kata-containers-runtime-fedora-PR/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container.go:332
------------------------------


Summarizing 1 Failure:

[Fail] [k8s.io] Container runtime should support basic operations on container [AfterEach] runtime should support stopping container [Conformance] 
/tmp/jenkins/workspace/kata-containers-runtime-fedora-PR/go/src/github.com/kubernetes-sigs/cri-tools/pkg/validate/container.go:332

Ran 5 of 68 Specs in 74.230 seconds
FAIL! -- 4 Passed | 1 Failed | 0 Pending | 63 Skipped
```
http://jenkins.katacontainers.io/job/kata-containers-runtime-centos-7-4-q-35-PR/1605/console
```
docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
make: *** [ramdisk] Error 125
Process leaked file descriptors. See https://jenkins.io/redirect/troubleshooting/process-leaked-file-descriptors for more information
Build step 'Execute shell' marked build as failure
Performing Post build task...
Match found for :.* : True
Logical operation result is TRUE
Running script  : #!/bin/bash
```
http://jenkins.katacontainers.io/job/kata-containers-runtime-ARM-18.04-PR/483/console
```
16:02:01 --- FAIL: TestEnvGetEnvInfoSetsCPUType (0.02s)
16:02:01     assertions.go:239: 
                          
	Error Trace:	kata-env_generic_test.go:48
16:02:01         
	            	
			kata-env_arm64_test.go:98
16:02:01         
	Error:      	Not equal: 
16:02:01         
	            	expected: main.EnvInfo{Meta:main.MetaInfo{Version:"1.0.20"}, Runtime:main.RuntimeInfo{Version:main.RuntimeVersionInfo{Semver:"1.5.3", Commit:"0baa56bb694bd0ffc8f7d623a2a1c1cdd909d69f", OCI:"1.0.1-dev"}, Config:main.RuntimeConfigInfo{Path:"/tmp/836348800/runtime.toml"}, Debug:false, Trace:false, DisableGuestSeccomp:false, DisableNewNetNs:false, Path:"/tmp/go-build793471919/b001/cli.test"}, Hypervisor:main.HypervisorInfo{MachineType:"machineType", Version:"QEMU emulator version 2.7.0+git.741f430a96-6.1, Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers", Path:"/tmp/836348800/hypervisor", BlockDeviceDriver:"virtio-scsi", EntropySource:"/dev/urandom", Msize9p:0x2000, MemorySlots:0xa, Debug:false, UseVSock:false}, Image:main.ImageInfo{Path:"/tmp/836348800/image"}, Kernel:main.KernelInfo{Path:"/tmp/836348800/kernel", Parameters:"init=/usr/lib/systemd/systemd systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket foo=bar xyz"}, Initrd:main.InitrdInfo{Path:""}, Proxy:main.ProxyInfo{Type:"kataProxy", Version:"proxy version 0.1", Path:"/tmp/836348800/proxy", Debug:false}, Shim:main.ShimInfo{Type:"kataShim", Version:"shim version 0.1", Path:"/tmp/836348800/shim", Debug:false}, Agent:main.AgentInfo{Type:"kata"}, Host:main.HostInfo{Kernel:"99.1", Architecture:"arm64", Distro:main.DistroInfo{Name:"Foo", Version:"42"}, CPU:main.CPUInfo{Vendor:"ARM Limited", Model:"v8"}, VMContainerCapable:true, SupportVSocks:false}, Netmon:main.NetmonInfo{Version:"netmon version 0.1", Path:"/tmp/836348800/netmon", Debug:false, Enable:false}}
16:02:01         
	            	actual: main.EnvInfo{Meta:main.MetaInfo{Version:"1.0.20"}, Runtime:main.RuntimeInfo{Version:main.RuntimeVersionInfo{Semver:"1.5.3", Commit:"0baa56bb694bd0ffc8f7d623a2a1c1cdd909d69f", OCI:"1.0.1-dev"}, Config:main.RuntimeConfigInfo{Path:"/tmp/836348800/runtime.toml"}, Debug:false, Trace:false, DisableGuestSeccomp:false, DisableNewNetNs:false, Path:"/tmp/go-build793471919/b001/cli.test"}, Hypervisor:main.HypervisorInfo{MachineType:"machineType", Version:"QEMU emulator version 2.7.0+git.741f430a96-6.1, Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers", Path:"/tmp/836348800/hypervisor", BlockDeviceDriver:"virtio-scsi", EntropySource:"/dev/urandom", Msize9p:0x2000, MemorySlots:0xa, Debug:false, UseVSock:false}, Image:main.ImageInfo{Path:"/tmp/836348800/image"}, Kernel:main.KernelInfo{Path:"/tmp/836348800/kernel", Parameters:"init=/usr/lib/systemd/systemd systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket foo=bar xyz"}, Initrd:main.InitrdInfo{Path:""}, Proxy:main.ProxyInfo{Type:"kataProxy", Version:"proxy version 0.1", Path:"/tmp/836348800/proxy", Debug:false}, Shim:main.ShimInfo{Type:"kataShim", Version:"shim version 0.1", Path:"/tmp/836348800/shim", Debug:false}, Agent:main.AgentInfo{Type:"kata"}, Host:main.HostInfo{Kernel:"99.1", Architecture:"arm64", Distro:main.DistroInfo{Name:"Foo", Version:"42"}, CPU:main.CPUInfo{Vendor:"ARM Limited", Model:"v8"}, VMContainerCapable:true, SupportVSocks:true}, Netmon:main.NetmonInfo{Version:"netmon version 0.1", Path:"/tmp/836348800/netmon", Debug:false, Enable:false}}
16:02:01         
	            	
16:02:01         
	            	Diff:
16:02:01         
	            	--- Expected
16:02:01         
	            	+++ Actual
16:02:01         
	            	@@ -67,3 +67,3 @@
16:02:01         
	            	   VMContainerCapable: (bool) true,
16:02:01         
	            	-  SupportVSocks: (bool) false
16:02:01         
	            	+  SupportVSocks: (bool) true
16:02:01         
	            	  },
```

**Comment by jcvenegas** [comment]
hi @Pennyzct, is there a fix for unit test in ARM CI?

**Comment by jcvenegas** [comment]
@egernst I'll restart fedora as both fedora jobs failed in the same test.

**Comment by jcvenegas** [comment]
https://github.com/kata-containers/runtime/pull/1538 is looking good so it is an issue related with this backport

**Comment by jcvenegas** [comment]
@egernst could you remove c08976e Merge pull request #1494 from lifupan/fixstop from this PR ?

**Comment by egernst** [comment]
repushed

**Pull request merged**
