### PR TITLE
vc: Remove extra call to Kill

### PR DESCRIPTION
**Pull request by tedyu**
This PR addresses this comment:
https://github.com/kata-containers/runtime/pull/2164/files#r346776205

/cc @jodh-intel

### CODE REVIEW

**Comment by tedyu** [comment]
```
ERROR: Commit 94b931cee4ec571e4bccc42b5403add73558ebbc: Failed to find subsystem in subject: "Remove extra call to Kill"
```
I looked at recent commits but didn't find pattern of embedding subsystem in the subject.

**Comment by grahamwhaley** [comment]
@tedyu - the 'subsystem' CI failure is telling you your commit subject line does not meet the format documented at:
https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#general-format

**Comment by grahamwhaley** [comment]
Looking at the patch, `virtcontainers` is probably the correct/appropriate subsystem, so renaming the commit subject to say:

`vc: remove extra call to kill`

would be the right thing. You can do that with a 'git commit --amend' and 'git push -f' for instance.

**Comment by egernst** [comment]
@tedyu you need a body on the commit. Further, you’ll want a reference to a GitHub issue which this PR addresses. Sorry for the extra hoops, and appreciate your help.

**Comment by egernst** [comment]
To help: I opened issue for you: https://github.com/kata-containers/runtime/issues/2207

**Comment by tedyu** [comment]
@egernst 
I have added the body for the commit.

**Comment by tedyu** [comment]
Does enkins-ci-ubuntu-18-04 normally take more than 2 hours to complete ?

**Comment by grahamwhaley** [comment]
/test
@tedyu - it needs triggering first ;-)

**Comment by tedyu** [comment]
For Power8-ubuntu:
```
ERROR: kata-log-parser: missing pid: {Count:0 TimeDelta:0 Filename:/home/jenkins/workspace/kata-containers-runtime-Power8-ubuntu-18-04-PR-initrd/go/src/github.com/kata-containers/tests/kata-runtime.log Line:47 Time:2019-11-17 21:31:04.495442708 -0500 EST Pid:0 Level:debug Msg:converting /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/17469350cf17a841e3f4e101cb9687f798531f1c8d336871038eb9d10bb34b30/config.json Source:virtcontainers Name: Container: Sandbox: Data:map[subsystem:compatoci]}
```
I don't think the above was caused by my PR.

**Comment by tedyu** [comment]
Looks like I don't have permission to re-trigger test.

**Comment by grahamwhaley** [comment]
@tedyu - possibly not - you have to be a member of the kata org and iirc the correct team, to do that...
Also, if you follow
https://github.com/kata-containers/ci#controlling-the-ci over to https://github.com/kata-containers/community/wiki/Controlling-the-CI you can see the list of commands that should work...

Let's try:

/test-power

**Comment by grahamwhaley** [comment]
also, if you need to locate who might be responsible for which bit of the project or infra, there is a table over at https://github.com/kata-containers/community/wiki/Areas-of-interest#resource-owners to help guide (in case we need to find the Power CI owners etc.)

**Comment by tedyu** [comment]
@jodh-intel
Do you have some insight why codecov declined ?

My PR reduces number of lines of code, I am not sure why coverage declined.

**Comment by tedyu** [comment]
@grahamwhaley 
I cannot trigger test rerun.

**Comment by tedyu** [comment]
@grahamwhaley @egernst 
When you have a chance, can you trigger another test run ?

thanks

**Comment by jodh-intel** [comment]
Thanks @tedyu - there are other instances of this "double kill". I was about to say you could update this PR for those, but it got merged underneath me :) Therefore, if you are interested,  feel free to raise a follow-on PR to update `virtcontainers/acrn.go` and `virtcontainers/fc.go`.

Regarding the coverage stats - we have never found a reliable service unfortunately. It's on the "TODO" list but if anyone has spare cycles, feel free to dig in! :smile:

**Pull request merged**
