### PR TITLE
kata-env: Add ability to output as JSON

### PR DESCRIPTION
**Pull request by grahamwhaley**
Having a direct JSON output for kata-env will help record
results in our CIs in some instances. Add that ability with
a kata-env command line extension.

Fixes: #474

Signed-off-by: Graham Whaley <graham.whaley@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Part of the reason I've pushed this is to see what the CI thinks, as I've not quite figured out how to sanely get the 'make check' to run on this locally yet... ;-)

**Comment by grahamwhaley** [comment]
Updated the tests and re-pushed.
If CI's pass go tests, pls review.

**Comment by grahamwhaley** [comment]
Haha: `cli/kata-env_test.go:1::warning: file is not gofmted with -s (gofmt)` - thought I'd done that already... repushed

**Comment by sboeuf** [comment]
@amshinde ptal

**Comment by devimc** [comment]
lgtm

**Comment by jodh-intel** [comment]
\o/

**Pull request merged**
