### PR TITLE
versions: Update cloud-hypervisor to release v0.11.0

### PR DESCRIPTION
**Pull request by likebreath**
The release v0.11.0 of cloud-hypervisor features the following changes:
1 ) Improved Linux Boot Time, 2) `SIGTERM/SIGINT` Interrupt Signal,
Handling 3) Default Log Level Changed, 4) `io_uring` support by default
for `virtio-block` (on host kernel version 5.8+), 5) Windows Guest
Support, 6) New `--balloon` Parameter Added, 7) Experimental
`virtio-watchdog` Support, 8) Bug fixes.

Fixes: #3044

Signed-off-by: Bo Chen <chen.bo@intel.com>

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]

**Review by devimc — APPROVED** [review]
thanks @likebreath

**Comment by jodh-intel** [comment]
Hi @likebreath - It looks like this hasn't been ported to 2.x (https://github.com/kata-containers/kata-containers/tree/2.0-dev/src/runtime) yet. Would you be able to look at doing that?

**Comment by likebreath** [comment]
@jodh-intel Thanks for the reminding. It is on my to-do list. I am holding for this forward-porting on landing another PR in kata 2.0 (https://github.com/kata-containers/kata-containers/pull/1077).

**Pull request merged**
