### PR TITLE
cc-runtime: Fix kernel param handling & update collect script

### LINKED ISSUE #27: Update cc-runtime to fix kernel parameter handling bug
Update the `cc-runtime` module for:

-  config: Allow user-specified kernel params to take priority
   https://github.com/clearcontainers/runtime/commit/feed1be89e391110ab54d330815f7a73029e01ac

- Fixes to the data collection script for Kata.

### PR DESCRIPTION
**Pull request by jodh-intel**
Update `cc-runtime` submodule for two main reasons:

-  config: Allow user-specified kernel params to take priority
   https://github.com/clearcontainers/runtime/commit/feed1be89e391110ab54d330815f7a73029e01ac

- Update data collection script to work with Kata.

Changes:

    a63895e versions: Update kernel version
    7bf93e2 release: Clear Containers 3.0.16
    1412ff8 cc-env: Remove "CC" from output.
    5e7d03c vendor: Update virtcontainers vendoring
    f515c21 vendor: Update Gopkg.toml for new prune syntax
    ef63d36 vendor: Remove constraints from packages not directly vendored
    ab1a9f1 build: Add bug URL to help output
    719f523 scripts: Fix collect script bug URL
    93c71c9 cc-check: Document "unrestricted_guest" requirement
    0f8b25d scripts: Ignore qemu startup message
    7310433 scripts: Update collect script for Kata
    feed1be config: Allow user-specified kernel params to take priority
    e7de45d usage: Show project URL in help output
    b45d46c release: Clear Containers 3.0.15
    e65682c docs: remove references to Clear Containers proxy service

Fixes #27.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Travis is failing because #24 hasn't landed yet (and that PR adds the `.travis.yml` file).

**Comment by WeiZhang555** [comment]
#24 is merged, I think you can retrigger CI now.

LGTM if CI is green again

**Comment by jodh-intel** [comment]
Thanks @WeiZhang555. Branch updated.

**Comment by grahamwhaley** [comment]
need an ack from one of @kata-containers/runtime 
Just to check @jodh-intel , whilst here, anything new we can pick up with a rebase ?

**Comment by sameo** [comment]
LGTM

**Pull request merged**
