### PR TITLE
mount fixes for stable-1.12

### PR DESCRIPTION
**Pull request by egernst**
Backport to stable-1.12:
```
runtime: readonly mounts should be readonly bindmount on the host
runtime: mount shared mountpoint readonly
```

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm, thanks!

**Review by devimc — APPROVED** [review]
thanks @egernst

**Review by amshinde — APPROVED** [review]

**Comment by amshinde** [comment]
@egernst Travis is failing with error:
```
ERROR: Required Copyright header check ('Copyright \(c\) [[:digit:]]{4}') failed for the following files:
virtcontainers/pkg/types/types.go

```
I am not sure if we modified that check recently, but what I see on the 1.12 branch:
```
 
// Copyright 2018 Intel Corporation.
//
// SPDX-License-Identifier: Apache-2.0
//
```
vs on master:
```
// Copyright (c) 2018 Intel Corporation.
//
// SPDX-License-Identifier: Apache-2.0
//
```
cc @chavafg

**Comment by amshinde** [comment]
@egernst Can you backport to stable 1.11 as well?

**Review by jodh-intel — APPROVED** [review]

**Comment by amshinde** [comment]
@egernst Can you change the copyright so that we can get this merged.

**Comment by jodh-intel** [comment]
Ah - looks like you've falled foul of https://github.com/kata-containers/tests/pull/2869.

**Comment by egernst** [comment]
I didn't even touch this file? Grumble grumble grumble. If we add a new test, we should fix the repo before merging it?

**Comment by amshinde** [comment]
Yeah, I am not sure how this got away. Anyways, has been fixed now. I just reran travis job for this PR , should pass now.

**Comment by jodh-intel** [comment]
Commits added:

- https://github.com/kata-containers/runtime/commit/77399058bf3ded60aaeb08978073d000f178478f
- https://github.com/kata-containers/runtime/commit/509eb6f850c0ceb60eb91a6095cceb8e4c7150f5

Yeah, this is odd and slightly worrying as I can't see how this is possible.

**Pull request merged**
