### PR TITLE
Revert "vc: change container rootfs to be a mount"

### PR DESCRIPTION
**Pull request by chavafg**
This reverts commit 196661bc0d351daa42b793b75ffdc0b88d3bcf39.

Reverting because cri-o with devicemapper started
to fail after this commit was merged.

Fixes: #1574.

### CODE REVIEW

**Comment by chavafg** [comment]
I want to do this revert since cri-o CI is failing because and we are blocking them. 
/cc @bergwolf @amshinde @egernst @sboeuf

**Comment by sboeuf** [comment]
@bergwolf please chime in on this one, as this was your PR.

**Comment by gnawux** [comment]
weird.... @chavafg do you mean the kata changes blocked the CI of CRI-O project?

**Comment by chavafg** [comment]
@gnawux yes, we have a CI job running on their repo.

**Comment by gnawux** [comment]
It's unusual that an internal change of a project breaks the CI of another project. Does this mean we do not have device mapper being tested in our CI?

**Comment by chavafg** [comment]
We stopped testing with devicemapper when we moved from ubuntu 16.04 to 18.04, Didn't realized honestly until this failure. I have opened https://github.com/kata-containers/tests/pull/1494 to fix that.

**Comment by gnawux** [comment]
ping @bergwolf, take a look here

**Comment by bergwolf** [comment]
@jcvenegas I don't have a cri-o setup to reproduce it. Do you have full logs somewhere that I can access to see what happened there?

**Comment by chavafg** [comment]
@bergwolf I think you can check the logs in http://jenkins.katacontainers.io/job/kata-containers-crio-PR/1702/

**Comment by bergwolf** [comment]
cri-o first umounted the mountpoint and then removed the device mapper device(`ba6957dbb3b068c72b0d877a99f4908e5b6bd93c6643ca1ad49f723401dd6782`). After that it reports that umount failed with EBUSY. Not the removal operation? That one would be easier to guess.

I did test containerd devmapper snapshotter (w/ both v1 and v2 shims) and docker device mapper graphdriver, and didn't see such failure. So I guess it is something special with cri-o. I need to setup a cri-o environment to understand its workflow there. In the meantime, feel free to merge this PR if you are certain that it is the root cause for the cri-o failure.

```
23:16:28 # time="2019-04-23 15:16:07.052129433Z" level=debug msg="devmapper: UnmountDevice START(hash=ba6957dbb3b068c72b0d877a99f4908e5b6bd93c6643ca1ad49f723401dd6782)"
23:16:28 # time="2019-04-23 15:16:07.052687136Z" level=debug msg="devmapper: Unmount(/tmp/tmp.XZ9I6Eb6VZ/crio/devicemapper/mnt/ba6957dbb3b068c72b0d877a99f4908e5b6bd93c6643ca1ad49f723401dd6782)"
23:16:28 # time="2019-04-23 15:16:07.078521171Z" level=debug msg="devmapper: Unmount done"
23:16:28 # time="2019-04-23 15:16:07.078558771Z" level=debug msg="devmapper: deactivateDevice START(ba6957dbb3b068c72b0d877a99f4908e5b6bd93c6643ca1ad49f723401dd6782)"
23:16:28 # time="2019-04-23 15:16:07.078673472Z" level=debug msg="devmapper: removeDevice START(container-8:1-1280011-ba6957dbb3b068c72b0d877a99f4908e5b6bd93c6643ca1ad49f723401dd6782)"
23:16:28 # time="2019-04-23 15:16:27.133753351Z" level=debug msg="devmapper: removeDevice END(container-8:1-1280011-ba6957dbb3b068c72b0d877a99f4908e5b6bd93c6643ca1ad49f723401dd6782)"
23:16:28 # time="2019-04-23 15:16:27.133804752Z" level=debug msg="devmapper: deactivateDevice END(ba6957dbb3b068c72b0d877a99f4908e5b6bd93c6643ca1ad49f723401dd6782)"
23:16:28 # time="2019-04-23 15:16:27.133816552Z" level=debug msg="devmapper: UnmountDevice END(hash=ba6957dbb3b068c72b0d877a99f4908e5b6bd93c6643ca1ad49f723401dd6782)"
23:16:28 # time="2019-04-23 15:16:27.133829452Z" level=error msg="devmapper: Error unmounting device ba6957dbb3b068c72b0d877a99f4908e5b6bd93c6643ca1ad49f723401dd6782: Device is Busy"
23:16:28 # time="2019-04-23 15:16:27.192205649Z" level=debug msg="failed to unmount container \"f1dd8a9102a85957216bd2b026b1ba4aef9a87e1a7623570f9c9013d1d7deca2\": Device is Busy"
```

**Comment by chavafg** [comment]
@kata-containers/runtime ptal and provide approvals if you agree, so this can be merged. @bergwolf has agreed to merge it while he takes a look at the issue.

**Comment by sboeuf** [comment]
@egernst @amshinde PTAL

**Pull request merged**
