### PR TITLE
revert: "virtcontainers: support pre-add storage for frakti"

### LINKED ISSUE #529: After running K8s tests processes are left behind
After running K8s tests processes like shim are left behind

```
$ pgrep -a -f /usr/libexec/kata-containers/kata-shim
1848 /usr/libexec/kata-containers/kata-shim -agent unix:///run/vc/sbs/98264dde03f2f9b9a1cec51adc5a80b47a23b819b9dece9f61fe624d2b66149a/proxy.sock -container 98264dde03f2f9b9a1cec51adc5a80b47a23b819b9dece9f61fe624d2b66149a -exec-id 98264dde03f2f9b9a1cec51adc5a80b47a23b819b9dece9f61fe624d2b66149a -log debug
27893 /usr/libexec/kata-containers/kata-shim -agent unix:///run/vc/sbs/b8873ddaef5b0072f2632be77749a2f6306bdc322ec89a35112b3d14ca72bb15/proxy.sock -container b8873ddaef5b0072f2632be77749a2f6306bdc322ec89a35112b3d14ca72bb15 -exec-id b8873ddaef5b0072f2632be77749a2f6306bdc322ec89a35112b3d14ca72bb15 -log debug
27966 /usr/libexec/kata-containers/kata-shim -agent unix:///run/vc/sbs/b8873ddaef5b0072f2632be77749a2f6306bdc322ec89a35112b3d14ca72bb15/proxy.sock -container 06ae4e2e246ccc4a82fe842c287a33bb8f98c7d0e7aa97054d8194e8afa0c82c -exec-id 06ae4e2e246ccc4a82fe842c287a33bb8f98c7d0e7aa97054d8194e8afa0c82c -log debug
28050 /usr/libexec/kata-containers/kata-shim -agent unix:///run/vc/sbs/b8873ddaef5b0072f2632be77749a2f6306bdc322ec89a35112b3d14ca72bb15/proxy.sock -container b362b6b83d66e179978591ed035868cab43ed9f64f57b5c37890463575d14532 -exec-id b362b6b83d66e179978591ed035868cab43ed9f64f57b5c37890463575d14532 -log debug
28132 /usr/libexec/kata-containers/kata-shim -agent unix:///run/vc/sbs/b8873ddaef5b0072f2632be77749a2f6306bdc322ec89a35112b3d14ca72bb15/proxy.sock -container 884e0a2db39f255494da117d7d8eb3c40923f49aa25f1265845f3e9243bfdeda -exec-id 884e0a2db39f255494da117d7d8eb3c40923f49aa25f1265845f3e9243bfdeda -log debug
```
Here it is the configuration that I am using
kata-runtime  : 1.1.0
commit   : cfbc974fec1d04ec7d799eac11f3bee99ab8e477
OCI specs: 1.0.1
kata-proxy version 1.1.0-c416c9fc2ff8389c201075f0f26bfabd08a3b140
kata-shim version 1.1.0-6ddca0334d0e8dee6e1e00f0c120fde4b8c1c176
kata-agent version 1.1.0-c6ac153f0c4c03b475d2b65bb73427cd33459bf7

That is causing that the `swarm` tests are failing as they are detecting that processes were left behind (https://github.com/kata-containers/agent/pull/309)

### PR DESCRIPTION
**Pull request by sboeuf**
This PR got merged while it had some issues with some shim processes
being left behind after k8s testing. And because those issues were
real issues introduced by this PR (not some random failures), now
the master branch is broken and new pull requests cannot get the
CI passing. That's the reason why this commit revert the changes
introduced by this PR so that we can fix the master branch.

Fixes #529 

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Comment by sboeuf** [comment]
@egernst @GabyCT ubuntu 16.04 is passing

**Comment by GabyCT** [comment]
lgtm

**Comment by sboeuf** [comment]
@egernst please merge if you're fine with this.

**Comment by WeiZhang555** [comment]
Sorry for late response, I will investigate more and thank @sboeuf for fixing this!

**Comment by sboeuf** [comment]
@WeiZhang555 no problem, I hope you get this fixed quickly so that we can get your PR back ;)

**Pull request merged**
