### PR TITLE
vc: Sandbox#Annotations should use annotationsLock read lock

### LINKED ISSUE #2222: Sandbox#Annotations should use annotationsLock read lock
# Description of problem

Currently Sandbox#Annotations reads config.Annotations directly without holding lock.
This would result in data race if the same key is written in Sandbox#SetAnnotations.

# Expected result

Sandbox#Annotations should use annotationsLock read lock

# Actual result

### PR DESCRIPTION
**Pull request by tedyu**
Fixes #2222

Signed-off-by: Ted Yu <yuzhihong@gmail.com>

### CODE REVIEW

**Comment by tedyu** [comment]
@grahamwhaley 
Can you review this ?

thanks

**Comment by grahamwhaley** [comment]
Hi @tedyu.
 Sure.
 I should probably explain some of the kata review process - we have a [weekly rota](https://github.com/kata-containers/community/wiki/Review-Team-Rota) of members watching out for new PRs and also processing and nudging along any stuck or stale PRs - so normally you should not have to nudge anybody to review - unless you happen to know who is a key [owner of some code](https://github.com/kata-containers/community/wiki/Areas-of-interest) - in which case you can specifically ask them to review something.

I'm not the best person to review virtcontainers code, but will pull in the right folks who are.

thanks!

**Comment by tedyu** [comment]
Thanks @grahamwhaley for adding reviewers.

**Comment by tedyu** [comment]
@grahamwhaley @jodh-intel 
Mind triggering test ?

Thanks

**Comment by grahamwhaley** [comment]
/test
sure thing!

**Comment by tedyu** [comment]
```
15:07:43 panic: ERROR: Docker-like container engine not accessible to current user:  (error exec: "podman": executable file not found in $PATH)
15:07:43 
15:07:43 goroutine 1 [running, locked to thread]:
15:07:43 github.com/kata-containers/runtime/cli.init.1()
15:07:43 	/tmp/jenkins/workspace/kata-containers-runtime-fedora-PR/go/src/github.com/kata-containers/runtime/cli/main_test.go:105 +0x10c1
15:07:43 FAIL	github.com/kata-containers/runtime/cli	0.291s
```
The test failure didn't seem to be related.

@grahamwhaley 
Can you re-trigger the fedora test ?

Thanks

**Comment by grahamwhaley** [comment]
done

**Comment by tedyu** [comment]
```
09:18:07 Stderr: failed to launch qemu: exit status 1, error messages from qemu log: qemu-system-x86_64: -object memory-backend-file,id=mem0,mem-path=/usr/share/kata-containers/kata-containers-clearlinux-31670-osbuilder-36a9dc5-agent-c87f497.img,size=118269440: backing store (null) size 0x70ca600 does not match 'size' option 0x70cb000
```
A different error this time.
I searched for the phrase which doesn't seem to be in kata-containers/runtime

@grahamwhaley 
Can you trigger another test run ?

Thanks

**Comment by grahamwhaley** [comment]
I can. also /cc @chavafg to check if this is a known CI instability.

**Comment by chavafg** [comment]
@grahamwhaley haven't seen something similar, but will keep an eye to check if it happens again...

**Comment by tedyu** [comment]
@grahamwhaley 
All tests passed.

FYI

**Pull request merged**
