### PR TITLE
vendor in latest govmm code

### PR DESCRIPTION
**Pull request by egernst**

### CODE REVIEW

**Comment by alicefr** [comment]
hi, would it be possible to include with this PR the new commits in govmm added by https://github.com/intel/govmm/pull/99 ?

**Comment by grahamwhaley** [comment]
@egernst - will let you answer @alicefr request before we push on (I'll avoid re-spin of the 18.04-initrd ci failure, as I suspect you may repush soon).

**Comment by egernst** [comment]
non est necesse

**Pull request closed without merging**
