### PR TITLE
cherry pick shimv2 fixes from master branch to stable-1.7

### PR DESCRIPTION
**Pull request by lifupan**
cherry pick shimv2 fixes from master branch to stable-1.7

### CODE REVIEW

**Comment by lifupan** [comment]
@kata-containers/runtime, it's weird, I hadn't touch the cli codes, but all of the test failed at there.

**Comment by awprice** [comment]
Is there anything preventing this from being backported? We are looking forward to using a release of Kata with these changes included in it.

**Comment by jodh-intel** [comment]
Restarted PPC CI which failed with a strange error:

```
=== RUN   TestSandboxStateRunningPaused
time="2019-05-29T09:04:24+05:30" level=error msg="Unable to launch /tmp/vc-tmp-235439353/hypervisor: fork/exec /tmp/vc-tmp-235439353/hypervisor: permission denied" source=virtcontainers subsystem=qmp
time="2019-05-29T09:04:24+05:30" level=error source=virtcontainers subsystem=qmp
FAIL	github.com/kata-containers/runtime/virtcontainers	3.140s
```

Also restarted initrd CI which appeared to have a transitory error.

**Comment by grahamwhaley** [comment]
@awprice - nothing preventing the backport apart from time and effort I think.
Thanks @jodh-intel for kicking the CI tyres - let's keep an eye on this, and /cc @ganeshmaharaj @jcvenegas @egernst to discuss v1.7 stable release timeline etc.

**Comment by grahamwhaley** [comment]
@chavafg - are Power and ARM known failures right now? Ah, I know ARM is - let me see if I can trigger just-power, which is up I think
/test-power

**Comment by chavafg** [comment]
seems like passphrase didnt work, let me take a look

**Comment by amshinde** [comment]
This is the failure on PPC:
```
--- FAIL: TestQemuPPC64leMemoryTopology (0.00s)
    assertions.go:239: 
                          
	Error Trace:	qemu_ppc64le_test.go:52
        
	Error:      	Not equal: 
        
	            	expected: qemu.Memory{Size:"120M", Slots:0xa, MaxMem:"2048M", Path:""}
        
	            	actual: qemu.Memory{Size:"120M", Slots:0xa, MaxMem:"33280M", Path:""}
        
	            	
        
	            	Diff:
        
	            	--- Expected
        
	            	+++ Actual
        
	            	@@ -3,3 +3,3 @@
        
	            	  Slots: (uint8) 10,
        
	            	- MaxMem: (string) (len=5) "2048M",
        
	            	+ MaxMem: (string) (len=6) "33280M",
        
	            	  Path: (string) ""
```
cc @nitkon in case he has any idea about this failure

**Comment by egernst** [comment]
thanks for opening this @fupan -- we ended up pulling them in in another PR. I think this PR can be closed.

**Pull request closed without merging**
