### PR TITLE
versions: Update firecracker to 0.21.3

### PR DESCRIPTION
**Pull request by amshinde**
In addition to features related to gathering metrics around
several data-points, the releases leading to this release
carry a few secirty fixes.
Lets update to latest fircracker release.

References:
https://github.com/firecracker-microvm/firecracker/issues/2057
https://github.com/firecracker-microvm/firecracker/issues/2177

Fixes: #3095

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Review by egernst — APPROVED** [review]

**Comment by amshinde** [comment]
Note, this release contains all the outstanding security fixes. I havent update to firecracker latest 0.23.1 in this PR as it looks it may require certain changes on the runtime side. Will address that in a future PR.

**Comment by amshinde** [comment]
@devimc @fidencio @jcvenegas Can I get an ack on this one?

**Review by jcvenegas — APPROVED** [review]

**Pull request merged**
