### PR TITLE
virtcontainers: just a debug

### PR DESCRIPTION
**Pull request by lifupan**
Just a debug for #1970, please don't merge.

Fixes:#1970

Signed-off-by: lifupan <lifupan@gmail.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
hi @lifupan 
just a note - if you only need this to run a single CI distro check whilst you are testing, maybe you can use `/test-ubuntu` or similar - that will save running all the CIs, which will consume more resource ;-)

**Comment by lifupan** [comment]
> hi @lifupan
> just a note - if you only need this to run a single CI distro check whilst you are testing, maybe you can use `/test-ubuntu` or similar - that will save running all the CIs, which will consume more resource ;-)

Oh, yes I only need  one, thanks!

**Comment by chavafg** [comment]
you can use `/test-fc`

**Comment by lifupan** [comment]
> you can use `/test-fc`

Got it, thanks!

**Comment by lifupan** [comment]
> you can use `/test-fc`

@chavafg, where can I find the test trigger for other distros, such as opensuse?

**Comment by grahamwhaley** [comment]
@lifupan - there is a wiki page that should list them all:
https://github.com/kata-containers/community/wiki/Controlling-the-CI#specific-job-triggers
**but**, I'm not sure if it is upto date.
The other method to check is to look for `TriggerPhrase` in the job jenkins xml :-(
https://github.com/kata-containers/ci/blob/master/jenkins/jobs/kata-containers-runtime-opensuse-15-PR/config.xml#L74

```xml
      <triggerPhrase>.*(\n|^|\s)/(re)?test(\n|$|\s)+.*</triggerPhrase>
```

Looks like (if that file is upto date) that there is no specific opensuse CI trigger phrase .... yet...
For example, the ubuntu one looks like:

```xml
     <triggerPhrase>.*(\n|^|\s)/(re)?test(-ubuntu)?(\n|$|\s)+.*</triggerPhrase>
```

**Comment by lifupan** [comment]
> @lifupan - there is a wiki page that should list them all:

@grahamwhaley Thanks, yup, there is no specific trigger for opensuse.

**Pull request closed without merging**
