### PR TITLE
qemu: Set govmmQemu NoReboot Knob

### PR DESCRIPTION
**Pull request by merwick**
The Kata architecture does not support rebooting VMs (the lifecycle being start/exec/kill) and if a VM is killed (e.g. using sysrq-trigger), the VM does not exit fully and other layers do not notice the state change.

The QEMU instance needs to be told to exit and not reboot which can be done by passing the --no-reboot command line option when creating the VM.

Fix for  #2866

### CODE REVIEW

**Comment by merwick** [comment]
Marking as WIP - TestQemuKnobs needs more work

**Comment by merwick** [comment]
@devimc @amshinde Thanks for taking a look at the first version.  Since you approved it, I have added another commit that added TestQemuKnobs with tests for the pre-existing code (fixing the initial logic) and then the fix for #2866 just adds a line testing the NoReboot var introduced.

**Comment by devimc** [comment]
thanks @merwick  lgtm

@jongwu does ARM support `--no-reboot` ?

**Comment by merwick** [comment]
The--no-reboot option is a universal one. From QEMU source https://git.qemu.org/?p=qemu.git;a=blob;f=qemu-options.hx;h=708583b4ce0b627bf5f74f9da6cde41d8b98fe56;hb=5772f2b1fc5d00e7e04e01fa28e9081d6550440a#l3844

```
DEF("no-reboot", 0, QEMU_OPTION_no_reboot, \
    "-no-reboot      exit instead of rebooting\n", QEMU_ARCH_ALL)
```
and it's present on ARM

```
# /usr/bin/qemu-system-aarch64 --version
QEMU emulator version 2.11.1(qemu-2.11.1-4.el7)
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers
# /usr/bin/qemu-system-aarch64 --machine virt --no-reboot
VNC server running on ::1:5900
^C
# 
```

**Comment by devimc** [comment]
thanks @merwick

**Pull request merged**
