### PR TITLE
[stable-1.11] Backport #3005

### PR DESCRIPTION
**Pull request by fidencio**
Would be good to get this one merged for the 1.11.5 release.

It's been merged Yesterday, and as Today is a Holiday in ~~Cambodia~~ France I'm doing the backport of @c3d series.

By the way, not all patches applied cleanly, so would be good if someone could carefully take a look at this series.

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @fidencio.

**Comment by fidencio** [comment]
- **jenkins-ci-rhel-8-q35**:
```
Step 1/11 : From docker.io/fedora:30
30: Pulling from library/fedora
401909e6e2aa: Pulling fs layer
401909e6e2aa: Verifying Checksum
401909e6e2aa: Download complete
401909e6e2aa: Pull complete
Digest: sha256:3a0c8c86d8ac2d1bbcfd08d40d3b757337f7916fb14f40efcb1d1137a4edef45
Status: Downloaded newer image for fedora:30
 ---> 177d5adf0c6c
Step 2/11 : RUN dnf -y update && dnf install -y     autoconf     automake     binutils     chrony     cmake     coreutils     curl     curl     gcc     gcc-c++     git     glibc-common     glibc-devel     glibc-headers     glibc-static     glibc-utils     libseccomp     libseccomp-devel     libstdc++-devel     libstdc++-static     m4     make     pkgconfig     sed     systemd     tar     vim     which
 ---> Running in 4fc9a685c692
Fedora Modular 30 - x86_64                      0.0  B/s |   0  B     01:00    
Errors during downloading metadata for repository 'fedora-modular':
  - Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-30&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
Error: Failed to download metadata for repo 'fedora-modular': Cannot prepare internal mirrorlist: Curl error (6): Couldn't resolve host name for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-30&arch=x86_64 [Could not resolve host: mirrors.fedoraproject.org]
The command '/bin/sh -c dnf -y update && dnf install -y     autoconf     automake     binutils     chrony     cmake     coreutils     curl     curl     gcc     gcc-c++     git     glibc-common     glibc-devel     glibc-headers     glibc-static     glibc-utils     libseccomp     libseccomp-devel     libstdc++-devel     libstdc++-static     m4     make     pkgconfig     sed     systemd     tar     vim     which' returned a non-zero code: 1
Failed at 126: sudo -E AGENT_INIT="${AGENT_INIT}" AGENT_VERSION="${agent_commit}" GOPATH="$GOPATH" USE_DOCKER=true OS_VERSION=${os_version} ./rootfs-builder/rootfs.sh "${distro}"
Failed at 26: "${cidir}/install_kata_image.sh" "${tag}"
Build step 'Execute shell' marked build as failure
```
@GabyCT, @jcvenegas, @chavafg, is this known to happen? do we have an issue about this already?

**Comment by fidencio** [comment]
@chavafg, @jcvenegas, just for the record, the issue above seems like a flake.  I couldn't  reproduce it locally, at least.
Regardless, fedora:30 has reached its EOL, we should start thinking about doing our tests either with rawhide (which is not exactly stable, but won't require updates), but latest stable version (which would require updates every six months).

**Pull request merged**
