### PR TITLE
docs: README: Minor grammatical updates

### PR DESCRIPTION
**Pull request by grahamwhaley**
Minor updates on some wording and clarificaitons.

Fixes: #2144

Signed-off-by: Graham Whaley <graham.whaley@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
/test
Replaces the stuck #2143, and adds a couple more tweaks.

**Comment by GabyCT** [comment]
The ARM CI failed with
```
ERROR: Document vendor/github.com/containernetworking/plugins/plugins/main/windows/CONTRIBUTORS.md is not referenced
```

**Comment by chavafg** [comment]
weird error on ARM:
```
05:08:49 ERROR: Document vendor/github.com/containernetworking/plugins/plugins/main/windows/CONTRIBUTORS.md is not referenced
```
the check passed on travis, but not here and it is checking a vendored file, so we should skip those, right? 
should we add the vendored files to: https://github.com/kata-containers/tests/blob/master/.ci/static-checks.sh#L640-L648 ?
/cc @jodh-intel

**Comment by grahamwhaley** [comment]
wrt the ARM CI failure, I checked the code, and yes, all vendor files should be skipped. The only theory I can come up with is that maybe the tests repo is not being updated on that bare metal node? It could be this [recent commit to the static checks](https://github.com/kata-containers/tests/pull/2164) that is the difference - as that was a change (fix) to the skip path handling....
Looking at the jenkins logs, it does look like the Jenkins workspace is removed between runs, and the tests repo is checked out clean for each run - so, I don't know!!!
/cc @Pennyzct @chavafg

**Comment by amshinde** [comment]
We know why ARM CI is failing and this change related to docs should not cause any failures.
Merging this.

**Pull request merged**
