### PR TITLE
# Kata Containers 1.6.7

### PR DESCRIPTION
**Pull request by bergwolf**
- versions: update kernel to 4.19.52

e338110 versions: update kernel to 4.19.52

### CODE REVIEW

**Comment by bergwolf** [comment]
travis failed with
```
ERROR: Invalid URL 'https://github.com/kubernetes/community/blob/master/contributors/devel/container-runtime-interface.md' found in the following files:

virtcontainers/README.md
```
The same link exists in master as well but CI succeeds there. Is there some special handling needed here? @grahamwhaley @jodh-intel

**Comment by jodh-intel** [comment]
@bergwolf - That link is indeed incorrect so the URL checker is working properly:

```sh
$ curl -sIL https://github.com/kubernetes/community/blob/master/contributors/devel/container-runtime-interface.md
HTTP/1.1 200 Connection established

HTTP/1.1 404 Not Found
```

The last time `virtcontainers/README.md` changed in `master` (which would have triggered a URL check) was 2019-06-12. Looking on the wayback machine for the invalid URL:

- https://web.archive.org/web/*/https://github.com/kubernetes/community/blob/master/contributors/devel/container-runtime-interface.md

... it was last indexed by archive.org on 2019-06-03 and the cached contents showed:

```
This file has moved to https://git.k8s.io/community/contributors/devel/sig-node/container-runtime-interface.md.

This file is a placeholder to preserve links. Please remove after 2019-07-01 or the release of kubernetes 1.15, whichever comes first.
```

**Comment by bergwolf** [comment]
@jodh-intel Thanks for digging it out. Let's fix the url then.

**Pull request merged**
