### PR TITLE
snap: add snapcraft store banner

### LINKED ISSUE #1198: Add snap store banner

### PR DESCRIPTION
**Pull request by devimc**
add snapcraft store banner

fixes #1198

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by devimc** [comment]
Preview 

screenshot from 2019-01-30 15-43-38

**Comment by jodh-intel** [comment]
I agree that it's a little too prominent right at the top. It's a shame you can't make it "float right".

Also, any plans to add it to https://github.com/kata-containers/documentation/tree/master/install ?

**Comment by devimc** [comment]
@sboeuf @egernst @jodh-intel  done

screenshot from 2019-01-31 07-35-29

**Comment by jodh-intel** [comment]
@devimc - thanks for updating. This feels a bit odd to me now though as the new "Downloads" section is channeling users down a single path ("snap only") whereas we do want to highlight that the user has options.

I think having a "Downloads" section here is useful, but that should point users at https://github.com/kata-containers/documentation/tree/master/install.

So, why don't we:

- Rename "Quick start for users" to "Download and install"
- Add the snapcraft icon in that section.

Also note that you need to update the TOC at the top of the doc.

**Comment by devimc** [comment]
@jodh-intel done

**Comment by devimc** [comment]
@jcvenegas good catch!, fixed

**Pull request merged**
