### PR TITLE
test: DNM - test kernel security features

### PR DESCRIPTION
**Pull request by devimc**
test kernel security features

depends-on: github.com/kata-containers/packaging#639

fixes #1234567

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by egernst** [comment]
Finally, a fix for 1234567!

**Comment by egernst** [comment]
I appreciate the authors efforts, but this PR cannot be merged.

This still needed @devimc ?

**Comment by devimc** [comment]
@egernst nop

**Pull request closed without merging**
