### PR TITLE
Fix some error reporting in listInterfaces() and listRoutes()

### PR DESCRIPTION
**Pull request by dgibson**
See #3032 for information.

### CODE REVIEW

**Comment by dgibson** [comment]
Not sure if this is a big enough deal to require a backport.

**Review by amshinde — APPROVED** [review]

**Review by jodh-intel — APPROVED** [review]
Thanks @dgibson.

**Comment by jodh-intel** [comment]
Added backport label.

**Comment by jodh-intel** [comment]
Hi @dgibson - It looks like this hasn't been ported to 2.x (https://github.com/kata-containers/kata-containers/tree/2.0-dev/src/runtime) yet. Would you be able to look at doing that?

**Comment by dgibson** [comment]
> Hi @dgibson - It looks like this hasn't been ported to 2.x (https://github.com/kata-containers/kata-containers/tree/2.0-dev/src/runtime) yet. Would you be able to look at doing that?

Finally got around to this.  See https://github.com/kata-containers/kata-containers/issues/1206 and https://github.com/kata-containers/kata-containers/pull/1207

**Pull request merged**
