### PR TITLE
virtcontainers: Make qdisc of hotplug nics mq

### LINKED ISSUE #650: Hotplug nics don't support qdisc mq
# Description of problem
Using kata-runtime kata-network add-iface to hot plug a nic

# Expected result

Qdisc of the nic is mq as the cold plug one.

# Actual result

Qdisc of the nic is pfifo_fast.

### PR DESCRIPTION
**Pull request by caoruidong**
In order to avoid performance drop caused by qdisc. And align with
cold plug codes.

Fixes #650

### CODE REVIEW

**Comment by WeiZhang555** [comment]
Why not update govmm to latest `1a16b5f98f133796f9c5e9b6ae3aa6d786cff9b1` ?

I think this PR can merge with https://github.com/kata-containers/runtime/pull/649 , we don't need to update govmm twice

**Comment by caoruidong** [comment]
That will be fine. @woshijpf Will you take this change as part of your PR?

**Comment by woshijpf** [comment]
@caoruidong Ok,I will merge your change in kata-runtime into my PR #649

**Comment by caoruidong** [comment]
@woshijpf Thanks. Close this.

**Pull request closed without merging**
