### PR TITLE
vendor: update govmm

### PR DESCRIPTION
**Pull request by alicefr**
s389x doesn't support dimm and we need to skip it.

Fixes: #2003

detail commit change:

9463486 s390x: dimm not supported

Signed-off-by: Alice Frosi <afrosi@de.ibm.com>

### CODE REVIEW

**Comment by alicefr** [comment]
@jschintag

**Comment by jschintag** [comment]
@alicefr You need to write `Fixes: #2003` instead of `Fix: #2003`

**Comment by jodh-intel** [comment]
Hi @alicefr - thanks for raising. Please can you modify the commit message to list the commits you are introducing from `govmm` as explained here:

- https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#re-vendor-prs

**Comment by alicefr** [comment]
@jodh-intel thanks!Update the commit message

**Pull request merged**
