### PR TITLE
Stable 1.10 backports

### PR DESCRIPTION
**Pull request by jcvenegas**

### CODE REVIEW

**Review by amshinde — APPROVED** [review]

**Comment by jcvenegas** [comment]
Virtiofs CI keeps failing in tests,  https://github.com/kata-containers/tests/blob/stable-1.10/integration/kubernetes/k8s-block-volume.bats#L54  I will remove virtiofs backports from here.

**Review by fidencio — APPROVED** [review]
lgtm, thanks @jcvenegas!

**Pull request merged**
