### PR TITLE
virtcontainers: Fix error message in mockHypervisor

### PR DESCRIPTION
**Pull request by andreabolognani**
Clearly a result of copy&paste :)

### CODE REVIEW

**Comment by grahamwhaley** [comment]
thanks @andreabolognani - looks like you also nailed almost all the format requirements for the PR - apart from, I think you need a `Fixes: #nnnn` in the commit - I have opened Issue #2424 for you to add a reference to ;-)

**Comment by devimc** [comment]
thanks @andreabolognani for raising this, please fix your commit message, take a look https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#general-format

**Comment by andreabolognani** [comment]
Sorry, I had not realized having an issue connected to the change was a strict requirement. To better comply with the expected format, I've added a slightly longer explanation of the original issue as well.

**Pull request merged**
