### PR TITLE
vendor: update govmm to be compatible with qemu 2.8 to stable 1.1 branch

### PR DESCRIPTION
**Pull request by woshijpf**
backport from commit-id: f841e89d in master branch to stable-1.1 branch

govmm has ExecuteBlockdevAdd() function and ExecuteBlockdevDel() function
doesn't compatible with qemu 2.8,because blockdev-add and x-blockdev-del usages
are different between qemu 2.7 and qemu 2.8

shortlog:

    ce070d1 govmm: modify govmm to be compatible with qemu 2.8
    0286ff9 qemu/qmp: support hotplug a nic whose qdisc is mq
    8515ae4 qmp: Remind users that you must first call ExecuteQMPCapabilities()
    21504d3 qemu/qmp: Add netdev_add with chardev support
    ed34f61 Add some negative test cases for qmp.go
    17cacc7 Add negative test cases for qemu.go
    2706a07 qemu: Use the supplied context.Context for launching
    e46092e qemu: Do not try and generate invalid RTC parameters
    fcaf61d qemu/qmp: add vfio mediated device support
    4461c45 disk: Add --share-rw option for hotplugging disks
    6851999 qemu/qmp: add addr and bus to hotplug vsock devices
    10efa84 qemu/qmp: add function for hotplug network by fds
    80ed88e qemu/qmp: implement function to hotplug serial ports
    ca46f21 qemu/qmp: implement function to hotplug character devices
    03f1a1c qemu/qmp: implement getfd
    84b212f qemu: add vhostfd and disable-modern to vsock hotplug
    12dfa87 qemu/qmp: implement function for hotplug network
    3830b44 qemu: add vhostfd and disable-modern to vhost-vsock-pci
    f700a97 qemu/qmp: implement function to hotplug vsock-pci
    4ca232e qmp_test: Fix Warning and Error level logs
    430e72c qemu,qmp: Enable gas security checker
    ffc06e6 qemu,qmp: Add staticcheck to travis and fix errors
    54caf78 qmp: add hotplug memory
    e66a9b4 qemu: add appendMemoryKnobs helper
    8aeca15 qmp: add migrate set arguments
    a03d496 qmp: add set migration capabilities
    0ace417 qemu: allow to set migration incoming
    723bc5f qemu: allow to create a stopped guest
    283d7df qemu: add file backed memory device support

fixes: #637

Signed-off-by: flyflypeng <jiangpengfei9@huawei.com>

### CODE REVIEW

**Comment by woshijpf** [comment]
follow the backport [suggestion](https://github.com/kata-containers/runtime/pull/649#issuecomment-421070703) by @sboeuf

**Comment by jodh-intel** [comment]
lgtm

**Comment by jodh-intel** [comment]
Thanks for these PRs @woshijpf! :smile:

**Comment by grahamwhaley** [comment]
CIs are all happy. I'd normally wait for @sboeuf , but, things are green, looks like the backport request was from @sboeuf , so merging...

**Pull request merged**
