### PR TITLE
# Kata Containers 1.11.1

### PR DESCRIPTION
**Pull request by amshinde**
- Backports for log fixes
- vc: make host shared path readonly

a74e194d shm: handle shm mount backed by empty-dir memory volumes
673b471e virtcontainers: Fix structured logging in device/config package
13887bf8 logging: Fix structured logging in store package
0042823f vc: make host shared path readonly

### CODE REVIEW

**Comment by jodh-intel** [comment]
Travis is failing with what looks like a timing issue as the agent repo looks correct now:

```
INFO: Tagging Kata Containers with version 1.11.1
INFO: Check all repos has version 1.11.1 in VERSION file
INFO: agent is in 1.11.0
ERROR: agent is not in version 1.11.1
```

I don't see the usual Travis "restart build" button today though !?!

**Comment by amshinde** [comment]
@jodh-intel I restarted Travis after all other version bump PRs have been merged. I couldnt see the restart button myself, but I logged out and logged back in, that seemed to have fixed it.

Here is the travis build link: https://travis-ci.org/github/kata-containers/runtime/builds/695089715
The amd64 job passed, but the ppc64le job seems to be stuck even after being restarted a couple of times. I have seen that today on a couple of other PRs as well.

**Comment by amshinde** [comment]
Ok, the ppc job seems to be making some progress now.

**Pull request merged**
