### PR TITLE
blk-dev: hotplug read only if applicable

### PR DESCRIPTION
**Pull request by egernst**
If a volume is backed by a block device, let's make sure we take into account whether it should be hot plugged RO or not.

While updating this, I made some minor non-functional changes to correct comments, make storage handling a bit more clear.

### CODE REVIEW

**Comment by jodh-intel** [comment]
Marking as dnm due to vendor change.

@egernst - I'm slightly surprised this is being raised on 1.x - is this correct?

**Comment by egernst** [comment]
It is correct. I'll be back porting to stable and forward to 2.0 as well. I think we'll want to update our vendoring to be consistent between these.

**Review by bergwolf — APPROVED** [review]
lgtm!

**Comment by egernst** [comment]
Minor update to fix pmem test failures.

**Review by mxpv — APPROVED** [review]
LGTM

**Pull request merged**
