### PR TITLE
versions: kernel: update to 4.19.28

### PR DESCRIPTION
**Pull request by ganeshmaharaj**
Update kernel to latest version.

Fixes: #1288

Signed-off-by: Graham Whaley <graham.whaley@intel.com>
(cherry picked from commit ae4d8b453e9fbc9cc068f1a01f25d8d935c24bae)
Signed-off-by: Ganesh Maharaj Mahalingam <ganesh.mahalingam@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
/test
I think that works for stable ...?

**Comment by grahamwhaley** [comment]
ARM CI seems to have failed on a kata-env vsock check:
```
19:33:35 --- FAIL: TestEnvGetEnvInfoSetsCPUType (0.02s)
19:33:35     assertions.go:239: 
                          
	Error Trace:	kata-env_generic_test.go:48
19:33:35         
	            	
			kata-env_arm64_test.go:98
19:33:35         
	Error:      	Not equal: 
19:33:35         
	            	expected: main.EnvInfo{Meta:main.MetaInfo{Version:"1.0.20"}, Runtime:main.RuntimeInfo{Version:main.RuntimeVersionInfo{Semver:"1.5.4", Commit:"c8dd8e1c73b61c68f4a62a7ca7d379172dd08b7e", OCI:"1.0.1-dev"}, Config:main.RuntimeConfigInfo{Path:"/tmp/039475901/runtime.toml"}, Debug:false, Trace:false, DisableGuestSeccomp:false, DisableNewNetNs:false, Path:"/tmp/go-build681379042/b001/cli.test"}, Hypervisor:main.HypervisorInfo{MachineType:"machineType", Version:"QEMU emulator version 2.7.0+git.741f430a96-6.1, Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers", Path:"/tmp/039475901/hypervisor", BlockDeviceDriver:"virtio-scsi", EntropySource:"/dev/urandom", Msize9p:0x2000, MemorySlots:0xa, Debug:false, UseVSock:false}, Image:main.ImageInfo{Path:"/tmp/039475901/image"}, Kernel:main.KernelInfo{Path:"/tmp/039475901/kernel", Parameters:"init=/usr/lib/systemd/systemd systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket foo=bar xyz"}, Initrd:main.InitrdInfo{Path:""}, Proxy:main.ProxyInfo{Type:"kataProxy", Version:"proxy version 0.1", Path:"/tmp/039475901/proxy", Debug:false}, Shim:main.ShimInfo{Type:"kataShim", Version:"shim version 0.1", Path:"/tmp/039475901/shim", Debug:false}, Agent:main.AgentInfo{Type:"kata"}, Host:main.HostInfo{Kernel:"99.1", Architecture:"arm64", Distro:main.DistroInfo{Name:"Foo", Version:"42"}, CPU:main.CPUInfo{Vendor:"ARM Limited", Model:"v8"}, VMContainerCapable:true, SupportVSocks:false}, Netmon:main.NetmonInfo{Version:"netmon version 0.1", Path:"/tmp/039475901/netmon", Debug:false, Enable:false}}
19:33:35         
	            	actual: main.EnvInfo{Meta:main.MetaInfo{Version:"1.0.20"}, Runtime:main.RuntimeInfo{Version:main.RuntimeVersionInfo{Semver:"1.5.4", Commit:"c8dd8e1c73b61c68f4a62a7ca7d379172dd08b7e", OCI:"1.0.1-dev"}, Config:main.RuntimeConfigInfo{Path:"/tmp/039475901/runtime.toml"}, Debug:false, Trace:false, DisableGuestSeccomp:false, DisableNewNetNs:false, Path:"/tmp/go-build681379042/b001/cli.test"}, Hypervisor:main.HypervisorInfo{MachineType:"machineType", Version:"QEMU emulator version 2.7.0+git.741f430a96-6.1, Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers", Path:"/tmp/039475901/hypervisor", BlockDeviceDriver:"virtio-scsi", EntropySource:"/dev/urandom", Msize9p:0x2000, MemorySlots:0xa, Debug:false, UseVSock:false}, Image:main.ImageInfo{Path:"/tmp/039475901/image"}, Kernel:main.KernelInfo{Path:"/tmp/039475901/kernel", Parameters:"init=/usr/lib/systemd/systemd systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket foo=bar xyz"}, Initrd:main.InitrdInfo{Path:""}, Proxy:main.ProxyInfo{Type:"kataProxy", Version:"proxy version 0.1", Path:"/tmp/039475901/proxy", Debug:false}, Shim:main.ShimInfo{Type:"kataShim", Version:"shim version 0.1", Path:"/tmp/039475901/shim", Debug:false}, Agent:main.AgentInfo{Type:"kata"}, Host:main.HostInfo{Kernel:"99.1", Architecture:"arm64", Distro:main.DistroInfo{Name:"Foo", Version:"42"}, CPU:main.CPUInfo{Vendor:"ARM Limited", Model:"v8"}, VMContainerCapable:true, SupportVSocks:true}, Netmon:main.NetmonInfo{Version:"netmon version 0.1", Path:"/tmp/039475901/netmon", Debug:false, Enable:false}}
19:33:35         
	            	
19:33:35         
	            	Diff:
19:33:35         
	            	--- Expected
19:33:35         
	            	+++ Actual
19:33:35         
	            	@@ -67,3 +67,3 @@
19:33:35         
	            	   VMContainerCapable: (bool) true,
19:33:35         
	            	-  SupportVSocks: (bool) false
19:33:35         
	            	+  SupportVSocks: (bool) true
19:33:35         
	            	  },
```

and our fedora-vsock has failed. Not sure if those are relevant?

**Comment by jodh-intel** [comment]
>  this was discussed to check if it was a valid thing to do for a stable branch.

@grahamwhaley - Can you provide a reference to where + when this was discussed please? :smile:

@egernst, @gnawux - Do you think we need to document our approach to backporting kernel versions in https://github.com/kata-containers/documentation/blob/master/Stable-Branch-Strategy.md ?

**Comment by jodh-intel** [comment]
@ganeshmaharaj - As a general comment, please could you add more detail to your commits?

It may be technically redundant in some cases, but we try to ensure that -- in addition to the SoB and a `FIXES ###` issue reference -- every commit summarises what changed and why. This helps with later "data archaeology" and can be an aid if English is not your first language to understand the change.

**Comment by grahamwhaley** [comment]
@jodh-intel - iirc it was on one of the ephereral channels - slack or irc... so, no permaref I'm afraid. It's a brave new world of fast moving social media out there....

**Comment by jodh-intel** [comment]
Wow, progress eh?

**Comment by ganeshmaharaj** [comment]
> @ganeshmaharaj - As a general comment, please could you add more detail to your commits?
> 
Will do @jodh-intel. I miss providing this only if the single liner is sufficient to explain what is being changed. I guess it won't hurt to put down the 'why' for such a change like this in the msg.

> It may be technically redundant in some cases, but we try to ensure that -- in addition to the SoB and a `FIXES ###` issue reference -- every commit summarises what changed and why. This helps with later "data archaeology" and can be an aid if English is not your first language to understand the change.

**Comment by grahamwhaley** [comment]
waha - [4.19.38](https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.19.38) is now available. @ganeshmaharaj - you want to update this, or race against the 5.x update. Probably best we update and land this in the interim you think?

**Comment by ganeshmaharaj** [comment]
@grahamwhaley last time we tried moving to 4.19.34 it failed the CI and Eric had to roll it back. Land this and all the other bits in transit and then bump the version would be safer.

**Comment by jodh-intel** [comment]
Ping @ganeshmaharaj.

**Comment by ganeshmaharaj** [comment]
With the last release of 1.5 complete, i doubt this PR is valid anymore. Closing it out!

**Pull request closed without merging**
