### PR TITLE
versions: bump conmon version to v2.0.5

### PR DESCRIPTION
**Pull request by haircommander**
in hopes the old failures were fixed, and to investigate them if not
if passes, this will fix: https://github.com/kata-containers/tests/issues/2271

Signed-off-by: Peter Hunt <pehunt@redhat.com>

### CODE REVIEW

**Comment by amshinde** [comment]
So I see the ubuntu tests are failing with the same reason that we saw earlier.
@haircommander Have a look at https://github.com/kata-containers/runtime/issues/2352#issuecomment-565642204

**Comment by haircommander** [comment]
(starting to pin down where it failed)

**Comment by chavafg** [comment]
Job failed on other (flaky?) tests, but cri-o passed OK. 

We started to see the issue with conmon on Dec 11, and conmon v2.0.5 was released on Dec 10. I think this could be the version that started to give problems to us.

**Comment by haircommander** [comment]
looks like cri-o tests are going to pass. we can live with 2.0.5 for now (it has the changes needed to make cri-o tests pass again), though I don't want to lose track of the fact we're not following conmon master. I'll make an issue here after this closes :)

**Comment by haircommander** [comment]
PTAL @chavafg @amshinde @devimc

**Pull request merged**
