### PR TITLE
virtcontainers: Return the appropriate container status

### LINKED ISSUE #926: Moving to Docker 18.09 does not delete the VM and proxy when the container terminates
We usually expect `docker` to monitor the shim process representing the container process inside the VM. And by doing so, it sends a `kata-runtime delete <container-id>` when it sees the shim going away. But unfortunately, something changed between `18.06` and `18.09` that prevents this logic from working as expected here.

Reference on docker repo: https://github.com/moby/moby/issues/38233

/cc @amshinde @egernst @grahamwhaley @jodh-intel

### PR DESCRIPTION
**Pull request by sboeuf**
When our runtime is asked for the container status, we also handle
the scenario where the container is stopped if the shim process for
that container on the host has terminated.

In the current implementation, we retrieve the container status
before stopping the container, causing a wrong status to be returned.
The wait for the original go-routine's completion was done in a defer
within the caller of statusContainers(), resulting in the
statusContainer()'s values to return the pre-stopped value.

This bug is first observed when updating to docker v18.09/containerd
v1.2.0. With the current implementation, containerd-shim receives the
TaskExit when it detects kata-shim is terminating. When checking the
container state, however, it does not get the expected "stopped" value.

The following commit resolves the described issue by simplifying the
locking used around the status container calls. Originally
StatusContainer would request a read lock. If we needed to update the
container status in statusContainer, we'd start a go-routine which
would request a read-write lock, waiting for the original read lock to
be released.  Can't imagine a bug could linger in this logic. We now
just request a read-write lock in the caller (StatusContainer),
skipping the need for a separate go-routine and defer. This greatly
simplifies the logic, and removes the original bug.

Fixes #926

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Comment by amshinde** [comment]
@sboeuf Any reason why this was opened when you have #977 open?

**Comment by sboeuf** [comment]
@amshinde #977 is on `stable-1.3` and #978 is on `stable-1.4` ;)

**Comment by jodh-intel** [comment]
lgtm

**Comment by jcvenegas** [comment]
Seems that centos failing with a timeout, restarting but I've seen this same error on different PRs now
```
Running command '/usr/local/bin/kata-runtime [kata-runtime --log=/tmp/bundle938849770/log run --console= --pid-file=/tmp/bundle938849770/pid AsJvY9fDD1MTRdIX9Urd]'
command failed error 'exit status 1'
[kata-runtime --log=/tmp/bundle938849770/log run --console= --pid-file=/tmp/bundle938849770/pid AsJvY9fDD1MTRdIX9Urd]
Timeout: 60 seconds
Exit Code: 1
```

**Comment by jcvenegas** [comment]
restart again

```
HEAD is now at fa540c8... Merge pull request #1913 from runcom/fix-devmapper-112
M	Makefile
/tmp/jenkins/workspace/kata-containers-runtime-centos-7-4-PR/go/src/github.com/kata-containers/tests
/tmp/jenkins/workspace/kata-containers-runtime-centos-7-4-PR/go/src/github.com/kubernetes-sigs/cri-o/test /tmp/jenkins/workspace/kata-containers-runtime-centos-7-4-PR/go/src/github.com/kata-containers/tests
Ensure crio service is stopped before running the tests
Ensure docker service is stopped before running the tests
helpers.bash: line 128: /tmp/jenkins/workspace/kata-containers-runtime-centos-7-4-PR/go/src/github.com/kubernetes-sigs/cri-o/test/copyimg/copyimg: No such file or directory
Error pulling quay.io/crio/redis
make: *** [crio] Error 1
```

**Pull request merged**
