### PR TITLE
iothread support for virtio-scsi

### PR DESCRIPTION
**Pull request by amshinde**
With qemu iothreads, it is possible to have a separate thread to handle IO. This results in lower IO latencies and better throughput.

### CODE REVIEW

**Comment by amshinde** [comment]
Depends on https://github.com/intel/govmm/pull/14

**Comment by amshinde** [comment]
@sboeuf @chavafg The CI failed due to some network issue. Can you restart the build, as it looks like I cannot do it.

**Comment by sboeuf** [comment]
@amshinde done

**Comment by amshinde** [comment]
@sboeuf @egernst @jodh-intel  @laijs @bergwolf ptal

**Comment by devimc** [comment]
sweet! lgtm

**Comment by jodh-intel** [comment]
lgtm.

/cc @markdryan.

Also, we should run the metrics CI on it to ensure we see the expected behaviour (/cc @grahamwhaley).

**Comment by egernst** [comment]
change looks good to me, though I'd want an ACK from either @bergwolf @WeiZhang555 or @laijs 

Can ya'll PTAL and consider merging?

**Comment by amshinde** [comment]
I have tested the performance locally with FIO tool and I have seen close to 120% increase in storage performance for linear and random reads and a 97% increase for random writes with using iothreads.

**Comment by bergwolf** [comment]
lgtm!

**Pull request merged**
