### PR TITLE
Add missing docs

### LINKED ISSUE #1681: Add missing documentation
This repo is missing a few documents to allow all documentation in the repo to be navigated.

### PR DESCRIPTION
**Pull request by jodh-intel**
Add a few minimal documents to allow all the documentation in this repository to be navigated from the top-level README.

Fixes #1681.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
@marcov - could you tal please? This is a doc-only PR so I think we can merge once we have one more ack ;)

**Comment by jodh-intel** [comment]
Thanks @marcov.

@grahamwhaley - looks like the zuul checks have stalled?

**Comment by grahamwhaley** [comment]
hmm, @jodh-intel once in a while we see a stall, and then they magically appear (they do have some sort of priority queue on the zuul CI node infra, but just once in a while we see them get stuck, maybe at a particularly busy time). Still, Monday morning I would not think to be that busy. Maybe there is some other issue. Give it 1h, and then I'll come and check and see what I can find.

**Comment by grahamwhaley** [comment]
@jodh-intel yep, i think Zuul things have stalled.
Looking at https://zuul.opendev.org/t/kata-containers/builds?pipeline=SoB-check - we have had 3 SoB checks run today.
If we clear the filter, we've only had 5 items run https://zuul.opendev.org/t/kata-containers/builds today.
I don't see any issues on the [status page](https://zuul.opendev.org/t/kata-containers/status), but nor do I know how well that ties into the higher levels of infra.
/cc @ttx @cboylan - any known issues with Zull infra, github, Kata at present?

**Comment by jodh-intel** [comment]
@grahamwhaley - It's still blocked :(

We really need to find a way to force-override issues like this. Is there anything we can do aside from restart all the CI tests I wonder?

**Comment by grahamwhaley** [comment]
`¯\_(ツ)_/¯` - 'required' CIs are by definition required, and all CIs have their moments of being flaky. It's not just Zuul, we've had this with Jenkins and Travis and semaphore and pullapprove. It's literally only been a few hours - let the west coast wake up and see where we get to.

**Comment by jodh-intel** [comment]
@grahamwhaley - I was waiting for that response. Yes. I do get that :smile: But -- as we're seeing -- the world is not always perfect and we (well, some of us) need a way to bypass the automatic checks when problems occur. These two particular checks which are blocking a trivial doc-only PR are themselves trivial and could easily be manually by simply looking at the commits at worst. But that doesn't work today - we have to wait, wait, waaaaaaaaait...

**Comment by jodh-intel** [comment]
RHEL 7 CI failing with a consistent network timeout issue:

```
time="2019-05-16T10:56:06Z" level=error msg="error copying docker://quay.io/crio/redis:alpine to dir:/tmp/jenkins/workspace/kata-containers-runtime-rhel-7-PR/go/src/github.com/cri-o/cri-o/.artifacts/redis-image: Error reading blob sha256:ff3a5c916c92643ff77519ffa742d3ec61b7f591b6b7504599d95a4a41134e28
    :  
dial tcp 13.32.84.96:443: i/o timeout" 
Error pulling quay.io/crio/redis
```

**Comment by jodh-intel** [comment]
Hi @cboylan - this PR is the only one I've noticed but maybe others have more info...?

**Comment by cboylan** [comment]
zuul-recheck

**Comment by jodh-intel** [comment]
@cboylan - thanks! I'll have to remember that one... ;)

**Comment by cboylan** [comment]
Ok I think that Zuul either missed these events or there were github errors when trying to process them a few days back. The recheck seems to have worked fine once I Figured out the correct string to use there. (I'm told by other zuul + github users that if github is having a sad then zuul may eventually give up retrying and effectively lose an event).

Hopefully this gets you moving again. In general I think it is safe to try a recheck if you don't see anything queued up for a PR in the status page. Also Zuul will dedup anyway so safe to over recheck too.

**Comment by jodh-intel** [comment]
Nice - thanks again @cboylan.

**Comment by grahamwhaley** [comment]
:-) It is documented on the [SoB wiki page](https://github.com/kata-containers/community/wiki/The-SoB-check#this-looks-like-a-transient-failure-how-can-i-ask-the-tests-to-run-again-) in the section `this-looks-like-a-transient-failure-how-can-i-ask-the-tests-to-run-again` :-) - but, yeah, you don't get a link to the wiki pages on this PR if Zuul has failed to feed back at all - the trick is to remember you can find the link from *another* PR that has triggered ;-)

**Comment by jodh-intel** [comment]
SoB! I forgot to check the SoB wiki :)

/me sobs...

**Pull request merged**
