### PR TITLE
s390x: change pci bridge type

### PR DESCRIPTION
**Pull request by alicefr**
Fixes: #1141

Signed-off-by: Alice Frosi <afrosi@de.ibm.com>

### CODE REVIEW

**Comment by sameo** [comment]
LGTM

**Comment by sameo** [comment]
@alicefr Sorry about that one. Are there any plans to include s390 as part of our CI?

**Comment by grahamwhaley** [comment]
In progress right now @sameo - we have access to a node, and are setting it up as a jenkins slave.

**Comment by alicefr** [comment]
@grahamwhaley sorry I always forget :sweat_smile:

**Comment by jodh-intel** [comment]
lgtm

**Pull request merged**
