### PR TITLE
# Kata Containers 1.11.5

### PR DESCRIPTION
**Pull request by katabuilder**
- Stable 1.11 backports
- Backports: Read-only mount fixes for 1.11
- runtime: Call s.newStore.Destroy if globalSandboxList.addSandbox
- runtime: Don' call bindUnmountContainerRootfs for devicemapper device
- runtime: Fix /var/lib/vc/sbs/${sid} dir residual
- [backport]: virtiofs: Change to cache auto and no DAX

eca202e7 arm64: correct bridge type for QEMUVIRT machine
314bc3d6 gitignore: Ignore cli/containerd-shim-kata-v2/config-generated.go
951302fb runtime: Ignore ENOENT in kill/delete
20fcb93c hypervisor: Remove unused methods
04dc0d93 annotations: Improve asset annotation handling
a47f7b39 annotations: Add missing hypervisor control annotation
2dd0fe68 asset: Formatting, grammar and whitespace
3f0e61c0 runtime: mount shared mountpoint readonly
228e6eb4 runtime: readonly mounts should be readonly bindmount on the host
d78780cf virtiofs: Disable DAX
51d85922 virtiofsd: Use cache=auto
ad3eec50 runtime: Fix /var/lib/vc/sbs/${sid} dir residual
054c4fbd runtime: Don' call bindUnmountContainerRootfs for devicemapper device
0b7019b9 runtime: Call s.newStore.Destroy if globalSandboxList.addSandbox

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
thanks, lgtm!

**Comment by fidencio** [comment]
Ooops, went way too fast in this one. Here I also think we shoul get #3005 backported. @amshinde, what do you think? @c3d, can you provide the backport?

**Review by fidencio — CHANGES_REQUESTED** [review]
Hmm. As I can't unnaprove a PR that I approved, let me just "Request changes". :-/

**Review by chavafg — APPROVED** [review]

**Pull request merged**
