### PR TITLE
versions: update supported docker version to 18.09

### PR DESCRIPTION
**Pull request by chavafg**
Update docker to v18.09-ce

Fixes: #1110.

Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>

### CODE REVIEW

**Comment by devimc** [comment]
that means no more devicemapper?

**Comment by egernst** [comment]
I think we want to hold off until we have a block based snapshotter plug-in in place

**Comment by sboeuf** [comment]
Yes agreed that we cannot afford to move to 18.09 since they broke devicemapper, and since we don't have a backup plan yet.

**Comment by chavafg** [comment]
hmmm, right, but that would mean we wont be able to move to fedora 29, which only provides docker 18.09, unless we hack it to use the 18.06 from the fedora 28 repo.

**Comment by jodh-intel** [comment]
@egernst - one for the architecture committee meeting maybe?

**Comment by raravena80** [comment]
@chavafg any updates? Thx. Are we still waiting for the snapshotter plugin?

**Comment by chavafg** [comment]
yes, still waiting on that, I can close this in the meantime...

**Pull request closed without merging**
