### PR TITLE
Firecracker: Upgrade to 0.17.0

### PR DESCRIPTION
**Pull request by mcastelino**
Upgrade Firecracker to 0.17.0. This is required to pick up
bug fixes needed in jailer, to allow kata to run firecracker
constrained by a jailer in Kata.

Fixes: #1746

Signed-off-by: Manohar Castelino <manohar.r.castelino@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
static check failed:
```
/home/travis/gopath/src/github.com/kata-containers/runtime/virtcontainers/types
/home/travis/gopath/src/github.com/kata-containers/runtime/virtcontainers/utils
virtcontainers/fc.go:539:2: var `ctxId` should be `ctxID` (golint)
	ctxId := int64(vs.contextID)
	^
The command ".ci/static-checks.sh" failed and exited with 1 during .
```

**Comment by jodh-intel** [comment]
Travis is failing due to a static analysis issue:

```
virtcontainers/fc.go:539:2: var `ctxId` should be `ctxID` (golint)
	ctxId := int64(vs.contextID)
	^
The command ".ci/static-checks.sh" failed and exited with 1 during .
```

**Comment by mcastelino** [comment]
> How often this could be updated, I ask to probably add

@jcvenegas each time firecracker spins a new release. I thought of doing that. But that would induce potential build to build variability. So it is better to generate and check it in.

**Comment by mcastelino** [comment]
Looks like something changed in 0.17.0 due to which kata fails after container launch.

**Comment by mcastelino** [comment]
@chavafg @egernst @jodh-intel @grahamwhaley I am getting another static check error 

```
ERROR: Required license identifier ('SPDX-License-Identifier: Apache-2.0') missing from following files:
```
This is for the swagger generated code. It does not make sense to modify generated code. 
What is our policy on headers for generated code.

**Comment by mcastelino** [comment]
This passes manual testing.  The licensing issue will require a force merge or a change to the license check to exclude generated code.

**Comment by chavafg** [comment]
I think we can exclude files in this path: `virtcontainers/pkg/firecracker/*`

**Comment by mcastelino** [comment]
> I think we can exclude files in this path: `virtcontainers/pkg/firecracker/*`

@chavafg https://github.com/kata-containers/tests/pull/1755 Hopefully this will address the issue

**Comment by grahamwhaley** [comment]
/test
and restart travis to pick up the new static check.

**Comment by chavafg** [comment]
Firecracker job failed:
```
[Firecracker devtool] Build successful.
[Firecracker devtool] Build complete.
[Firecracker devtool] Binaries placed under /tmp/jenkins/workspace/kata-containers-runtime-centos-7-4-PR-firecracker/go/src/github.com/firecracker-microvm/firecracker/build/release-musl
install: cannot stat ‘/tmp/jenkins/workspace/kata-containers-runtime-centos-7-4-PR-firecracker/go/src/github.com/firecracker-microvm/firecracker/build/release/firecracker’: No such file or directory
Failed at 45: sudo install ${GOPATH}/src/${firecracker_repo}/build/release/firecracker /usr/bin/
Failed at 25: "${cidir}/install_firecracker.sh"
Build step 'Execute shell' marked build as failure
```

Seems like the path where the binaries are placed changed.

**Comment by mcastelino** [comment]
> Seems like the path where the binaries are placed changed.

@chavafg yes it has. I have pushed a patch to packaging

https://github.com/kata-containers/packaging/pull/600

Let me see where else we need the change

**Comment by mcastelino** [comment]
> Seems like the path where the binaries are placed changed.

@chavafg The tests repo has also been updated https://github.com/kata-containers/tests/pull/1757

**Comment by chavafg** [comment]
sent rebuild for firecracker job, this time it should pass

**Pull request merged**
