### PR TITLE
runtime: Add Clear Containers runtime

### PR DESCRIPTION
**Pull request by sameo**
This adds Clear Containers as a Kata Containers runtime, under
runtime/cc-runtime

The Docker `create`, `start`, `run`, `exec` and `ps` commands
work when using the cc-runtime code together with the vanilla
Kata shim, proxy and agent components. Shortly we will also
document how to build and install all of those together.

Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>

### CODE REVIEW

**Comment by sameo** [comment]
@bergwolf @gnawux @laijs @sboeuf @jodh-intel Please review.

**Comment by jodh-intel** [comment]
Thanks @sameo!

lgtm

**Comment by gnawux** [comment]
lgtm

**Comment by sboeuf** [comment]
Cool !!!

**Pull request merged**
