### PR TITLE
virtcontainers: fix not close socket with ethtool

### PR DESCRIPTION
**Pull request by Ace-Tang**
close socket after use ethtool.NewEthtool()

Fixes: #919 

Signed-off-by: Ace-Tang <aceapril@126.com>

### CODE REVIEW

**Comment by caoruidong** [comment]
lgtm

**Comment by jodh-intel** [comment]
lgtm

**Comment by Ace-Tang** [comment]
@grahamwhaley ， I also create a pr for the example https://github.com/safchain/ethtool/pull/18

**Comment by grahamwhaley** [comment]
@Ace-Tang sweeeet! - I've acked it ;-)

**Pull request merged**
