### PR TITLE
versions: update kernel version 4.14.67

### PR DESCRIPTION
**Pull request by jcvenegas**
Update kernel version to 4.14.67

Fixes: #698

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

As this might eventually affect https://github.com/kata-containers/packaging/tree/master/kernel/configs,

/cc @nitkon, @ydjainopensource, @Pennyzct, @Weichen81.

**Comment by jodh-intel** [comment]
Ignoring zuul...

**Comment by Weichen81** [comment]
@jodh-intel I have tested the kernel 4.14.67. There is not any difference between current config file and 4.14.67.

**Comment by jodh-intel** [comment]
Thanks @Weichen81!

**Pull request merged**
