### PR TITLE
env: Show virtiofsd info

### PR DESCRIPTION
**Pull request by jcvenegas**
Add virtiofs cache size and mode.

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm!

**Review by jodh-intel — COMMENTED** [review]
@jcvenegas - please can you bump `formatVersion`. Also, could you port to 2.0?

**Comment by amshinde** [comment]
@jcvenegas as @jodh-intel mentioned, `formatVersion` needs to be bumped.

**Comment by jodh-intel** [comment]
@jcvenegas - can you also port to 2.0?

**Review by jensfr — APPROVED** [review]
lgtm!

**Comment by jodh-intel** [comment]
@jcvenegas - can you also add a "fixes" comment in the commit?

**Comment by jodh-intel** [comment]
Ping @jcvenegas - this PR seems to have been forgotten ;)

**Comment by fidencio** [comment]
Folks, this PR has been stale and I'm closing it as we're walking towards the **final** 1.13.0 release of the kata-containers-1.x.
From now on, all the development will happen as part of https://github.com/kata-containers/kata-containers/ and fixes should be provided to that repo.

Thanks a lot for your contribution, we're sorry that for some reason it got stale, and we hope to see you around for new adventures in the kata-containers-2.x land.

**Pull request closed without merging**
