### PR TITLE
fix the issue of hypervisor process is killed by kubelet 

### PR DESCRIPTION
**Pull request by lifupan**
For k8s, once all of the containers in a pod terminated, the pod status would be set "Succeeded" or "Failed" according the containers exited status, in any case, kubelet would consider the pod has terminated, and would try to cleanup the pod cgroup resources, which means kubelet would kill all of the processes in the pod cgroups, thus the qemu process would be killed by accident, at a result, kata shimv2 wouldn't communicate with qemu to do some sandbox cleanup and left the shimv2 process there.

This patch will try to fix this issue by moving "stop sandbox" from deleting podsandbox container stage to the time when podsandbox container exited and before kubelet detect the podsandbox container exited, thus kubelet wouldn't kill the hypervisor process.

### CODE REVIEW

**Comment by nitkon** [comment]
@jodh-intel : Power CI errored 'cannot remove workspace' due to file permission issues. @grahamwhaley fixed the Jenkins configuration to make sure that the whole workspace of the previous job is owned by the Jenkins user so it can then delete it for the next run.

**Comment by grahamwhaley** [comment]
@egernst @lifupan @gnawux @jodh-intel - is this maybe a stable backport candidate? Sounds like a real bug that really needed fixing?

**Comment by lifupan** [comment]
> @egernst @lifupan @gnawux @jodh-intel - is this maybe a stable backport candidate? Sounds like a real bug that really needed fixing?

@grahamwhaley , yes, I think so.

**Comment by grahamwhaley** [comment]
@lifupan - great, I've added the `stable-candidate` label so we don't forget it. Would you be able to PR the stable patches? /cc @jcvenegas @ganeshmaharaj 
BTW, **great work** on tracking down and fixing this :-)

**Comment by lifupan** [comment]
> @lifupan - great, I've added the `stable-candidate` label so we don't forget it. Would you be able to PR the stable patches? /cc @jcvenegas @ganeshmaharaj
> BTW, **great work** on tracking down and fixing this :-)

Hi, @grahamwhaley  I had send three PR for stable-1.5 to stable-1.7.

**Pull request merged**
