### PR TITLE
cli: refactor the config into a separated package

### PR DESCRIPTION
**Pull request by lifupan**
Since to refactor the cli codes will be a big task, and I will try
to split it into several PRs.

This is the first PR for refactor the config related codes.

### CODE REVIEW

**Comment by lifupan** [comment]
It seems the Depends-on doesn't work, the travis is blocked by https://github.com/kata-containers/runtime/pull/869

**Comment by jshachm** [comment]
@lifupan 
Can you open an issue to clarify the purpose to refactor the `cli` and the overall plan on it~~~

**Comment by lifupan** [comment]
Hi, @jshachm
Actually I had opened it, please see https://github.com/kata-containers/runtime/issues/714,
https://github.com/kata-containers/runtime/issues/787, and
for much more info, please see the comments in https://github.com/kata-containers/runtime/pull/572

**Comment by lifupan** [comment]
test

**Comment by bergwolf** [comment]
LGTM!

@jodh-intel PTAL.

**Comment by gnawux** [comment]
LGTM

**Comment by gnawux** [comment]
Discussed on the AC meeting this week, @sboeuf will take a look as well

**Comment by sboeuf** [comment]
Just added `do-not-merge` label since I want to make sure my comments get addressed and @jodh-intel can review it before it's merged.

**Comment by egernst** [comment]
Agreed with @sboeuf feedback, though I hate nack'ing a name without suggesting a better alternative....

**Comment by lifupan** [comment]
@sboeuf  @egernst  I didn't have a  strong opinion about where and how to name this pkg, if you guys @kata-containers/runtime  don't have any better ideas, I'll name it as kata-utils and put it in pkg dir.

**Comment by WeiZhang555** [comment]
How about just `runtime/pkg/cli` ?

**Comment by sboeuf** [comment]
@WeiZhang555 
>How about just runtime/pkg/cli ?

I don't think we should use `cli` in the name, as this is a library used by `kata-containerd-shim`, which is not really a command line interface in this case.

@lifupan 

I like `kata-utils` proposal from @egernst

**Comment by lifupan** [comment]
@egernst @sboeuf  I had renamed the pkg from clilib to "katautils", since the character  "-"  is not friend to some go UI editors and I removed it and put it in pkg dir.

**Comment by sboeuf** [comment]
@lifupan you forgot to remove a bunch of file. Now we have duplicates :)
Please remove all the remaining `pkg/kata-utils/clilib/...` files.

**Comment by egernst** [comment]
looks good aside from duplicated files - let's merge once that gets updated.  Thanks @lifupan

**Comment by sboeuf** [comment]
Looks good! Thanks @lifupan for reworking this!

**Comment by lifupan** [comment]
Seems there is something wrong with the CI.

**Comment by sboeuf** [comment]
@egernst could you ack this please?

**Comment by egernst** [comment]
waiting for CI to turn green...

**Pull request merged**
