### PR TITLE
Backports for 1.7.1

### PR DESCRIPTION
**Pull request by ganeshmaharaj**
Backport patches for 1.7.1 release.

kata-containers/runtime#1665
kata-containers/runtime#1670
kata-containers/runtime#1676
kata-containers/runtime#1679
kata-containers/runtime#1691
kata-containers/runtime#1694
kata-containers/runtime#1697
kata-containers/runtime#1703
kata-containers/runtime#1708
kata-containers/runtime#1710
kata-containers/runtime#1717
kata-containers/runtime#1721
kata-containers/runtime#1722
kata-containers/runtime#1723
kata-containers/runtime#1724
kata-containers/runtime#1727
kata-containers/runtime#1739
kata-containers/runtime#1741
kata-containers/runtime#1762

Not Included
kata-containers/runtime#1732 <-- Has vendor changes that is not playing well with the branch.

### CODE REVIEW

**Comment by ganeshmaharaj** [comment]
RHEL-7 builds seem to be failing with missing package dependencies.

```
--> Package perl-HTTP-Message.noarch 0:6.06-6.el7 will be installed
--> Processing Dependency: perl(HTTP::Date) >= 6 for package: perl-HTTP-Message-6.06-6.el7.noarch
--> Processing Dependency: perl(Encode::Locale) >= 1 for package: perl-HTTP-Message-6.06-6.el7.noarch
--> Processing Dependency: perl(IO::HTML) for package: perl-HTTP-Message-6.06-6.el7.noarch
---> Package perl-HTTP-Negotiate.noarch 0:6.01-5.el7 will be installed
---> Package perl-IO-Socket-SSL.noarch 0:1.94-7.el7 will be installed
--> Processing Dependency: perl-Net-SSLeay >= 1.55-5 for package: perl-IO-Socket-SSL-1.94-7.el7.noarch
--> Processing Dependency: perl(Net::SSLeay) >= 1.21 for package: perl-IO-Socket-SSL-1.94-7.el7.noarch
--> Processing Dependency: perl(IO::Socket::IP) >= 0.20 for package: perlError: Package: 7:device-mapper-devel-1.02.149-10.el7_6.8.x86_64 (rhui-rhel-7-server-rhui-optional-rpms)
           Requires: device-mapper = 7:1.02.149-10.el7_6.8
```

**Comment by egernst** [comment]
rekicked RHEL test.

**Comment by jodh-intel** [comment]
Restarted the failing Travis job (network issue) and it has now passed.

**Pull request merged**
