### PR TITLE
versions: Update kernel to 4.14.102

### LINKED ISSUE #1268: Update kernel to 4.14.102 for stable-1.4
In order to fix a bunch of CVEs, let's move to the kernel 4.14.102 for stable 1.4 branch.

### PR DESCRIPTION
**Pull request by sboeuf**
Update kernel to get latest fixes.

Fixes #1268

Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
lgtm - but the CIs didn't like it, and the jenkins server is down right now so I can't go and find out why...

**Comment by sboeuf** [comment]
@grahamwhaley here is the root cause:
```
Skipping checkcommits
See issue: https://github.com/kata-containers/tests/issues/632
INFO: Checking for SPDX license headers
ERROR: Required license identifier ('SPDX-License-Identifier: Apache-2.0') missing from following files:
.pullapprove.yml
The command ".ci/static-checks.sh" failed and exited with 1 during .
```

Did you forget to update this branch wrt pullapprove?

**Comment by grahamwhaley** [comment]
err, @sboeuf - I'm confused :-) we nuked .pullapprove.yaml last week! oh, it's a stable branch!! ouch!!.
dont' suppose you'd like to add a pre-patch to drop .pullapprove.yaml to this PR would you - that might sadly be the easiest fix!

**Comment by sboeuf** [comment]
@grahamwhaley yeah no worries I can do that. I just need to submit a PR removing `.pullapprove.yaml` right?

**Comment by grahamwhaley** [comment]
yep - I was thinking you could even do it as a first-commit on this PR @sboeuf

**Comment by sboeuf** [comment]
@grahamwhaley yes that's a good suggestion, it will be faster :)

**Pull request merged**
