### PR TITLE
vendor: update govmm to be compatible with qemu 2.8

### PR DESCRIPTION
**Pull request by woshijpf**
govmm has ExecuteBlockdevAdd() function and ExecuteBlockdevDel() function
doesn't compatible with qemu 2.8,because blockdev-add and x-blockdev-del usages
are different between qemu 2.7 and qemu 2.8

shortlog:

ce070d1 govmm: modify govmm to be compatible with qemu 2.8
0286ff9 qemu/qmp: support hotplug a nic whose qdisc is mq
8515ae4 qmp: Remind users that you must first call ExecuteQMPCapabilities()
21504d3 qemu/qmp: Add netdev_add with chardev support
ed34f61 Add some negative test cases for qmp.go
17cacc7 Add negative test cases for qemu.go

fixes: #637

Signed-off-by: flyflypeng <jiangpengfei9@huawei.com>

### CODE REVIEW

**Comment by woshijpf** [comment]
Since `ExecuteNetPCIDeviceAdd` function in the govmm has changed the function definition, so I need to change the code where call this function in the runtime, then merge this update vendor PR.

**Comment by caoruidong** [comment]
Yes, I'll raise a PR

**Comment by ydjainopensource** [comment]
@woshijpf I am sending in a PR adding support for Z by today evening. Can this wait till that gets merged? This way we need to revendor only once.  However, I will raise a new PR to incldue my changes if this is urgent for you.

**Comment by WeiZhang555** [comment]
@ydjainopensource I think it makes sense to update once, unless it takes too long to merge your PR

**Comment by ydjainopensource** [comment]
On second thought, just let this go I am still to get the CI running. So merging my PR would take time

**Comment by woshijpf** [comment]
Hey @ydjainopensource ~ What do you want to add  in https://github.com/intel/govmm/? And I wonder how long would you take to finish merge your PR, if not taks so long ,I think just revendor once together is better.

**Comment by ydjainopensource** [comment]
The PR is waiting for review [here](https://github.com/intel/govmm/pull/43). Can't say how long it will take

**Comment by jodh-intel** [comment]
The govmm PR has now been reviewed.

**Comment by devimc** [comment]
PR https://github.com/intel/govmm/pull/43 is being reviewed and probably it will need more work/review 
can we merge this one to unlock https://github.com/kata-containers/runtime/pull/669 ?

btw @woshijpf  you should include the changes suggested by @caoruidong  https://github.com/kata-containers/runtime/pull/651#issuecomment-416266216

**Comment by woshijpf** [comment]
Ok, I have merge #651 and update this PR.

**Comment by jshachm** [comment]
LGTM

**Comment by jodh-intel** [comment]
lgtm

**Comment by sboeuf** [comment]
@woshijpf please backport to stable branches.

**Comment by woshijpf** [comment]
@sboeuf Could you please explain more details about "backport to stable brancher"? I am not familiar with this operation.

**Comment by sboeuf** [comment]
@woshijpf Sure!
So on `github.com/kata-containers/runtime` repo, we have 3 different branche:
- `master`
- `stable-1.1`
- `stable-1.2`

This current PR has been raised against `master`, and because it's been merged and it actually fixes a bug, we want to apply the same code to the 2 other branches.
Please create 2 new PRs, but make sure you open them against `stable-1.1` and `stable-1.2` instead of `master`.

**Pull request merged**
