### PR TITLE
# Kata Containers 1.6.4

### PR DESCRIPTION
**Pull request by katabuilder**
- backports: Bp 1.6.4 rel

b0d86cc vc: fix netns leak
a8b3a23 virtcontainers: fix invalid CPU topology
40a33b2 Support_vsock: only need to check whether device 'vhost_vsock' exists
77d5fe2 vsock_module: add 'vhost_vsock' kernel module in kata-check
42689e6 unit-test: refine unit test

### CODE REVIEW

**Comment by jodh-intel** [comment]
Restarted the ubuntu initrd test which failed on what looks like a transitory error. CentOS failed due to 
 the known issue https://github.com/kata-containers/runtime/issues/1604.

@egernst, @ganeshmaharaj - we can overcome the CentOS failure if you also add https://github.com/kata-containers/runtime/pull/1630 to this PR.

**Comment by ganeshmaharaj** [comment]
@jodh-intel to be able to pull in #1630, i would have to pull in the change https://github.com/kata-containers/runtime/commit/23f7cfa9f433a7a9f7c6102339b1ddfe335495d4 which is not currently marked for backporting. I can morph #1630 to work for the stable tree, though I am not sure how folks feel about it.

**Comment by jodh-intel** [comment]
@ganeshmaharaj - understood and fine with me to force merge this one ;)

**Pull request merged**
