### PR TITLE
config: Add cache-related options for block devices

### PR DESCRIPTION
**Pull request by teawater**
Add block_device_cache_set, block_device_cache_direct
and block_device_cache_noflush.

Fixes: #997

Signed-off-by: Hui Zhu <teawater@hyper.sh>

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

**Comment by teawater** [comment]
In jenkins-metrics-ubuntu-16-04:
```
Report Summary:
+-----+----------------------+-------+--------+--------+-------+--------+--------+-------+------+-----+
| P/F |         NAME         |  FLR  |  MEAN  |  CEIL  |  GAP  |  MIN   |  MAX   |  RNG  | COV  | ITS |
+-----+----------------------+-------+--------+--------+-------+--------+--------+-------+------+-----+
| *F* | boot-times           | 95.0% | 112.1% | 105.0% | 10.0% | 109.0% | 138.9% | 27.4% | 5.5% |  20 |
| *F* | memory-footprint     | 85.0% | 84.4%  | 115.0% | 30.0% | 84.4%  | 84.4%  | 0.0%  | 0.0% |   1 |
| P   | memory-footprint-ksm | 95.0% | 99.9%  | 105.0% | 10.0% | 99.9%  | 99.9%  | 0.0%  | 0.0% |   1 |
+-----+----------------------+-------+--------+--------+-------+--------+--------+-------+------+-----+
```
This patch doesn't change the default behavior.  So I think this fail can be ignore.

**Comment by grahamwhaley** [comment]
Yes, please ignore metrics CI for the moment -  I am working on what has upset it again...

**Pull request merged**
