### PR TITLE
Use Go Modules

### PR DESCRIPTION
**Pull request by moricho**
Now Go1.13 supports Go Modules and I hope this library supports it too.
Previously there was a similar discussion, but it doesn't seem to be in progress.

Ref: https://github.com/kata-containers/runtime/pull/1911

### CODE REVIEW

**Comment by grahamwhaley** [comment]
Hi @moricho - thanks for your (first!) contribution to Kata. I'll leave the go mod discussion to @jodh-intel and @amshinde etc., as they looked already, and iirc, there may have been a reason we did not move yet. But, I will point you to our [Contributors documentation](https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md) to read - I think you will need to edit your commits to fit the correct formatting to satisfy the CI systems :-)
And, welcome to Kata :-)

**Comment by moricho** [comment]
Hi @grahamwhaley . 
Thanks for your comment. I'll read Contributors documentation and follow the discussion about Go Modules once again!

**Comment by grahamwhaley** [comment]
@moricho - I think a key point is made in [this comment on #1911](https://github.com/kata-containers/runtime/pull/1911#issuecomment-528181290) - that just moving from vendor to mod will break the CI and other builds. Did you sturdy the #1911 discussion? (I've not, but I think there is history there that needs to be understood).

/cc @amshinde who last tried to pick this up and @WeiZhang555 who had input.

**Comment by fidencio** [comment]
Folks, this PR has been stale and I'm closing it as we're walking towards the **final** 1.13.0 release of the kata-containers-1.x.
From now on, all the development will happen as part of https://github.com/kata-containers/kata-containers/ and fixes should be provided to that repo.

Thanks a lot for your contribution, we're sorry that for some reason it got stale, and we hope to see you around for new adventures in the kata-containers-2.x land.

**Pull request closed without merging**
