### PR TITLE
# Kata Containers 1.7.2

### PR DESCRIPTION
**Pull request by bergwolf**
- [cherry-pick 1.7]: katautils: fix shim v2 fail to work with libnetwork
- NEMU: Disable default hugepages enabling for virtio-fs

0066fa5 katautils: fix shim v2 fail to work with libnetwork
8cf29dd NEMU: Disable default hugepages enabling for virtio-fs

### CODE REVIEW

**Comment by egernst** [comment]
fedora transient failure: 
```
23:11:14 The downloaded packages were saved in cache until the next successful transaction.
23:11:14 You can remove cached packages by executing 'dnf clean packages'.
23:11:14 Error: Error downloading packages:
23:11:14   Status code: 503 for https://mirrors.fedoraproject.org/metalink?repo=updates-released-f27&arch=x86_64
23:11:14 The command '/bin/sh -c dnf -y update && dnf install -y git systemd pkgconfig gcc coreutils libseccomp libseccomp-devel chrony' returned a non-zero code: 1
23:11:15 Failed at 116: sudo -E AGENT_INIT="${AGENT_INIT}" AGENT_VERSION="${agent_commit}" GOPATH="$GOPATH" USE_DOCKER=true OS_VERSION=${os_version} ./rootfs-builder/rootfs.sh "${distro}"
23:11:15 Build step 'Execute shell' marked build as failure
```

**Comment by egernst** [comment]
@jodh-intel - see travis failure?
```
ERROR: Invalid URL 'https://godoc.org/github.com/kata-containers/runtime' found in the following files:
pkg/katatestutils/README.md
README.md
ERROR: Invalid URL 'https://godoc.org/github.com/kata-containers/runtime/pkg/katatestutils' found in the following files:
pkg/katatestutils/README.md
ERROR: Invalid URL 'https://godoc.org/github.com/kata-containers/runtime?status.svg' found in the following files:
```
IIRC, you added a timeout?  Should we add a retry?  Does the fix need to be packported to stable?

**Comment by bergwolf** [comment]
CI failure noted at https://github.com/kata-containers/tests/issues/1734

**Pull request merged**
