### PR TITLE
virtcontainers: Expand unit test coverage for asset

### LINKED ISSUE #2835: Increase unit test coverage for virtcontainers/types/asset.go
Duplicate of [424](https://github.com/kata-containers/kata-containers/issues/424) in kata-containers/kata-containers.

### PR DESCRIPTION
**Pull request by cmaf**
Add additional test cases that cover more asset types and functions to
increase unit test coverage.

Fixes #2835

Signed-off-by: Chelsea Mafrica <chelsea.e.mafrica@intel.com>

### CODE REVIEW

**Comment by cmaf** [comment]
Comparing unit test coverage with this PR

**Comment by jodh-intel** [comment]
Travis is complaining:

```
virtcontainers/types/asset_test.go:8: File is not `gofmt`-ed with `-s` (gofmt)
```

**Comment by jodh-intel** [comment]
One more ack here and we can land this PR (all green ;)

**Comment by cmaf** [comment]
Forward port: [#425](https://github.com/kata-containers/kata-containers/pull/425) (issue [#424](https://github.com/kata-containers/kata-containers/issues/424))

**Pull request merged**
