### PR TITLE
# Kata Containers 1.6.1

### PR DESCRIPTION
**Pull request by egernst**
Version bump no changes

### CODE REVIEW

**Comment by egernst** [comment]
blocked by #1468

**Comment by jcvenegas** [comment]
@egernst @ganeshmaharaj @chavafg  still have some issues relaeted with linter 
```
/home/travis/gopath/src/github.com/kata-containers/runtime/virtcontainers/utils
containerd-shim-v2/service.go:594:10: `events.TaskPaused` composite literal uses unkeyed fields (govet)
	s.send(&eventstypes.TaskPaused{
	        ^
containerd-shim-v2/service.go:622:10: `events.TaskResumed` composite literal uses unkeyed fields (govet)
	s.send(&eventstypes.TaskResumed{
```

**Comment by jcvenegas** [comment]
centos: Probably a unstable test
```
[2] • Failure [35.609 seconds]
[2] Update number of CPUs
[2] /tmp/jenkins/workspace/kata-containers-runtime-centos-7-4-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:228
[2]   Update CPU period and quota
[2]   /tmp/jenkins/workspace/kata-containers-runtime-centos-7-4-PR/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table.go:92
[2]     should have 3 CPUs [It]
[2]     /tmp/jenkins/workspace/kata-containers-runtime-centos-7-4-PR/go/src/github.com/kata-containers/tests/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46
[2] 
[2]     Expected
[2]         <int>: 1
[2]     to be zero-valued
[2] 
[2]     /tmp/jenkins/workspace/kata-containers-runtime-centos-7-4-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:277
[2] ------------------------------
[2] 
[2] 
[2] Summarizing 1 Failure:
[2] 
[2] [Fail] Update number of CPUs Update CPU period and quota [It] should have 3 CPUs 
[2] /tmp/jenkins/workspace/kata-containers-runtime-centos-7-4-PR/go/src/github.com/kata-containers/tests/integration/docker/cpu_test.go:277
[2] 
[2] Ran 51 of 51 Specs in 655.057 seconds
[2] FAIL! -- 50 Passed | 1 Failed | 0 Pending | 0 Skipped --- FAIL: TestIntegration (655.06s)
```

**Comment by jcvenegas** [comment]
ubuntu-18-04-PR-initrd and centos  restarted

**Pull request merged**
