### PR TITLE
ci: clear travis config warnings

### PR DESCRIPTION
**Pull request by liubin**
Fixes: #2957

Signed-off-by: bin liu <bin@hyper.sh>

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @liubin.

lgtm

**Comment by liubin** [comment]
Thanks @jodh-intel , I'm sorry that previous PRs are pushed onto wrong branch, so I re-created it.

**Comment by jodh-intel** [comment]
@liubin - np ;)

**Review by cmaf — APPROVED** [review]
lgtm

**Pull request merged**
