### PR TITLE
gitignore: Ignore cli/containerd-shim-kata-v2/config-generated.go

### PR DESCRIPTION
**Pull request by dgibson**
This link is generated during build, but not ignored by .gitignore.

Signed-off-by: David Gibson <david@gibson.dropbear.id.au>

### CODE REVIEW

**Review by jodh-intel — APPROVED** [review]
Thanks @dgibson.

**Comment by jodh-intel** [comment]
@dgibson - you'll need to reference an issue number in the "Fixes: #XXX" comment for the CIs to be happy. See:

- https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#patch-format

**Review by c3d — APPROVED** [review]
Looks good to me (with the change in commit message @jodh-intel pointed out)

**Review by devimc — APPROVED** [review]
lgtm - thanks @dgibson

**Comment by dgibson** [comment]
> @dgibson - you'll need to reference an issue number in the "Fixes: #XXX" comment for the CIs to be happy. See:

Dangit, forgot.

**Pull request merged**
