### PR TITLE
Create the hypervisor package

### LINKED ISSUE #1229: Add hypervisor package
# Description of problem

In order to simplify and make the virtcontainers logic more logically separated (#1059), we want to move the hypervisor specific code into its own package. The end goal is to keep only the pure virtcontainers logic under the virtcontainers package.

### PR DESCRIPTION
**Pull request by sameo**
With the `store` package now merged in, we can finally create a standalone `hypervisor` package for all thing hypervisor/vmm related. We still want to decouple the `Endpoint` interface from the `hypervisor` package but that can be done as a follow up step.

Fixes #1229

### CODE REVIEW

**Comment by amshinde** [comment]
@sameo The PR looks good overall. But I agree with @sboeuf, moving the network endpoints under hypervisor package, although solves the cyclic issue, seems a bit counter-intuitive. 
I dont have any solution for this either, maybe have some kind of intermediate representation of just the required network properties in the hypervisor package. Not sure if that will over-complicate things.

**Comment by sameo** [comment]
@amshinde @sboeuf I fully agree that it's not entirely natural to put `Endpoint` under the `hypervisor` package but the reality is that our current endpoint interface is `hypervisor` bound for the device attachment part.
I'm ok with putting this PR on hold until we manage to break that dependency. There are a couple ways to do that and I'm going to open an issue to track that.

**Comment by sameo** [comment]
Adding `donotmerge` back, let's see if we can have a network/endpoint package first.

**Comment by sameo** [comment]
> I'm ok with putting this PR on hold until we manage to break that dependency. There are a couple ways to do that and I'm going to open an issue to track that.

I already did that a few days ago...See #1209

**Comment by jodh-intel** [comment]
Needs a rebase though ;)

**Comment by jodh-intel** [comment]
@sameo - this still needs a rebase.

@kata-containers/runtime - are you there? :)

**Comment by amshinde** [comment]
I guess this PR depend on https://github.com/kata-containers/runtime/pull/1233 being merged first.

**Comment by raravena80** [comment]
@sameo ping, any updates? Thx!

**Comment by raravena80** [comment]
@sameo nudge

**Comment by raravena80** [comment]
@sameo any updates?

**Comment by egernst** [comment]
need help for driving this forward.  Added 'needs-help' label

**Comment by raravena80** [comment]
Any takers?

**Comment by raravena80** [comment]
Pinging from your weekly herder, any takers? 😄 🙏

**Comment by Zyqsempai** [comment]
Hey guys, I want to take care of this, but it looks like this PR it's hard to reanimate, since there is to much conflicts, it's almost impossible to resolve them, believe me, I spent 4 hours trying to do that.
Do you have any idea where better to start, or maybe it will be easier to create a new PR?

**Comment by caoruidong** [comment]
@Zyqsempai Yes, you can create a new one.

**Comment by Zyqsempai** [comment]
Also, I see that there is an open question about `Endpoints`, where they should be moved.
Do you have decision related to this topic?

**Comment by Zyqsempai** [comment]
@raravena80 @caoruidong @egernst So, i am almost finished, the only one question is still open, is `Endpoints` where and how should we move them?
There is one already opened PR https://github.com/kata-containers/runtime/pull/1233 by same as this is stock.

**Comment by raravena80** [comment]
@Zyqsempai Any update on this PR? Thx

**Comment by raravena80** [comment]
@Zyqsempai any updates? 

Your weekly Kata herder.

**Comment by raravena80** [comment]
@Zyqsempai ping 😄

**Comment by Zyqsempai** [comment]
Sorry guys, didn't had enough time to work on it, will try to look into it on this week.

**Comment by raravena80** [comment]
@Zyqsempai friendly ping 😄

**Comment by raravena80** [comment]
@Zyqsempai this is old, should we close this and move the work to 2.0?

**Comment by c3d** [comment]
@Zyqsempai Two friendly pings, the last one in June, and in bad need of a rebase.
Closing for now. Please feel free to re-open when you feel it's back in the "ready to merge" state.
Thanks!

**Pull request closed without merging**
