### PR TITLE
versions: Update kernel to version 4.14.51

### PR DESCRIPTION
**Pull request by jcvenegas**
Update to kernel to get latest fixes.

Depends-on: github.com/kata-containers/agent#278
Fixes: #420

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
lgtm

Related: https://github.com/kata-containers/ci/issues/41.

**Comment by jcvenegas** [comment]
Seems that the CI is not happy with the new kernel version, I'll debug locally

**Comment by devimc** [comment]
@jcvenegas newest version is 4.14.51, any reason to prefer 4.14.50 ?

**Comment by jcvenegas** [comment]
@devimc when I created the RP the latest was 4.14.50  , thanks for heads up.

depends on https://github.com/kata-containers/agent/pull/279

**Pull request merged**
