### PR TITLE
vendor: fix govmm package

### LINKED ISSUE #797: Fix govmm package
Last time govmm was updated it was not vendored correctly

### PR DESCRIPTION
**Pull request by devimc**
Last time govmm was updated it was not vendored correctly

Fixes #797

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
What was the problem with the previous re-vendor?

**Comment by devimc** [comment]
@jodh-intel I think so, if you run `dep ensure` on master you'll see that `govmm` is modified but ` Gopkg.toml` not

**Comment by jshachm** [comment]
LGTM

**Pull request merged**
