### PR TITLE
s390x: fix golint complain

### PR DESCRIPTION
**Pull request by alicefr**
Changed capital letter of VirtioSerialCCW to avoid golint complain

Fixes : #1327

Signed-off-by: Alice Frosi <afrosi@de.ibm.com>

### CODE REVIEW

**Comment by alicefr** [comment]
Sorry I pushed in the false branch. Let me fix it

**Comment by jodh-intel** [comment]
initrd CI failed with:

```
	Error:		Received unexpected error rpc error: code = Unknown desc = failed to stop container "2935eba26413dcc4598bb0937530f0a8e5e0e6b06c3836cee7c34a62dea4d0d9": container_linux.go:389: signaling init process caused "no such process": unknown
```

Restarting to see if it's a transitory / machine issue...

**Comment by jodh-intel** [comment]
Ignoring initrd testing - this is a simple rename and all the other CI's are green. Let's not labour it...

**Pull request merged**
