### PR TITLE
version: Update containerd version to 1.3.0

### PR DESCRIPTION
**Pull request by amshinde**
These include features like privileged containers without host devices
and support for per runtime annotations.

Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by egernst** [comment]
Yikes, CI really didn’t like this PR.

**Comment by amshinde** [comment]
@egernst Yeah, lets try this one more time.

**Comment by jodh-intel** [comment]
Could you add the changes to containerd in the commit?

All the CI's seem to be failing attempting to build CNI plugins.

**Comment by bergwolf** [comment]
Since `privileged containers without host devices` is kind of unique to kata, could you add a test case to validate it (after merging this PR)?

**Comment by GabyCT** [comment]
@amshinde if this PR is related with https://github.com/kata-containers/tests/pull/2003 then you need to put `Depends-on` on the commit

**Comment by amshinde** [comment]
@GabyCT I did put it on the commit.

**Comment by grahamwhaley** [comment]
nudge - any plans for this @amshinde @egernst

**Comment by amshinde** [comment]
@grahamwhaley I will be looking at this again to fix the CI failures.

**Comment by amshinde** [comment]
@chavafg I suspect this PR has been failing as the VM instances do not seem to support ipv6 in spite of trying to enable it with this PR: https://github.com/kata-containers/tests/pull/2003
Do you know if I am missing something for enabling this, does this need to be requested from azure while creating the instances itself.

**Comment by chavafg** [comment]
@amshinde I am not sure, but reading some internet resources it seems that we need to make further configuration to enable ipv6. Will check how to do it and how to enable it using our jenkins plugin.

**Comment by amshinde** [comment]
@chavafg For now, I have avoided using ipv6 with https://github.com/kata-containers/tests/pull/2029 by not using the cni config file that comes with containerd which included ipv6 routes.
I wanted to check if this would really resolve the errors related to ipv6 that I was seeing. 
While I no longer see the ipv6 errors in the shimv2 tests, I am now seeing errors in the k8s tests with containerd. containerd seems to exit after starting successfully:
```
Oct 31 00:16:46 ubuntu1804-azurecf2320 containerd[7607]: time="2019-10-31T00:16:46.165132668Z" level=info msg=serving... address="/run/containerd/containerd.sock"
Oct 31 00:16:46 ubuntu1804-azurecf2320 containerd[7607]: time="2019-10-31T00:16:46.165155668Z" level=info msg="containerd successfully booted in 0.165919s"
Oct 31 00:32:57 ubuntu1804-azurecf2320 systemd[1]: containerd.service: Current command vanished from the unit file, execution of the command list won't be resumed.
Init cluster using /run/containerd/containerd.sock
[init] Using Kubernetes version: v1.15.3
[preflight] Running pre-flight checks
error execution phase preflight: [preflight] Some fatal errors occurred:
	[ERROR CRI]: container runtime is not running: output: time="2019-10-31T00:41:45Z" level=fatal msg="getting status of runtime failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService"```

@jcvenegas Do you have any input on this? I know you had added the initial commit to switch to testing with the cni config provided by containerd. Was this added to address a certain failure that I am not aware of.

**Comment by amshinde** [comment]
@chavafg I am seeing that containerd process exits while doing a `kubeadm init`.
It would be good to see the containerd journal at this point. 
I dont see the containerd logs: http://jenkins.katacontainers.io/job/kata-containers-runtime-cri-containerd-PR/1699/
Can we make them available?

**Comment by chavafg** [comment]
@amshinde I opened https://github.com/kata-containers/tests/pull/2035 to collect them in the CI

**Comment by amshinde** [comment]
@chavafg Thanks, I have merged it. Will the entire CI need to be rerun again?
Feel free to trigger what you think needs to be done.

**Comment by amshinde** [comment]
@lifupan containerd-cri CI seems to be failing. I dont see much from the containerd logs other than
```
Nov 01 17:33:17 ubuntu1804-azure7e00c0 containerd[19005]: time="2019-11-01T17:33:17.298016926Z" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." type=io.containerd.grpc.v1
Nov 01 17:33:17 ubuntu1804-azure7e00c0 containerd[19005]: time="2019-11-01T17:33:17.298287844Z" level=info msg=serving... address="/run/containerd/containerd.sock"
Nov 01 17:33:17 ubuntu1804-azure7e00c0 containerd[19005]: time="2019-11-01T17:33:17.298311145Z" level=info msg="containerd successfully booted in 0.343453s"
Nov 01 17:43:03 ubuntu1804-azure7e00c0 systemd[1]: containerd.service: Current command vanished from the unit file, execution of the command list won't be resumed.
Nov 01 17:51:42 ubuntu1804-azure7e00c0 systemd[1]: Stopping containerd container runtime...
Nov 01 17:51:42 ubuntu1804-azure7e00c0 systemd[1]: Stopped containerd container runtime.
```
Do you have any idea? I was able to run containerd 1.3.0 with kata shimv1 and v2 locally.

**Comment by lifupan** [comment]
> @lifupan containerd-cri CI seems to be failing. I dont see much from the containerd logs other than
> 
> ```
> Nov 01 17:33:17 ubuntu1804-azure7e00c0 containerd[19005]: time="2019-11-01T17:33:17.298016926Z" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." type=io.containerd.grpc.v1
> Nov 01 17:33:17 ubuntu1804-azure7e00c0 containerd[19005]: time="2019-11-01T17:33:17.298287844Z" level=info msg=serving... address="/run/containerd/containerd.sock"
> Nov 01 17:33:17 ubuntu1804-azure7e00c0 containerd[19005]: time="2019-11-01T17:33:17.298311145Z" level=info msg="containerd successfully booted in 0.343453s"
> Nov 01 17:43:03 ubuntu1804-azure7e00c0 systemd[1]: containerd.service: Current command vanished from the unit file, execution of the command list won't be resumed.
> Nov 01 17:51:42 ubuntu1804-azure7e00c0 systemd[1]: Stopping containerd container runtime...
> Nov 01 17:51:42 ubuntu1804-azure7e00c0 systemd[1]: Stopped containerd container runtime.
> ```
> 
> Do you have any idea? I was able to run containerd 1.3.0 with kata shimv1 and v2 locally.



> @lifupan containerd-cri CI seems to be failing. I dont see much from the containerd logs other than
> 
> ```
> Nov 01 17:33:17 ubuntu1804-azure7e00c0 containerd[19005]: time="2019-11-01T17:33:17.298016926Z" level=info msg="loading plugin "io.containerd.grpc.v1.introspection"..." type=io.containerd.grpc.v1
> Nov 01 17:33:17 ubuntu1804-azure7e00c0 containerd[19005]: time="2019-11-01T17:33:17.298287844Z" level=info msg=serving... address="/run/containerd/containerd.sock"
> Nov 01 17:33:17 ubuntu1804-azure7e00c0 containerd[19005]: time="2019-11-01T17:33:17.298311145Z" level=info msg="containerd successfully booted in 0.343453s"
> Nov 01 17:43:03 ubuntu1804-azure7e00c0 systemd[1]: containerd.service: Current command vanished from the unit file, execution of the command list won't be resumed.
> Nov 01 17:51:42 ubuntu1804-azure7e00c0 systemd[1]: Stopping containerd container runtime...
> Nov 01 17:51:42 ubuntu1804-azure7e00c0 systemd[1]: Stopped containerd container runtime.
> ```
> 
> Do you have any idea? I was able to run containerd 1.3.0 with kata shimv1 and v2 locally.

Hi @amshinde 

I think PR https://github.com/kata-containers/tests/pull/2043 can fix this issue.

**Comment by amshinde** [comment]
@lifupan Thanks, looks like that did help. I have added another commit to update containerd config here : https://github.com/kata-containers/tests/pull/2029/commits/61725d5d1acd083b4b7fee313ef9c1c02ce38323

But looks like one of storage tests is failing now.

**Comment by amshinde** [comment]
I have tried reproducing the failures locally. Even tried running the kubernetes CI on an Azure instance.
However I do not see any failures locally. So I don't understand why the storage test is failing in the CI here.
The containerd CI run for this PR shows  storage test fails when the the pod does a mount, but the pod has been given CAP_SYS_ADMIN capabilities, so I do not see why the mount should fail, unless some weird apparmor issues.
@lifupan Any idea about this? Let me know if you are able to reproduce the issue.

@chavafg Let me know if you can reproduce the containerd CI issue, if you have nay cycles.

**Comment by chavafg** [comment]
Hi @amshinde,

I could reproduce the issue and tried to debug... but it seems that containerd tests are not even running kata. I see pod up, but no kata process. Also the journals of kata-runtime and proxy are empty.
Continue checking the issue.

**Comment by chavafg** [comment]
seems like changes here https://github.com/kata-containers/tests/pull/2029/files#diff-69bf746790abbecab6afee63f20ad2f7L29-R36 are not working correctly, could you make them work locally?

**Pull request merged**
