### PR TITLE
Nemu bump

### PR DESCRIPTION
**Pull request by egernst**
- Bump NEMU version up to latest
- update versions.yaml for accurate descriptions

### CODE REVIEW

**Comment by egernst** [comment]
NEMU CI is the one that should be exercised here.

**Comment by grahamwhaley** [comment]
we know q35 ci is not happy right now - so, this is probably open to merge - am still interested in how we got two nemu bumps in a 10h window - maybe it was on purpose and planned, in which case maybe we needed to note that on the PRs?

**Comment by chavafg** [comment]
@grahamwhaley not on purpose or planned to have both PRs, but this one is not a pre-release, so I can close my PR and merge this one.

**Pull request merged**
