### PR TITLE
virtiofsd: fix typo in test code

### PR DESCRIPTION
**Pull request by Kvasscn**
Fix typo in virtiofsd_test.go

Fixes: #2948

Signed-off-by: zhanghj <zhanghj.lc@inspur.com>

### CODE REVIEW

**Review by fidencio — APPROVED** [review]
lgtm!

@Kvasscn, thanks a lot for the original and the backported patch!

**Review by jodh-intel — APPROVED** [review]
Thanks @Kvasscn.

lgtm

**Pull request merged**
