### PR TITLE
versions: Move to k8s 1.10

### PR DESCRIPTION
**Pull request by jcvenegas**
Move to k8s 1.10

Fixes: #277

Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
I was talking with the CRI-O guys and there will be compatibility issues between Openshift and Kubernetes, because latest Openshift v3.9 should use CRI-O 1.9 and k8s 1.10 should use CRI-O 1.10. 

There isnt still an Openshift 3.10 out, neither an alpha release.

So I think we will need to have a way to test crio 1.9 with openshift v3.9.0 and crio 1.10 with k8s 1.10

**Comment by sboeuf** [comment]
@chavafg thanks for the heads up. If we can fit this into our CI without increasing the time taken by the CI, that'd be great. I am saying that because the CI is already pretty slow (around an hour now...)
/cc @egernst

**Comment by chavafg** [comment]
I was thinking Fedora to run Openshift tests and ubuntu to run k8s, what do you think @sboeuf @egernst @jcvenegas ?

**Comment by egernst** [comment]
@chavafg  this makes a lot of sense to me - a natural division.

**Comment by sboeuf** [comment]
:+1:

**Comment by jodh-intel** [comment]
lgtm

**Comment by amshinde** [comment]
lgtm

**Comment by chavafg** [comment]
Using k8s 1.10.0 `kubeadm reset` doesn't delete  the pods created by CRI-O, while k8s 1.9 does it properly. Seems like an issue with cri-o or kuberentes, since I can reproduce the failure using `runc`.

**Comment by chavafg** [comment]
The issue is already reported on kubeadm: https://github.com/kubernetes/kubeadm/issues/748

I think the only option here is to add a workaround in the tests to delete the pods after running `kubeadm reset` using `crictl` and when this is fixed, remove the workaround. 
cc @jcvenegas @egernst @sboeuf @amshinde @jodh-intel

**Comment by jodh-intel** [comment]
Hi @chavafg - sounds reasonable to me.

**Comment by amshinde** [comment]
@chavafg Yes, that sounds fine. Lets create an issue for it so we dont forget.

**Comment by chavafg** [comment]
opened https://github.com/kata-containers/tests/issues/296 to delete the workaround when the issue gets properly fixed.

**Comment by chavafg** [comment]
This is ready to be merged, but please when merge this, please also merge this one in tests repository: https://github.com/kata-containers/tests/pull/277

**Pull request merged**
