### PR TITLE
[backport] runtime: clh: disable virtiofs DAX when FS cache size is 0

### LINKED ISSUE #3072: backport: clh: disable virtiofs DAX when FS cache size is 0
backport https://github.com/kata-containers/kata-containers/pull/1101

### PR DESCRIPTION
**Pull request by devimc**
Guest consumes 120Mb more of memory when DAX is enabled and the default
FS cache size (8G) is used. Disable dax when it is not required
reducing guest's memory footprint.

Without this patch:

```
7fdea4000000-7fdee4000000 rw-s 18850589 /memfd:ch_ram (deleted)
Size:            1048576 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:              187876 kB
```

With this patch:

```
7fa970000000-7fa9b0000000 rw-s 612001  /memfd:ch_ram (deleted)
Size:            1048576 kB
KernelPageSize:        4 kB
MMUPageSize:           4 kB
Rss:               57308 kB
Pss:               56722 kB
```

fixes #3072

Signed-off-by: Julio Montes <julio.montes@intel.com>

### CODE REVIEW

**Review by likebreath — APPROVED** [review]
Thanks, @devimc. The data looks great. Good/expected failure on the metrics:
```
14:10:26 time="2020-11-12T22:10:26Z" level=warning msg="Failed Minval ( 258919.403000(minimal mean expected) > 141659.350000(minimal mean on dataset)) for [memory-footprint-ksm]"
```

**Comment by likebreath** [comment]
I also opened a PR https://github.com/kata-containers/tests/pull/3058 to update the reference midval for memory-footprint being used by our metrics CI. Please feel free to add a `Depends-on: github.com/kata-containers/tests#3058` in the commit message for making the metrics CI happy.

**Review by bergwolf — APPROVED** [review]

**Review by jodh-intel — APPROVED** [review]

**Comment by likebreath** [comment]
Add DNM now, so that we will land this PR with https://github.com/kata-containers/tests/pull/3058 at the same time.

**Pull request merged**
