### PR TITLE
virtcontainers: Append max_ports to virtio-serial device

### PR DESCRIPTION
**Pull request by justin-he**

### CODE REVIEW

**Comment by devimc** [comment]
@justin-he thanks, I was about to raise the same change :smile: 

fyi - CI is not happy

```
03:40:17 --- FAIL: TestQemuArchBaseAppendConsoles (0.00s)
03:40:17     assertions.go:239: 
                          
	Error Trace:	qemu_arch_base_test.go:281
03:40:17         
	Error:      	Not equal: 
03:40:17         
	            	expected: []qemu.Device{qemu.SerialDevice{Driver:"virtio-serial", ID:"serial0", DisableModern:false, ROMFile:"", DevNo:"", Transport:"", MaxPorts:0x0}, qemu.CharDevice{Backend:"socket", Driver:"virtconsole", Bus:"", DeviceID:"console0", ID:"charconsole0", Path:"/tmp/vc/mockfs/sbs/123456789/console.sock", Name:"", DisableModern:false, ROMFile:"", DevNo:"", Transport:""}}
03:40:17         
	            	actual: []qemu.Device{qemu.SerialDevice{Driver:"virtio-serial", ID:"serial0", DisableModern:false, ROMFile:"", DevNo:"", Transport:"", MaxPorts:0x2}, qemu.CharDevice{Backend:"socket", Driver:"virtconsole", Bus:"", DeviceID:"console0", ID:"charconsole0", Path:"/tmp/vc/mockfs/sbs/123456789/console.sock", Name:"", DisableModern:false, ROMFile:"", DevNo:"", Transport:""}}
```

**Comment by justin-he** [comment]
> expected: []qemu.Device{qemu.SerialDevice{Driver:"virtio-serial", ID:"serial0", DisableModern:false, ROMFile:"", DevNo:"", Transport:"", MaxPorts:0x0}, qemu.CharDevice{Backend:"socket", Driver:"virtconsole", Bus:"", DeviceID:"console0", ID:"charconsole0", Path:"/tmp/vc/mockfs/sbs/123456789/console.sock", Name:"", DisableModern:false, ROMFile:"", DevNo:"", Transport:""}}
> 03:40:17         
> 	            	actual: []qemu.Device{qemu.SerialDevice{Driver:"virtio-serial", ID:"serial0", DisableModern:false, ROMFile:"", DevNo:"", Transport:"", MaxPorts:0x2}, qemu.CharDevice{Backend:"socket", Driver:"virtconsole", Bus:"", DeviceID:"console0", ID:"charconsole0", Path:"/tmp/vc/mockfs/sbs/123456789/console.sock", Name:"", DisableModern:false, ROMFile:"", DevNo:"", Transport:""}}


At first glance, I should revise the test case also. will fix it asap

**Comment by justin-he** [comment]
> @justin-he thanks, I was about to raise the same change 😄
> 
> fyi - CI is not happy
> 
> ```
> 03:40:17 --- FAIL: TestQemuArchBaseAppendConsoles (0.00s)
> 03:40:17     assertions.go:239: 
>                           
> 	Error Trace:	qemu_arch_base_test.go:281
> 03:40:17         
> 	Error:      	Not equal: 
> 03:40:17         
> 	            	expected: []qemu.Device{qemu.SerialDevice{Driver:"virtio-serial", ID:"serial0", DisableModern:false, ROMFile:"", DevNo:"", Transport:"", MaxPorts:0x0}, qemu.CharDevice{Backend:"socket", Driver:"virtconsole", Bus:"", DeviceID:"console0", ID:"charconsole0", Path:"/tmp/vc/mockfs/sbs/123456789/console.sock", Name:"", DisableModern:false, ROMFile:"", DevNo:"", Transport:""}}
> 03:40:17         
> 	            	actual: []qemu.Device{qemu.SerialDevice{Driver:"virtio-serial", ID:"serial0", DisableModern:false, ROMFile:"", DevNo:"", Transport:"", MaxPorts:0x2}, qemu.CharDevice{Backend:"socket", Driver:"virtconsole", Bus:"", DeviceID:"console0", ID:"charconsole0", Path:"/tmp/vc/mockfs/sbs/123456789/console.sock", Name:"", DisableModern:false, ROMFile:"", DevNo:"", Transport:""}}
> ```

resolved, thanks

**Comment by devimc** [comment]
thanks @justin-he  - would you mind file an issue in https://github.com/kata-containers/kata-containers/issues ? this way we won't forget to backport it

**Comment by justin-he** [comment]
> thanks @justin-he - would you mind file an issue in https://github.com/kata-containers/kata-containers/issues ? this way we won't forget to backport it


Okay, done. Should I also create a new pull request in new repo  https://github.com/kata-containers/kata-containers/ ?

**Comment by devimc** [comment]
@justin-he  you can, but we are still waiting for https://github.com/kata-containers/kata-containers/issues/247

**Comment by amshinde** [comment]
@justin-he Please feel free to open a pull request in the new repo.

**Comment by bpradipt** [comment]
@justin-he @amshinde @devimc @jodh-intel is this required for 1.x or should be closed and targeted for 2.x only ?

**Comment by devimc** [comment]
@bpradipt I think so, this is a nice to have for 1.x - @justin-he what do you think ?

**Comment by justin-he** [comment]
> @bpradipt I think so, this is a nice to have for 1.x - @justin-he what do you think ?

Sorry, I almost forget it, will pick it up and open the pr in both 1.x and 2.0 within a few days.

**Comment by justin-he** [comment]
Ping @jodh-intel @devimc , thanks :)

**Comment by devimc** [comment]
@justin-he unit tests are failing

```
11:18:02 --- FAIL: TestQemuArchBaseAppendConsoles (0.00s)
11:18:02     assertions.go:239: 
                          
	Error Trace:	qemu_arch_base_test.go:281
11:18:02         
	Error:      	Not equal: 
11:18:02         
	            	expected: []qemu.Device{qemu.SerialDevice{Driver:"virtio-serial", ID:"serial0", DisableModern:false, ROMFile:"", DevNo:"", Transport:"", MaxPorts:0x0}, qemu.CharDevice{Backend:"socket", Driver:"virtconsole", Bus:"", DeviceID:"console0", ID:"charconsole0", Path:"/tmp/vc/mockfs/sbs/123456789/console.sock", Name:"", DisableModern:false, ROMFile:"", DevNo:"", Transport:""}}
11:18:02         
	            	actual: []qemu.Device{qemu.SerialDevice{Driver:"virtio-serial", ID:"serial0", DisableModern:false, ROMFile:"", DevNo:"", Transport:"", MaxPorts:0x2}, qemu.CharDevice{Backend:"socket", Driver:"virtconsole", Bus:"", DeviceID:"console0", ID:"charconsole0", Path:"/tmp/vc/mockfs/sbs/123456789/console.sock", Name:"", DisableModern:false, ROMFile:"", DevNo:"", Transport:""}}
11:18:02         
	            	
11:18:02         
	            	Diff:
11:18:02         
	            	--- Expected
11:18:02         
	            	+++ Actual
11:18:02         
	            	@@ -8,3 +8,3 @@
11:18:02         
	            	   Transport: (qemu.VirtioTransport) "",
11:18:02         
	            	-  MaxPorts: (uint) 0
11:18:02         
	            	+  MaxPorts: (uint) 2
11:18:02         
	            	  },
```

**Comment by justin-he** [comment]
> @justin-he unit tests are failing
> 
> ```
> 11:18:02 --- FAIL: TestQemuArchBaseAppendConsoles (0.00s)
> 11:18:02     assertions.go:239: 
>                           
> 	Error Trace:	qemu_arch_base_test.go:281
> 11:18:02         
> 	Error:      	Not equal: 
> 11:18:02         
> 	            	expected: []qemu.Device{qemu.SerialDevice{Driver:"virtio-serial", ID:"serial0", DisableModern:false, ROMFile:"", DevNo:"", Transport:"", MaxPorts:0x0}, qemu.CharDevice{Backend:"socket", Driver:"virtconsole", Bus:"", DeviceID:"console0", ID:"charconsole0", Path:"/tmp/vc/mockfs/sbs/123456789/console.sock", Name:"", DisableModern:false, ROMFile:"", DevNo:"", Transport:""}}
> 11:18:02         
> 	            	actual: []qemu.Device{qemu.SerialDevice{Driver:"virtio-serial", ID:"serial0", DisableModern:false, ROMFile:"", DevNo:"", Transport:"", MaxPorts:0x2}, qemu.CharDevice{Backend:"socket", Driver:"virtconsole", Bus:"", DeviceID:"console0", ID:"charconsole0", Path:"/tmp/vc/mockfs/sbs/123456789/console.sock", Name:"", DisableModern:false, ROMFile:"", DevNo:"", Transport:""}}
> 11:18:02         
> 	            	
> 11:18:02         
> 	            	Diff:
> 11:18:02         
> 	            	--- Expected
> 11:18:02         
> 	            	+++ Actual
> 11:18:02         
> 	            	@@ -8,3 +8,3 @@
> 11:18:02         
> 	            	   Transport: (qemu.VirtioTransport) "",
> 11:18:02         
> 	            	-  MaxPorts: (uint) 0
> 11:18:02         
> 	            	+  MaxPorts: (uint) 2
> 11:18:02         
> 	            	  },
> ```
Sorry, missed sth when rebasing the patch

**Comment by c3d** [comment]
@justin-he Could you please update the description to link to issue #2676 ? Adding a "Fixes: #2676" line to the commits.

**Comment by justin-he** [comment]
> @justin-he Could you please update the description to link to issue #2676 ? Adding a "Fixes: #2676" line to the commits.

Sorry，@c3d. Not quite sure I understand your comments here. But I pushed the commit again just now. Does it look good to you now?

**Review by devimc — APPROVED** [review]
thanks @justin-he

**Review by jodh-intel — APPROVED** [review]

**Pull request merged**
