### PR TITLE
factory: Make VMCache and VM templating can work together

### PR DESCRIPTION
**Pull request by teawater**
Make VMCache and VM templating can work together.

Fixes: #1376

Signed-off-by: Hui Zhu <teawater@hyper.sh>

### CODE REVIEW

**Comment by devimc** [comment]
@teawater Thanks for the PR but the CI is failing

```
bash sanity/check_sanity.sh
ERROR: 1 pods left and found at /var/lib/vc/sbs
Makefile:47: recipe for target 'functional' failed
make: *** [functional] Error 1
```

**Comment by teawater** [comment]
Meet cannot cleanup issue like the issue that fixed by https://github.com/kata-containers/runtime/pull/764

**Comment by jcvenegas** [comment]
@teawater ping #764 got merged, you want to give another round to this PR?

**Comment by teawater** [comment]
> @teawater ping #764 got merged, you want to give another round to this PR?

@jcvenegas Thanks for your remind.  I am going to restart work of this PR.

**Pull request merged**
