### PR TITLE
# Kata Containers 1.11.0

### PR DESCRIPTION
**Pull request by katabuilder**
- backport 1.11: fix podman vfio

93b1b833 virtcontainers: constrain runtime after creating network
fc9be990 virtcontainers: update sandbox's device cgroup
5cfae217 virtcontainers: remove all the code related to HasCRIContainerType
cff5392a virtcontainers: apply constraints to the sandbox cgroup
ce6edc5a pkg/cgroups: update the list of devices for the hypervisor
3fceece3 pkg/cgroups: add methods to add and remove device from the cgroup
b3458550 pkg/cgroups: implement functions to get information from a host device
0d3b6975 device: add GetHostPath() to generic device

### CODE REVIEW

**Comment by jcvenegas** [comment]
Waiting for https://github.com/kata-containers/packaging/pull/1035 
and the backport for https://github.com/kata-containers/runtime/pull/2659

**Comment by jodh-intel** [comment]
Travis has caught an issue:

```
INFO: Tagging Kata Containers with version 1.11.0
INFO: Check all repos has version 1.11.0 in VERSION file
INFO: agent is in 1.11.0-rc0
ERROR: agent is not in version 1.11.0
The command ".ci/versions_checker.sh" failed and exited with 1 during .
```

**Comment by jcvenegas** [comment]
@jodh-intel nice, it expects that all other bumps are merged first

**Comment by jcvenegas** [comment]
```
00:22:32.204 Drop caches
00:22:34.026 /tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR/go/src/github.com/kata-containers/runtime
00:22:34.057 Setup virtcontainers environment
00:22:57.459 Install virtcontainers
00:22:57.487 make: Entering directory '/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR/go/src/github.com/kata-containers/runtime/virtcontainers'
00:22:57.489      GOBUILD  build
00:22:57.848      GOBUILD  hook
00:22:58.420      GOBUILD  kata-shim
00:22:59.884 make: Leaving directory '/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR/go/src/github.com/kata-containers/runtime/virtcontainers'
00:22:59.945 /usr/local/bin/kata-runtime
00:22:59.945 Logging kata-env information:
00:23:00.550 Build step 'Execute shell' marked build as failure
00:23:07.622 Performing Post build task...
00:23:07.622 Match found for :.* : True
00:23:07.622 Logical operation result is TRUE
00:23:07.622 Running script  : #!/bin/bash
00:23:07.622 
```

**Comment by jcvenegas** [comment]
00:22:30.874 Install virtcontainers
00:22:30.876 make: Entering directory '/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR/go/src/github.com/kata-containers/runtime/virtcontainers'
00:22:30.878      GOBUILD  build
00:22:31.241      GOBUILD  hook
00:22:31.798      GOBUILD  kata-shim
00:22:33.226 make: Leaving directory '/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR/go/src/github.com/kata-containers/runtime/virtcontainers'
00:22:33.289 /usr/local/bin/kata-runtime
00:22:33.289 Logging kata-env information:
00:22:33.847 Build step 'Execute shell' marked build as failure
00:22:41.180 Performing Post build task...
00:22:41.180 Match found for :.* : True
00:22:41.180 Logical operation result is TRUE
00:22:41.180 Running script  : #!/bin/bash
00:22:41.180 
00:22:41.180 export GOPATH=$WORKSPACE/go
00:22:41.180 export GOROOT="/usr/local/go"
00:22:41.180 export PATH=${GOPATH}/bin:/usr/local/go/bin:/usr/sbin:/usr/local/bin:${PATH}
00:22:41.180 
00:22:41.180 cd $GOPATH/src/github.com/kata-containers/tests

**Comment by jcvenegas** [comment]
```
00:24:52.581 Install virtcontainers
00:24:52.585 make: Entering directory '/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR/go/src/github.com/kata-containers/runtime/virtcontainers'
00:24:52.586      GOBUILD  build
00:24:53.008      GOBUILD  hook

00:24:53.614      GOBUILD  kata-shim

00:24:55.142 make: Leaving directory '/tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR/go/src/github.com/kata-containers/runtime/virtcontainers'
00:24:55.208 /usr/local/bin/kata-runtime
00:24:55.208 Logging kata-env information:

00:24:55.759 Build step 'Execute shell' marked build as failure

00:25:02.984 Performing Post build task...
00:25:02.984 Match found for :.* : True
00:25:02.984 Logical operation result is TRUE
00:25:02.984 Running script  : #!/bin/bash
```
CI seems to be broken, the setup 

Seems that is related with https://github.com/kata-containers/tests/issues/2494 
but now, `chronic` is not failing but the same steps that where failing before now are broken again

**Comment by GabyCT** [comment]
@jcvenegas sorry I could not find the previous failure, what I can see right now in the latest test is that is failing but for another issue
```
16:12:06 /tmp/install-go-tmp.5xkTjY0HSS /tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR/go/src/github.com/kata-containers/runtime
16:12:06 curl: (22) The requested URL returned error: 500 Internal Server Error
16:12:06 Failed at 32: curl -o "${yq_path}" -LSsf "${yq_url}"
16:12:06 /tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR/go/src/github.com/kata-containers/tests/.ci/lib.sh: line 128: /tmp/jenkins/workspace/kata-containers-runtime-ubuntu-18-04-PR/go/bin/yq: No such file or directory
16:12:06 Missing go version or -p option
16:12:06 Usage:
16:12:06 
16:12:06 install_go.sh [options] <args>
16:12:06 
16:12:06 Args:
16:12:06 <go-version> : Install a specific go version.
16:12:06 
16:12:06 Example:
16:12:06 install_go.sh 1.10
16:12:06 
16:12:06 Options
16:12:06 -d <path> : destination path, path where go will be installed.
16:12:06 -f        : Force remove old go version and install the specified one.
16:12:06 -h        : Show this help
16:12:06 -p        : Install go defined in Kata Containers versions file.
```

**Comment by GabyCT** [comment]
@jcvenegas I saw the failure in the job, but for me it does not looked like the issue that we have before as the connection of the VM was failing completely, this seems that something else is missing maybe a backport fix

**Comment by jcvenegas** [comment]
Trying to know what is wrong with the CI https://github.com/kata-containers/runtime/pull/2666

**Pull request closed without merging**
