### PR TITLE
versions: Update CLH to version v0.10.0

### PR DESCRIPTION
**Pull request by likebreath**
We got a new release of cloud-hypervisor earlier today. The latest
release v0.10.0 contains the following updates: 1) `virtio-block`
Support for Multiple Descriptors; 2) Memory Zones; 3) `Seccomp` Sandbox
Improvements; 4) Preliminary KVM HyperV Emulation Control; 5) various
bug fixes and refactoring.

Fixes: #2973

Signed-off-by: Bo Chen <chen.bo@intel.com>

### CODE REVIEW

**Comment by likebreath** [comment]
Failures on  `jenkins-ci-podman-clh-fedora-31` and `jenkins-metrics-ubuntu-18-04` are known issues. Also, my take for the decreasing on the code coverage is a result of the new client package of `CLH HTTP API`.

**Review by jodh-intel — APPROVED** [review]
Thanks @likebreath.

lgtm

Do this need to be ported to 2.0?

**Comment by likebreath** [comment]
> Do this need to be ported to 2.0?

Yes, I will do that fair soon (afer landing this PR and the fix on the CLH CI in kata 2.0 https://github.com/kata-containers/kata-containers/pull/762). Note that we just updated the CLH version to v0.10.0 for kata 2.0 in PR https://github.com/kata-containers/kata-containers/pull/766, but we will need to upgrade the CLH client pkg to make sure the APIs in kata is consistent with the latest CLH API.

**Review by amshinde — APPROVED** [review]

**Comment by likebreath** [comment]
The `forward-port` PR in kata 2.0 is https://github.com/kata-containers/kata-containers/pull/790, and the issue is https://github.com/kata-containers/kata-containers/issues/789.

 When the above PR is merged, do I need to do anything else here given the label `needs-forward-port`? What's the advised practice to track the `forward-porting`?  Thanks @jodh-intel

**Comment by jodh-intel** [comment]
@likebreath - although I've raised https://github.com/kata-containers/community/pull/178, that doesn't yet include the process for tracking the ports. I'm currently working on that but the spoiler is - we'll need to add a "magic comment" to the original PR to "find" the ports I'm afraid. GitHub just doesn't provide the sorts of features that a complex project like ours requires ;(

**Comment by jodh-intel** [comment]
@likebreath - I'm removing the `needs-forward-port` label since fwics 2.x is using a newer version than 0.10.0 anyway.

**Pull request merged**
