### PR TITLE
WIP: DNM: qemu: update qemu vanilla version

### PR DESCRIPTION
**Pull request by chavafg**
Update qemu version to v4.0.0

Fixes: #1397.

Signed-off-by: Salvador Fuentes <salvador.fuentes@intel.com>

### CODE REVIEW

**Comment by chavafg** [comment]
please do not merge this change. Opened to check CI stability using qemu vanilla v3.1.0

**Comment by raravena80** [comment]
@chavafg nudge. We need this open?

**Comment by raravena80** [comment]
@chavafg @jcvenegas any updates? Thx!

**Comment by chavafg** [comment]
closing this one, superseded by #1744

**Pull request closed without merging**
