### PR TITLE
virtcontainers: GetOOMEvent should have no timeout

### LINKED ISSUE #2695: virtcontainers: GetOOMEvent make agent's goroutines leak
# Description of problem

Running the latest kata for some while, goroutines in agent will increasing continuously, about 1 goroutine per minute.

And it also produced many too many logs: 

```
May 21 09:36:00 master kata[30282]: time="2020-05-21T09:36:00.669881517Z" level=warning msg="failed to get OOM event from sandbox" error="rpc error: code = DeadlineExceeded desc = context deadline exceeded" sandbox=866635a11e6c426bf4ddf57c8d05ce9fa894e00eb7ae6b8ac9fb3546a07cf86b
```

# Expected result

Goroutines in agent should keep in a stable number.

# Reason

GetOOMEvent rpc call used 60 seconds as timeout:

https://github.com/kata-containers/runtime/blob/master/virtcontainers/kata_agent.go#L2015

And code in agent will blocked at https://github.com/kata-containers/agent/blob/master/grpc.go#L1807

### PR DESCRIPTION
**Pull request by liubin**
This will fix #2695

Signed-off-by: bin liu <liubin0329@gmail.com>

### CODE REVIEW

**Comment by grahamwhaley** [comment]
@awprice

**Comment by awprice** [comment]
Apologies for this! Thank you for fixing

**Comment by grahamwhaley** [comment]
Thanks for the contribution @liubin !
I think you will need to edit your commit a little to meet our contribution patch format guidelines - the CI system will complain otherwise. You can find details in the document at: https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#pull-requests

Please do ask if you need any help.

**Comment by lifupan** [comment]
@liubin Can you backport this fix into https://github.com/kata-containers/kata-containers 2.0-dev branch?

**Pull request merged**
